- .travis.yml
This catches a LOT of issues.
Signed-off-by: Ronald Minnich <rminnich@gmail.com>
> A first real test: cd bb and make sure bb builds.

- .travis.yml
- bb/bb.go
- bb/buildinit.go
- bb/config.go
- bb/ramfs.go
- glide.lock
To test this, you can do this:
sudo unshare -m chroot bbsh /init
Also, this fixes the problem of flags for *Var, since we need to change
the second argument, not the first.
> bb: change paths and how we build to match our new vendor/ setup.

- .travis.yml
Things will probably fail badly as soon as I try to run it. One step at a time.
> travis: add build of ramfs.go

- .travis.yml
- cmds/init/init.go
- cmds/installcommand/installcommand.go
- scripts/ramfs.go
- uroot/root.go
> Run ramfs.go

- README.md
> travis: add travis-ci badge to README.md

- scripts/ramfs.go
This one change is all we need to get away from having our
own specially built go toolchain. You still need a working toolchain
that is 1.5+ around, but you no longer have to build a static
version.
> ramfs: if the go command is not static, build a static one

- scripts/ramfs.go
> .travis.yml: run ramfs.go, don't just build it.

- glide.lock
- glide.yaml
It was not that good, we did not use that much of it,
and this gets rid of one import.
> Remove kr/pty package

- .travis.yml
> .travis.yml: enable sudo

- .travis.yml
> travis: try running ramfs again now that we have sudo

- cmds/which/which_test.go
Signed-off-by: Rafael Campos Nunes <rafaelnunes@engineer.com>
> For some reason which_test.go disappeared, I'm just uploading it again.

- roadmap.md
> Update TODO about new tests and add progress bar

- cmds/init/init.go
They want to be pid 1, make them happy.
> init: set up inito (original init) to run as pid 1

- cmds/validate/validate.go
This will take a file and a sum and try the file
out against a set of comma-seperated algorithm names.
> validate: finish adding validation functionality

- cmds/dmesg/dmesg.go
- glide.yaml
Signed-off-by: Mateus Pinto Rodrigues <mathgamain@openaliasbox.org>
> dmesg: use sys/unix/ Add golang.org/x/sys/unix to glide.yaml

- .travis.yml
- cmds/builtin/builtin.go
- cmds/cat/cat_test.go
- cmds/cp/cp_unix.go
- cmds/date/date_test.go
- cmds/dhcp/c2.go
- cmds/ectool/commands.go
- cmds/ip/ip.go
- cmds/ln/ln_test.go
- cmds/pflask/pflask.go
- cmds/ping/ping.go
- cmds/rush/parse.go
- cmds/tcz/tcz.go
- scripts/ramfs.go
- uroot/uname_amd64.go
> govet: require govet to pass for commits.

- .travis.yml
- travis.sh
This makes it easy for people to test the travis build
process.
> travis setup: break out the travis script into travis.sh

- travis.sh
The title pretty much summarizes the modification, now it is shown how
much of our code is being covered.
Signed-off-by: Rafael Campos Nunes <rafaelnunes@engineer.com>
> Now travis do a coverage of the cmds

- cmds/tcz/tcz.go
> tcz: If there is an existing symlink, and it's right, don't error out.

- .travis.yml
All we have to do now is
`go run scripts/getimports.go`
That script can run any number of times.
> glide: remove glide

- travis.sh
> Bring back vet for scripts

- scripts/getimports.go
> cleanup: getimports.go

- cmds/builtin/builtin.go
We had not tested this in quite some time as the Go compiler
slowdown made it just plain painful. Now that Go 1.6 is much better,
it was time to fix it.
It works again: try this
builtin hi {fmt.Printf("hi\\n")}
Rush quoting also works:
builtin hi '{ fmt.Printf("hi\\n") }'
> builtin: fix the builtin command.

- README
- README.md
- RUN_ME_FIRST
- scripts/getimports.go
> Update and fix the startup instructions.

- cmds/date/date.go
Not sure what I was thinking with that earlier code :-)
> date: use variadics

- cmds/date/date.go
I promise to write tests soon. This is embarrassing.
> date: Final set of bug fixes.

- cmds/kexec/kexec.go
Use /proc/cmdline if no -cmdline switch is used.
Tested and works fine.
> kexec: make command line /proc/cmdline

- cmds/kexec/kexec.go
> Changed printf to FatalF

- cmds/sync/sync.go
- cmds/sync/sync_test.go
This just uses the sync system call.
> Added sync command

- cmds/chmod/chmod.go
- cmds/chmod/chmod_test.go
> Added Chmod command

- bb/bb.go
- bb/ramfs.go
- bbnofork/bb.go
- bbnofork/ramfs.go
> Resolve go vet warnings in bb (busybox) and bbnofork (busybox all in one process) commands

- README.md
> Bring the README up to date

- bbnofork/bb.go
- cmds/builtin/builtin.go
- cmds/dhcp/c2.go
- cmds/dhcp/client.go
- cmds/dhcp/s.go
- cmds/echo/echo_test.go
- cmds/gitclone/gitclone.go
- cmds/hostname/hostname_test.go
- cmds/losetup/losetup.go
- cmds/mkdir/mkdir.go
- cmds/mv/mv.go
- cmds/mv/mv_test.go
- cmds/srvfiles/srvfiles.go
- cmds/tcz/tcz.go
- cmds/validate/validate_test.go
- cmds/wc/wc_test.go
- memmap/memmap.go
- memmap/memmap_test.go
- uroot/root.go
- uroot/uname_386.go
- uroot/uname_amd64.go
- uroot/uname_arm.go
- uroot/uname_ppc64le.go
> Run gofmt -s on the tree

- cmds/gpgv/gpgv.go
The openpgp package does not completely implement
rfc4880: it does not work for public keys with zero signatures.
Arguably, the standard is allowing too much flexibility,
but it's the standard and this omission in its implementation
has caused a problem.
Eric Grosse implemented a gpgv.go which correctly
handles this case.
> gpgv: add Eric Grosse's gpgv

- cmds/wc/wc.go
- cmds/which/which.go
I will do a few of these a day. I am hoping others will too.
> Fix up some golint errors

- README.md
> README: add the report card. Even if we don't get A+

- roadmap.md
Many of the listed commands have now been implemented. I added some more
commands to this wishlist as well as some args.
You can press the rich-diff button to see the formatted table. Be sure to comment if you want to add of subtract from the list.
An :x: means the command is not implemented at all yet.
> Update the roadmap

- website/docs/index.md
> website: fix Unlikely -> Unlike

- cmds/rush/exit.go
- cmds/rush/exit_test.go
> Add exit builtin and tests to rush

- uroot/uname_386.go
- uroot/uname_amd64.go
- uroot/uname_arm.go
- uroot/uname_ppc64le.go
See https://goreportcard.com/report/github.com/u-root/u-root
> Address warnings generated by `go vet`

- cmds/rush/rush_test.go
Fixes this flaky build failure: https://travis-ci.org/u-root/u-root/builds/198221840
> Widen test bounds to remove test flakiness

- cmds/false/false_test.go
- cmds/sort/sort.go
- cmds/sort/sort_test.go
- shared/test_util/test_util.go
- shared/testutil/testutil.go
The test was testing your system's `false` and not u-root's `false`; my
mistake.
This class of problems will be fixed with bug #116 as we can then check
the program is receiving code coverage.
> Fix command name in `false_test.go`

- cmds/comm/comm.go
- cmds/comm/comm_test.go
- roadmap.md
This address the comments in @mathgamain PR (https://github.com/u-root/u-root/pull/49) and adds table-driven testing.
> Add test for comm

- scripts/pre-commit
> Add pre-commit hook to gofmt, golint and go vet

- cmds/umount/umount.go
- cmds/umount/umount_linux.go
- roadmap.md
> Umount implementation for Linux

- cmds/umount/umount_linux.go
- uroot/uname_386.go
- uroot/uname_amd64.go
- uroot/uname_arm.go
- uroot/uname_ppc64le.go
> Remove unneccesary build constraints

- scripts/ramfs.go
Also cleaned up ramfs.go to pass golint
> Make ramfs.go handle empty directories

- cmds/mknod/mknod.go
- cmds/mknod/mknod_linux.go
- cmds/mknod/mknod_test.go
- roadmap.md
The test is still missing the most important case, but this is ok for
now.
> Implement mknod command

- cmds/chmod/chmod_test.go
> Correct print for error check in chmod_test

- cmds/installcommand/installcommand.go
The prevent the ambiguity, there are now two forms for installcommand.
> Parse installcommand args unambiguously

- cmds/init/init.go
> Revert "Installcommand exec"

- cmds/init/init.go
> Decrease the console loglevel

- cmds/dd/dd.go
- cmds/dd/dd_test.go
I had this vision in the beginning of goroutines talking through
memory pipes and doing one transform at each step.
The juice is not worth the squeeze. We don't need all those
transforms; the main need is blocking.
> dd: rewrite it

- cmds/ansi/ansi.go
- cmds/dd/dd.go
- cmds/fmap/fmap.go
- cmds/fmap/lib/fmap.go
- cmds/fmap/lib/fmap_test.go
- cmds/grep/grep.go
- cmds/kill/kill.go
- cmds/kill/kill_test.go
- cmds/kill/signaler_unix.go
- cmds/mount/mount.go
- cmds/rush/parse.go
- cmds/rush/rush.go
- cmds/seq/seq.go
> Fix more golint errors

- README.md
> Add badge link to the license

- cmds/installcommand/installcommand.go
- cmds/installcommand/installcommand_linux.go
> Propogate exit code in installcommand

- cmds/wget/wget.go
- cmds/wget/wget_test.go
- shared/testutil/testutil.go
This also adds a few improvements:
- More complete man page
- Return 1 if the HTTP status is not 200
> Wget tests

- cmds/dd/dd.go
- cmds/dd/dd_test.go
@rjoleary @rminnich @GanShun  Try this out and let me know if there are any bugs.
> Rewrite dd in idiomatic Go.

- cmds/pe/pe.go
> Add command for dumping PE file headers

- cmds/dd/dd.go
Just found this, figured I'd slim down my code a bit.
> Use ioutil.Discard instead of self-written nothingWriter.

- uroot/uname_arm64.go
This is required to build on arm64
> Add uname for arm64

- cmds/dhclient/dhclient.go
- cmds/dhclient/dhclient_test.go
- vendor/github.com/d2g/dhcp4/LICENSE
- vendor/github.com/d2g/dhcp4/README.md
- vendor/github.com/d2g/dhcp4/constants.go
- vendor/github.com/d2g/dhcp4/helpers.go
- vendor/github.com/d2g/dhcp4/option.go
- vendor/github.com/d2g/dhcp4/packet.go
- vendor/github.com/d2g/dhcp4client/LICENSE
- vendor/github.com/d2g/dhcp4client/README.md
- vendor/github.com/d2g/dhcp4client/client.go
- vendor/github.com/d2g/dhcp4client/inetsock.go
- vendor/github.com/d2g/dhcp4client/init.go
- vendor/github.com/d2g/dhcp4client/pktsock_linux.go
- vendor/vendor.json
> Newdhclient

- bb/bb.go
- bb/config.go
- bb/ramfs.go
This merges two needed fixes and the first of the two didn't even work.
> Just fix bb, already.

- cmds/dhclient/dhclient.go
We needed to make a packet socket, and we need to try to
set the interface up, as it might not be up. Further,
trying to force it up when it's not up catches a whole class
of issues.
But ...
it's possible we should put the 'bring it up' in the for loop, since
somebody might hot plug a connector or a switch might be slow to boot,
all things I've seen in real life. We'll have to keep that in mind.
> dhclient: get it to work

- cmds/ed/bin.go
- cmds/ed/command.go
- cmds/ed/ed.go
- cmds/ed/ed_test.go
- cmds/ed/text.go
- cmds/ed/types.go
> ed: simple ed command

- cmds/ls/ls.go
The code assumed all args were directories, leading to confusing behavior:
ls -l /dev/tty
crw-rw-rw- root tty 5, 0 May 10 08:02 .
tty is .? I don't think so. It now behaves more like the real ls.
> ls: fix ls

- bb/bb.go
- bb/config.go
- cmds/rush/tty_linux.go
With these changes, we now have ^C working in rush under bb.
> WIP: rush and bb: get control tty working

- cmds/dhclient/dhclient.go
Signed-off-by: Ron Minnich <rminnich@gmail.com>
> dhclient: add a node explaining a choice of subnet mask.

- cmds/dhclient/dhclient.go
There were a few remaining issues with v4 dhcp and setting
up the default route. This fixes them.
> dhclient: Set gateway properly

- cmds/insmod/insmod.go
Doesn't work yet
$ sudo ./insmod /lib/modules/4.6.0-1-amd64/kernel/drivers/net/ethernet/3com/3c59x.ko
insmod: error inserting '/lib/modules/4.6.0-1-amd64/kernel/drivers/net/ethernet/3com/3c59x.ko': 18446744073709551615 exec format error
> add insmod

- uroot/root.go
We've had a relatively simply model for root file systems
that let us mkdir, mknod, mount, and create files.
minimega wants cgroups, and we're building minimega appliances,
so we need to bend in that direction.
cgroups breaks our simple model; it requires this weird interleaving
of mkdir, mount, mkdir, mount, symlink games. See: systemdwars(1)
The new state machine takes an array of interface{}, does a
basic type switch and takes action. The code is actually a lot
easier on the eyes, it turns out.
> uroot/root.go: modify/extend it for more complex roots

- cmds/mm/mm.go
- uroot/root.go
It's just too much typing otherwise.
David and John, you probably want to clean this up a bit!
> mm: add a convenience command for starting minimega

- bb/ramfs.go
- pkg/cpio/cpio.go
- pkg/cpio/fs_unix.go
- pkg/cpio/newc/newc_test.go
- pkg/cpio/sysinfo_darwin.go
- pkg/cpio/sysinfo_linux.go
- pkg/cpio/types.go
- travis.sh
These are essential for the firnware embedded case, and useful for all other
cases.
> reproducibility changes.

- cmds/io/io.go
- cmds/io/io_linux.go
- travis.sh
I have no idea how to test since it requires root priveleges and how would you
know if you'd done anything right? I will try to work up some error tests.
We need this to test SMI operations. And outb at the right place should cause
an SMI.
> io: support io ops at the command line

- cmds/dhclient/dhclient.go
Set correct dst address after getting it with dhcpv4 protocol.
> Fixed dhcpv4 dst address

- cmds/dhclient/dhclient.go
Fixed route replacement and addition.
> Fixed RouteReplace

- cmds/dhclient/dhcp6client/dhcp6client.go
- cmds/dhclient/dhcp6client/packet.go
- cmds/dhclient/dhcp6client/packetSock.go
- cmds/dhclient/dhcp6client/packet_test.go
- vendor/github.com/google/netstack/LICENSE
- vendor/github.com/google/netstack/ilist/list.go
- vendor/github.com/google/netstack/tcpip/buffer/prependable.go
- vendor/github.com/google/netstack/tcpip/buffer/view.go
- vendor/github.com/google/netstack/tcpip/header/arp.go
- vendor/github.com/google/netstack/tcpip/header/checksum.go
- vendor/github.com/google/netstack/tcpip/header/gue.go
- vendor/github.com/google/netstack/tcpip/header/icmpv4.go
- vendor/github.com/google/netstack/tcpip/header/interfaces.go
- vendor/github.com/google/netstack/tcpip/header/ipv4.go
- vendor/github.com/google/netstack/tcpip/header/ipv6.go
- vendor/github.com/google/netstack/tcpip/header/ipv6_fragment.go
- vendor/github.com/google/netstack/tcpip/header/tcp.go
- vendor/github.com/google/netstack/tcpip/header/udp.go
- vendor/github.com/google/netstack/tcpip/tcpip.go
- vendor/github.com/google/netstack/waiter/waiter.go
- vendor/vendor.json
Chris added a new dependency, netstack header, which includes helper functions that we need for wrapping up and parsing packets.
Xuan fixed the unit tests based on cleanups.
> DHCPv6 Cleanups and Unit Test Fixing

- cmds/dhclient/dhclient.go
> Disable test mode in default

- cmds/dd/dd.go
I found this is necessary to estimate how long a dd will take.
The `progress` flag may be one of the following:
- `none`: nothing extra is printed to stderr
- `xfer`: print transfer stats after completion (default)
- `progress`: progressively print transfer stats during copy (GNU)
I performed a bit of benchmarking and the addition of the feature has no
noticeable penalty on performance.
> Add status flag to dd

- README.md
- website/docs/index.md
> Added elvish usage in README.md

- bb/ramfs.go
bb -cpio 'a.cpio b.cpio'
will add the cpio archives to the initramfs it generates.
The archives must be in newc format.
> bb: allow additional cpio archives

- cmds/dhclient/dhclient.go
- pkg/dhcp6client/dhcp6client.go
Timeout defines the max waiting duration of each time after the client
sends out a DHCPv6 solicit message. The client waits for a valid DHCPv6
reply from server until time is out.
Users are able to define the amount of time that they want the client to
send the solicit message at most, before it receives a valid DHCPv6
packet.
> Timeout for DHCPv6 Client

- bb/ramfs.go
error with argument passing when there is trailing or starting whitespace
> Trimmed beginning and ending whitespace to parse argument

- cmds/cp/cp_test.go
> changed path.Join to filepath.Join in cp files

- cmds/cat/cat_test.go
Changes only reflected in cat_test.go #fixes 317 #317
> Changed path.Join to filepath.Join for cat cmd

- cmds/mv/mv.go
- cmds/mv/mv_test.go
Added filepath import statement to mv.go #fixes 316
> mv: Changed path.Join to filepath.Join 

- cmds/dhclient/dhclient.go
- cmds/dhclient/dhclient_test.go
The code should see if the link is up, and if so return immediately.
It should not return until the link is up.
30 seconds is about as long as one should try.
This will make it so you no longer have to hit ^C on the
first dhclient :-)
> dhclient: improve ifup code

- cmds/console/console.go
- cmds/console/i8042_linux.go
- cmds/console/port_linux.go
- cmds/console/uart_linux.go
This is really naive at present, it has no map
and just forwards the characters.
> i8042: add i8042 support to console

- cmds/id/id.go
- cmds/id/id_test.go
This pull request contains the tests and implementation of the ID command. So far it only has the flags, "G, g, u, n". Here are the reasons I chose not to implement the rest:
"a" This flag is called  "ignore, for compatibility with other versions"
"Z" Only valid with SELinux kernel
"r" This flag prints real IDs, but this command automatically prints the real IDs
> ID command

- cmds/tcz/tcz.go
> tcz: move to version 8.x

- cmds/xinit/xinit.go
If the correct tczs are installed, you can run xinit
and in a second or so see x11, and in 5 seconds
see a terminal.
Author:    Ananya Joshi <ananya@ananya.co>
> Final set of changes for xinit to get us to a working x11 screen

- cmds/xinit/xinit.go
we want a wm (although this is not working -- still have to type flwm by hand)
and we might as well fire up opera-12 to make sure that path will always work.
> Start up opera-12 and flwm

- cmds/tcz/tcz.go
the tcz dependencies sometimes have errors. This change
allows program calling tcz to specify a list of packages
to ignore.
E.g.,
tcz -skip "wireless-KERNEL openssl"
will skip those two packages and all their dependencies.
> tcz: implement a skip list

- travis.sh
> fixvboot: re enable ppc64le

- travis.sh
only set GOPATH if it is not set.
> travis.sh: make it so anyone can run travis

- cmds/ip/ip.go
so you can now do things like this:
ip a s
ip ad sh
and so on
> ip: add a simple function so we can use minimal unique subsets

- CONTRIBUTING.md
- MAINTAINERS.md
- README.md
Info from README.md and MAINTAINERS.md is updated and merged into a new
CONTRIBUTING.md.
Signed-off-by: Tim Pepper <tpepper@vmware.com>
> add contributing doc

- cmds/dirname/dirname.go
- cmds/dirname/dirname_test.go
The various chrome scripts need it.
> dirname: add dirname command

- pkg/ldd/ldd_test.go
- pkg/ldd/ldd_unix.go
- pkg/ldd/ldso_linux.go
> Fix ldd_test to test shared library dependency checking

- cmds/ed/command.go
- cmds/io/io.go
- cmds/kill/kill_test.go
- cmds/wget/wget.go
Some of these might actually be bugs -- the error code is not being
checked properly.
Signed-off-by: Ryan O'Leary <ryan@ryanoleary.ca>
> Fix some lint errors

- cmds/xinit/xinit.go
Too many programs have forgotten about -display.
> xinit: Move from -display argument to DISPLAY env variable

- cmds/init/init.go
Both `inito` and `uinit` are optional. So it's better to test file existence before trying to execute it.
> Avoid command not found error on boot

- cmds/insmod/insmod.go
- cmds/lsmod/lsmod.go
- cmds/rmmod/rmmod.go
While I intended to work on lsmod/rmmod, I stumbled about a bug in insmod. Boring implementation work ;-), for details please see the according commits.
This was tested with "bb", my current Debian testing kernel (4.13.0-1-amd64), and a simple hello.ko
In sum this Fixes #245.
Regards, rck
> Fix bug in insmod, implement lsmod and rmmod

- cmds/kexec/kexec.go
- cmds/kexec/kexec_linux.go
- cmds/kexec/kexec_test.go
- pkg/kexec/kexec_linux.go
- pkg/kexec/kexec_linux_amd64.go
- pkg/kexec/kexex_linux_other.go
> Make kexec compatible with Linux kexec

- scripts/ramfs.go
> Use runtime-given Goarch, GOROOT when env vars not set.

- bb/config.go
> Simplify gussing GOROOT, GOARCH, and GOPATH for bb.

- bb/config.go
I broke bb in #410. This fixes it.
> bb: Set config.Gopaths as needed. This unbreaks bb.

- cmds/truncate/truncate.go
- cmds/truncate/truncate_test.go
So far it did not exist, so implement it.
Signed-off-by: Roland Kammerer <dev.rck@gmail.com>
> truncate: Implement command

- roadmap.md
Add the commands I recently touched and did not already exist in the roadmap.
> roadmap: Add insmod, lsmod, rmmod, truncate

- bb/ramfs.go
- cmds/lddfiles/lddfiles.go
- pkg/ldd/ldd_test.go
- pkg/ldd/ldd_unix.go
- pkg/ldd/ldso_linux.go
> ldd: give package the right name.

- README.md
- cmds/mknod/mknod_linux.go
- cmds/mount/mount.go
- cmds/stty/termios.go
- cmds/umount/umount_linux.go
- cmds/validate/validate.go
This PR fixes a few minor issues that caught my eye while working on other u-root stuff. Please see the individual commits for details.
> Various cleanups

- cmds/rush/tty_linux.go
Use IoctlGetInt/IoctlSetInt from golang.org/x/sys/unix instead of
locally re-implementing them.
> cmds/rush: use ioctl functions from x/sys/unix

- cmds/wifi/wifi.go
Tested at SC17 where there is no password.
> wifi: make it work on nets with no password

- pkg/kexec/kexec_linux.go
- pkg/kexec/kexec_linux_amd64.go
> kexec fixes

- cmds/wifi/wifi.go
Suppose you need an ESSID, a username, and a password: will that work?
Yes, now it does. Tested and working.
> wifi: now supporting EAP!

- Gopkg.lock
- Gopkg.toml
- cmds/truncate/truncate.go
- cmds/truncate/truncate_test.go
- vendor/github.com/rck/unit/unit.go
- vendor/github.com/rck/unit/unit_test.go
This was discussed in: https://github.com/u-root/u-root/issues/424
Again, thanks to Chris for his feedback.
If this goes in, I then start git-grepping the tree to find other users for this package.
Closes #424
> Vendor in unit package and make truncate the first user

- Gopkg.lock
- cmds/dd/dd.go
- cmds/dd/dd_test.go
- vendor/github.com/rck/unit/unit.go
- vendor/github.com/rck/unit/unit_test.go
This is just a follow up to the unit package that got recently merged.
As my time is currently a bit limited, this conversions will drop in as individual pull requests, tool per tool. Hope that is okay.
I tested it as committed, with the exception that the last test (the multiple GB memory bomb) was disabled.
> dd: use unit package

- LICENSE
Same license, it just allows GitHub to recognize the license and display it in the UI.
> Update LICENSE to a GitHub-recognized template.

- pkg/golang/build.go
- pkg/uroot/bb.go
- pkg/uroot/source.go
- pkg/uroot/uroot.go
@insomniacslk
the least I could fix right now, because all that was bothering me.
> pkg/golang: standardize terminology and documentation.

- cmds/ps/ps_linux.go
- Remove unneeded conversion of ints
- Open /proc directly and Readdir
- Iterate the resulting slice of FileInfo
> cmds/ps: Small optimizations

- CONTRIBUTING.md
General cleanup of the contrib doc. Update for CircleCI. Added some general guidelines that I hope mirror what I've seen @rminnich iterate a few times on PRs.
> Update contributing to u-root doc

- cmds/shutdown/shutdown_test.go
- cmds/sync/sync_test.go
> cmds: remove empty test files.

- .circleci/config.yml
- cmds/ip/ip.go
- cmds/shutdown/shutdown.go
- cmds/switch_root/switch_root.go
- pkg/gpt/gpt.go
- travis.sh
> Fixes for arm 7 including continuous build

- cmds/tcz/tcz.go
This fixes NiChrome when we have multiple users.
> tcz: make directories 0755, not 0700

- pkg/cpio/fs_unix.go
> cpio: on extract, honor unix bits like SUID, GUID, and sticky

- README.md
I created a status only token under the u-root project following this [guide](https://circleci.com/docs/1.0/status-badges/#access-control)
> Update Build Badge to point at circleci

- cmds/tcz/tcz.go
> tcz: Only create the tinycoreroot directory if we're installing

- cmds/free/free.go
Addressed the feedback from @hugelgupf in https://github.com/u-root/u-root/pull/556 about grouping
variables and using `switch` instead of a bunch of `if..else`
> cmds/free: better syntax

- README.md
Signed-off-by: Sven Dowideit <sven.dowideit@csiro.au>
> docs: Add info on src:dst for adding files

- pkg/golang/build.go
Previously, if one set the GOROOT environment variable, we would not
actually use the the compiler found in $GOROOT/bin/go, but the compiler
found in $PATH.
build.Context.GOROOT is by default the compiled code's GOROOT, unless
the GOROOT environment variable is set.
cc @osresearch
> pkg/golang: use GOROOT to find the correct compiler.

- cmds/shutdown/shutdown.go
I've tested this in qemu and all variations work.
how to test is not that clear, so I've removed the test.
> working shutdown command

- pkg/golang/build.go
- pkg/uroot/bb.go
- pkg/uroot/bb_test.go
- pkg/uroot/cpio.go
- pkg/uroot/test/foo/foo.go
- u-root.go
Fixes #423.
Still a work in progress, but seems to work with all of our existing ./cmds/* tools. (It compiles, I haven't tried it yet. But I'm taking that as a good sign...)
The downside is that bb mode now takes longer to create an initramfs than source mode. But it's still manageable.
cc @prattmic @rminnich @rjoleary
> pkg/uroot: rewrite bb to be more general

- .circleci/config.yml
Add a test for source mode building.
Closes https://github.com/u-root/u-root/issues/607
> Source Mode Archive Build Testing

- Examples/uinit/README.md
- Examples/uinit/uinit.go
writing down some of what I unearthed - for eg #328
I'd love some suggestions - I like what I'm seeing :)
> Example uinit.go

- cmds/shutdown/shutdown.go
- cmds/shutdown/shutdown_test.go
> shutdown: add a test

- cmds/dd/dd_test.go
patch to reduce dd test runtime from ~150s to ~35s on my machine(#616)
> reduced time consume by dd test

- cmds/mkdir/mkdir.go
- cmds/mkdir/mkdir_test.go
* Change its default creation mode to 0777
* Make -m flag work as expected from regular mkdir
> Fix #624: Write test for mkdir and make its permission work correctly

- Gopkg.lock
- cmds/wifi/wifi.go
- cmds/wifi/wifi_test.go
- pkg/testutil/testutil.go
- pkg/wpa/passphrase/passphrase.go
- pkg/wpa/passphrase/passphrase_test.go
- vendor/golang.org/x/crypto/pbkdf2/pbkdf2.go
- vendor/golang.org/x/crypto/ssh/certs.go
- vendor/golang.org/x/crypto/ssh/client_auth.go
Also, refactor test helper functions in wifi_test.go into testutil pkg and reuse it in passphrase_test.go
> Write wpa/passphrase pkg in Go and use it inside wifi cmd

- cmds/forth/forth.go
- pkg/forth/forth.go
- pkg/forth/forth_test.go
This may seem crazy but it's actually a handy little interpretive
language. I had forgotten about this until trammell mentioned forth.
We used this to parse command lines in a 500 node cluster, where
each node got the same command and needed to turn it into a pod
(via / and %) and a node (via other operations).
If this gets in I'll write a trivial forth cli -- or maybe just
make rush into a forth shell?
> Add the forth package

- cmds/ping/ping.go
Build a proper ICMP echo request packet; check the
response to make sure it's well-formed and corresponds
to the request packet we sent.
Signed-off-by: Dan Cross <cross@gajendra.net>
> ping: Fix this to actually work.

- .circleci/config.yml
- pkg/uroot/uroot.go
This commit addresses https://github.com/u-root/u-root/issues/650
> Fix regression in -files command

- cmds/sos/sos.go
- cmds/sos/sosServer.go
- cmds/sos/sosServer_test.go
- cmds/sos/sos_test.go
Proof-of-concept work for NiChrome
> (Experimental) Service of Services (SoS) with register and unregister enabled

- cmds/sos/sos.go
- cmds/sos/sosServer_test.go
- cmds/sos/sos_test.go
This is branched off from https://github.com/u-root/u-root/pull/678
So if both of PRs are approved, please merge this one and close https://github.com/u-root/u-root/pull/678
> (Experimental) Add test cases for SoS Server and Change function signature for read

- scripts/pre-commit
> Fixing go vet for pre commit hook

- cmds/sos/sosServer_test.go
- cmds/sos/sos_test.go
> Incorporate Read into race test of SoS Server

- pkg/dhcp6client/client.go
- pkg/dhcp6client/client_test.go
> pkg/dhcp6client: wait for reading goroutines to exit before returning.

- cmds/sos/sos.go
> sos: brings up locahost before starting the server

- cmds/mount/mount.go
changed usage string to reflect exact rules
inform user if filesystem type not supported
Signed-off-by: Francois-Frederic Ozog <ff@ozog.com>
> cmds/mount: change usage/error reporting

- cmds/pxeboot/pxeboot.go
- pkg/boot/boot.go
- pkg/boot/linux.go
- pkg/boot/linux_test.go
- pkg/boot/measurement.go
- pkg/boot/measurement_test.go
- pkg/boot/multiboot.go
- pkg/boot/package.go
- pkg/boot/package_test.go
- pkg/cpio/cpio.go
- pkg/cpio/types.go
- pkg/pxe/pxe.go
- pkg/pxe/pxe_test.go
- pkg/pxe/schemes.go
- pkg/pxe/schemes_test.go
- pkg/uio/reader.go
@Natolumin and @insomniacslk 
the intent is for pkg/boot to be used in pxeboot and disk boot and netboot21. The design is somewhat copied from #509 :)
> pkg/boot: shared bootloader logic.

- pkg/uroot/bb.go
Makes u-root initramfs' reproducible again. Fixes #714.
> pkg/uroot/bb: deterministically rewrite packages.

- cmds/init/init.go
- pkg/gzip/file_test.go
- pkg/gzip/options_test.go
- pkg/uroot/util/root.go
SystemD can't start if it spots that cgroups /proc files have been created. It also requires that init really has PID1.
> Add a flag that'll allow u-root to start systemd

- cmds/mknod/mknod_linux.go
This is not the right way to fix this, so I'm going to file an issue,
but for now it gets me out of a spot.
How I hate special files. I miss Plan 9.
> mknod: fix bits for major and minor

- u-root.go
* We want to have a really minimal environment with less commands.
> Add coreboot-app template

- .circleci/config.yml
- pkg/uroot/uroot.go
> pkg/uroot: undo rename of function, add CI for makebb.

- pkg/uroot/test/gopath1/src/foo/foo.go
- pkg/uroot/test/gopath1/src/os/os.go
- pkg/uroot/test/gopath2/src/mypkga/mypkga.go
- pkg/uroot/test/gopath2/src/mypkgb/mypkgb.go
- pkg/uroot/uroot.go
- pkg/uroot/uroot_test.go
First go at issue #659 
Note that I marked some things I was unsure about with TODOs. Those need to be cleaned up before this can be submitted.
Option 2 to make the testing more isolated would be to mock out our golang.Environ: https://github.com/subhav/u-root/commit/dcdce24836ceef2951c1f95d6a5dd59a802c397e
> Look through GOROOT and all GOPATHS when resolving packages by path.

- html/sos.html
- pkg/sos/server.go
Signed-off-by: jbetancourt <jmbetancourt@google.com>
> add the ability to read in external html files

- pkg/uroot/bb.go
- pkg/uroot/bb_test.go
- tools/makebbmain/main.go
I know it just looks like I'm moving code around arbitrarily. I am. It helps though. More code to be exported soon.
> pkg/uroot/bb: modularizing code for bazel-based build; adding docs.

- cmds/upspin_sos/server.go
- pkg/sos/html/css/stylesheet.css
- pkg/sos/html/upspin.html
still need to wait to see how it works with a functional upspin
> bring sos upspin page up to date with new interface

- cmds/upspin_sos/server.go
- cmds/wifi/server.go
Signed-off-by: jbetancourt <jmbetancourt@google.com>
> remove hardcoded paths

- pkg/sos/html/css/stylesheet.css
- pkg/sos/html/upspin.html
Signed-off-by: jbetancourt <jmbetancourt@google.com>
> fix disabled fields on upspin page

- pkg/gpt/gpt.go
- pkg/gpt/gpt_test.go
this is gross. Just less gross than so many other things.
>  gpt: don't use broken google UUID package, just create GPT type

- cmds/basename/basename.go
- cmds/basename/basename_test.go
* Support using suffix flag with unlimited positional arguments
* Suffix positional after filename
* Single argument
Implements https://github.com/u-root/u-root/issues/782
> Implement basic basename command

- cmds/mktemp/mktemp.go
- cmds/mktemp/mktemp_test.go
Add the `mktemp` command and tests.
Implements https://github.com/u-root/u-root/issues/784
> Implement mktemp command

- cmds/strings/strings.go
- cmds/strings/strings_test.go
Fun fact: An vulnerability was found in binutil's strings in 2014: https://lcamtuf.blogspot.com/2014/10/psa-dont-run-strings-on-untrusted-files.html
> strings: Add strings command

- Gopkg.lock
- cmds/ip/ip.go
- cmds/ip/ops.go
> ip: return all errors to main

- xcmds/.gitignore
> xcmds: Ignore binary files

- cmds/ls/ls.go
- cmds/ls/ls_test.go
Now we can do ls -lR, finally!
> ls: use the spf13 flag package

- cmds/init/init.go
- cmds/io/io.go
- cmds/io/io_linux.go
- cmds/io/io_test.go
- cmds/rush/parse.go
- cmds/upspin_sos/service.go
- pkg/boot/measurement.go
- xcmds/ash/main.go
- xcmds/ed/command.go
- xcmds/ed/ed_test.go
> Fixed some serious lint errors

- pkg/uroot/README.md
See rendered: https://github.com/hugelgupf/u-root/blob/bb-readme/pkg/uroot/README.md
> pkg/uroot/bb: add a README describing Go busybox.

- .circleci/config.yml
> circleci: Check licenses

- .circleci/config.yml
- cmds/dd/dd_test.go
> circleci: Run ineffassign

- pkg/cmdline/cmdline.go
- pkg/dhcp6client/client.go
- pkg/diskboot/parser.go
- pkg/sos/client.go
- pkg/wifi/iwl.go
- pkg/wpa/passphrase/passphrase.go
> misspell: Fix errors automatically detected

- cmds/kexec/kexec_linux.go
> kexec: Use pflag

- cmds/sos/sos.go
- pkg/sos/server.go
- pkg/sos/server_test.go
Addresses #834 and fixes test errors
> sos: flag from pkg to cmds

- README.md
> readme: Update Go version

- cmds/sshd/sshd.go
Builds upon https://github.com/u-root/u-root/pull/885
Title says it all
> Return exit status to client for SSH

- RELEASES
> Initial release

- pkg/uroot/uroot.go
> Fix defaults

- cmds/tee/tee.go
Added missing file.Close(), minor refactorings.
> Minor improvements to tee

- cmds/sshd/sshd.go
- cmds/time_sos/service.go
- pkg/bzimage/header.go
> Fix spelling mistakes

- cmds/init/init.go
> Print logo in init

- pkg/uroot/builder/bb/bb.go
> Double timeout for bb

- .circleci/config.yml
> Missing quotes in shell expansion

- cmds/wget/wget.go
Comment fix for https://github.com/u-root/u-root/issues/942
> Update wget example to use output flag

- RELEASES
> v2.0.0 release

- .circleci/config.yml
- .gitignore
- Gopkg.lock
- integration/integration_test.go
- pkg/qemu/qemu.go
- vendor/github.com/google/goexpect/expect.go
> Save qemu serial output

- pkg/qemu/qemu.go
> qemu: RE matches return the matched string

- integration/gotest_test.go
Before this change, each package which does not contain a test needed to
be included in the blacklist; otherwise, an unhelpful error message is
printed. This was bound to fail as soon as a new package is added. This
change skips those package without tests.
> integration: Ignore packages without tests

- cmds/strace/strace.go
- pkg/strace/strace.go
- pkg/strace/strace_test.go
- pkg/strace/strace_unix.go
This is the start of strace. First things first, this simple package lets
you trace system calls.
I'll be using the gvisor pretty printer code for records I expect.
> strace package

- pkg/kmodule/kmodule_linux.go
Signed-off-by: David Disseldorp <ddiss@suse.de>
> kmodule: consider modules.builtin if present

- roadmap.md
- 7 new commands and flags have been implemented!
- When we switched to Elvish, we lost the "time" builtin, so one will
need to be implemented.
> roadmap: Update

- cmds/strace/strace.go
- pkg/strace/strace_unix.go
- pkg/strace/syscall_linux.go
- pkg/strace/syscall_linux_amd64.go
- pkg/strace/tracer.go
- pkg/strace/types.go
To test:
strace /bin/sh
and see what shakes.
or strace /bin/sh -c /bin/date
TODO: more tests
> Implement multiprocess tracing

- cmds/mv/mv_test.go
Should resolve https://github.com/u-root/u-root/issues/949
> Update mv tests to check content and inode

- cmds/ps/ps.go
- cmds/ps/ps_linux.go
- cmds/ps/ps_test.go
note: I realize this is not  up to our current standards, but it now at least passes
golint
go vet
and it sort of has a test. 
We'd never let it go in this way today but ... well ... be gentle.
I think if it's even an improvement we should start here and I'll keep at it.
> ps: cleanup, add tests

- pkg/forth/forth.go
- pkg/forth/forth_test.go
Since I wrote this some Go style rules have changed.
Further, while the Forth standard seems to imply the stack
is always strings, it just seems nicer to have our cells
be an interface{}.
It now also passes golint and go vet. We include a new
test for mismatched interfaces, e.g. adding w to a []byte
won't get you very far.
> Forth: define Cell type for stack, cleanup

- cmds/strace/strace.go
> Strace supports forking

- RELEASES
> v3.0.0 release

- cmds/ps/ps.go
The old school non-flag-syntax args are deprecated.
Leave in ps aux for now, but we may remove it later.
> ps: adopt spf13 flag package, remove permutation stuff

- pkg/uio/buffer.go
to be used in dhcp4 code and in some other bits.
> pkg/uio: add buffer for byte manipulation in network order.

- integration/gotest_test.go
- integration/integration.go
> Skip integration tests 40 seconds faster

- Gopkg.lock
- Gopkg.toml
- vendor/github.com/anmitsu/go-shlex/LICENSE
- vendor/github.com/anmitsu/go-shlex/shlex.go
- vendor/github.com/gliderlabs/ssh/LICENSE
- vendor/github.com/gliderlabs/ssh/agent.go
- vendor/github.com/gliderlabs/ssh/conn.go
- vendor/github.com/gliderlabs/ssh/context.go
- vendor/github.com/gliderlabs/ssh/doc.go
- vendor/github.com/gliderlabs/ssh/options.go
- vendor/github.com/gliderlabs/ssh/server.go
- vendor/github.com/gliderlabs/ssh/session.go
- vendor/github.com/gliderlabs/ssh/ssh.go
- vendor/github.com/gliderlabs/ssh/tcpip.go
- vendor/github.com/gliderlabs/ssh/util.go
- vendor/github.com/gliderlabs/ssh/wrap.go
- vendor/github.com/vishvananda/netlink/link_linux.go
- vendor/github.com/vishvananda/netlink/nl/nl_linux.go
- xcmds/sshd/sshd.go
> xcmds/sshd: add a new sshd based on the gliderlabs package

- pkg/loop/losetup_linux.go
- xcmds/pox/pox.go
pox was using cpio memory archives for reasons I no longer
recall, possibly because I intended to use them instead
of squashfs.
Instead of fussing with cpio,
fix pox to just copy the files, preserving mode.
I don't read the file into memory as it pays to keep small
memory systems in mind.
This also uncovered a bug in the loop package, now fixed.
> pox: fix pox and an old nasty loop pkg bug

- pkg/kexec/memory_linux.go
- pkg/kexec/memory_linux_test.go
> multiboot: align module starts to a page boundary

- .circleci/config.yml
- .circleci/images/integration/Dockerfile
- integration/multiboot_test.go
- pkg/multiboot/description.go
- pkg/multiboot/module.go
- pkg/multiboot/multiboot.go
- pkg/multiboot/reader.go
> multiboot: read gzipped kernels

- xcmds/esxiboot/esxiboot.go
> multiboot: command to boot ESXi

- cmds/kexec/kexec_linux.go
- pkg/kexec/memory_linux.go
- pkg/multiboot/internal/trampoline/trampoline_linux_amd64.s
- pkg/multiboot/multiboot.go
Fix typos, comments.
Remove unused code.
> multiboot: minor refactoring

- RELEASES
> v4.0.0 release

- LICENSE
> Update LICENSE to 2019

- pkg/zimage/zimage.go
- pkg/zimage/zimage_test.go
> zimage: Minor improvements

- cmds/elvish/sys/winsize_unix.go
Use the IoctlGetWinsize function and Winsize type from
golang.org/x/sys/unix in sys.GetWinsize instead of duplicating it.
> cmds/elvish: use unix.IoctlGetWinsize and unix.Winsize

- pkg/uroot/builder/bb/bb.go
> bb: Delete stale files

- cmds/dmesg/dmesg.go
Also remove the unused _SYSLOG_ACTION_READ const.
> cmds/dmesg: use unix.Klogctl

- cmds/ping/ping.go
Using a time.Duration with %v format specifier in fmt.Sprintf already
leads to a pretty printed duration (ns, µs, ms, s), thus beatifulLatency
is not necessary. Also don't include the buffer allocation and ICMP
reply validation in the latency, only the actual duration of c.Read.
> cmds/ping: use %v format specifier to format latency duration

- cmds/fusermount/fusermount.go
- cmds/fusermount/fusermount_linux.go
- cmds/fusermount/fusermount_test.go
- integration/gotest_test.go
We're going to need this for sshfs and we've needed it for nichrome.
> Simple fusermount

- cmds/init/init.go
> Remove verbose message

- .circleci/config.yml
> Disable cgo for clean code tests

- .circleci/config.yml
> Only run TestUrootCmdline once

- cmds/installcommand/installcommand.go
@rminnich does this work for you?
> installcommand: avoid using cgo

- cmds/pxeboot/pxeboot.go
- pkg/ipxe/ipxe.go
- pkg/ipxe/ipxe_test.go
- pkg/pxe/mock_schemes.go
- pkg/pxe/pxe_test.go
- pkg/pxe/schemes_test.go
Written in co-ordination with hugelgupf and rjoleary.
> Add trivial support for IPXE configs for netboot.

- cmds/boot/boot.go
few improvements to the boot command
tested on: qemu, winterfell
> Cmds boot refactor

- cmds/dmesg/dmesg_test.go
> more dmesg output

- cmds/dmesg/dmesg_test.go
> dmesg: Disable dmesg test

- Gopkg.lock
- pkg/dhclient/dhclient.go
- pkg/dhclient/dhcp4.go
- vendor/github.com/insomniacslk/dhcp/dhcpv4/dhcpv4.go
- vendor/github.com/insomniacslk/dhcp/dhcpv4/option_routes.go
- vendor/github.com/insomniacslk/dhcp/dhcpv4/options.go
- vendor/github.com/insomniacslk/dhcp/dhcpv4/types.go
> Classless Static Routes

- pkg/dhclient/dhcp4.go
- pkg/dhclient/dhcp4_test.go
> dhcp4: return errors when no boot file or server name is found

- pkg/sh/run.go
> Add sh.Run function and documentation

- pkg/sh/run.go
> Add RunWithLogs function to sh

- cmds/crc/crc.go
> Add crc command

- pkg/io/seek.go
> Use io.SeekStart for io command

- pkg/dhclient/dhclient.go
> dhclient: Poll until IPv6 address is not tentative

- cmds/grep/grep.go
- cmds/tcz/tcz.go
- pkg/tar/tar.go
> Fix potential panics in filepath walks

- cmds/rsdp/rsdp.go
- pkg/acpi/rsdp.go
- pkg/acpi/rsdp_test.go
- pkg/acpi/sdt.go
- pkg/acpi/sdt_test.go
- pkg/kexec/kexec_linux_amd64.go
- pkg/multiboot/multiboot.go
- pkg/uroot/util/root.go
> Refactor away one of the GetRSDP functions

- pkg/tar/tar.go
> Add VerboseLogFilter function for tar

- cmds/switch_root/switch_root.go
- pkg/mount/switch_root_linux.go
Signed-off-by: Mark Pictor <mpictor@gmail.com>
> Move some code from cmds/switch_root to pkg/mount; export useful funcs.

- pkg/ipxe/ipxe.go
- pkg/ipxe/ipxe_test.go
> ipxe: Print the config only if it's an ipxe config

- pkg/ebda/ebda.go
- pkg/ebda/ebda_test.go
- xcmds/fixrsdp/fixrsdp.go
Also, add a hacky fixrsdp command that may not work at best.
> ebda: Add functions to access the EBDA

- pkg/acpi/rsdp.go
> pkg: acpi: rsdp: Add print failure for debugging

- xcmds/fixrsdp/fixrsdp.go
> xcmds: fixrsdp: open /dev/mem rw

- pkg/pxe/schemes.go
This is a useful work around for intermittent network issues and
probably a good idea overall because networks are never perfect.
> pxe: Add scheme for retrying HTTP connections

- pkg/dhclient/dhclient.go
> dhclient: Use optmistic DAD to configure lease

- pkg/boot/linux.go
> boot: Add nil-check to LinuxImage.Execute

- cmds/exp/rush/rush.go
> Fix pipe to write_only files

- cmds/core/elvish/eval/vals/kind.go
- cmds/exp/cpu/cpu.go
- pkg/acpi/generic.go
- pkg/acpi/raw.go
- pkg/acpi/rsdp.go
- pkg/complete/complete_test.go
- pkg/less/less.go
- pkg/recovery/recovery.go
- pkg/sortedmap/sortedmap_test.go
- pkg/strace/syscall_linux_amd64.go
- pkg/strace/tracer.go
- pkg/uio/buffer.go
- pkg/zimage/zimage.go
Signed-off-by: Urvisha Patel <patelvisha2007@gmail.com>
> Fix the misspellings

- pkg/kexec/kexec_load_linux.go
- pkg/kexec/memory_linux.go
- pkg/kexec/memory_linux_test.go
- pkg/multiboot/module.go
Let's apply some set theory. Add some tests. Voila!
> kexec: formalize memory manipulation methods.

- RELEASES
We need to do a release now, we keep missing them.
This should be a major release due to the great rename,
so we can put off the number question a little longer.
> Release notes

- Gopkg.lock
- pkg/pxe/schemes.go
- vendor/github.com/cenkalti/backoff/LICENSE
- vendor/github.com/cenkalti/backoff/backoff.go
- vendor/github.com/cenkalti/backoff/context.go
- vendor/github.com/cenkalti/backoff/exponential.go
- vendor/github.com/cenkalti/backoff/retry.go
- vendor/github.com/cenkalti/backoff/ticker.go
- vendor/github.com/cenkalti/backoff/tries.go
> pxe: Add support for retries with backoff

- pkg/gpio/gpio_linux.go
Gpio package enables setting/reading gpio pin values using the GPIO Sysfs Interface for Userspace
> Adding gpio package

- pkg/golang/build.go
Signed-off-by: Mark Pictor <mpictor@gmail.com>
> honor BuildTags in build.Context

- integration/integration.go
I want this sooner rather than later and have been copying it into so many branches... so I'm just gonna push this through now.
cc @mpictor (commit still lists you as author, I just amended the msg)
> integration: replace ESC with ~ on serial console

- integration/integration.go
> integration: clean up temp dir abstraction

- cmds/core/uptime/uptime.go
- cmds/core/uptime/uptime_test.go
I have implemented the uptime command which is used to find out how long the system has been active (running). This command returns set of values that involve, the current time, and the amount of time system is in running state, and the load time for the past 1, 5 and 15 minutes respectively.
The uptime command should also return the  number of users currently logged into the system.I am still in the process of adding this functionality.
> Implemented the uptime command

- .circleci/config.yml
- .gitignore
- tools/checklicenses/checklicenses.go
- tools/checklicenses/config.json
Signed-off-by: Andrea Barberio <insomniac@slackware.it>
> [scripts/checlicences] Generalized tool to be used in other projects

- pkg/gpio/gpio_linux.go
Instead of having to use hardcoded pin IDs with the gpio_linux package, we can compute the pin ID from the gpiochip directories (controllers)
> Get GPIO pin ID from controller 

- pkg/golang/build.go
- u-root.go
> u-root: complain if version != go1.12 or go1.13

- cmds/exp/esxiboot/README.md
- cmds/exp/esxiboot/esxiboot.go
- integration/dhclient_test.go
- pkg/esxi/esxi.go
- pkg/esxi/esxi_test.go
- pkg/esxi/testdata/empty_mods.cfg
- pkg/esxi/testdata/kernel_cmdline_mods.cfg
- pkg/esxi/testdata/no_cmdline.cfg
- pkg/esxi/testdata/no_mods.cfg
- pkg/mount/mount_linux.go
> pkg/esxi: API for booting ESXi from disks and CDROMs

- pkg/sh/run.go
> pkg/sh: provide shortcut to run command with arbitrary stdio

- RELEASES
> v6.0.0 release

- pkg/dhclient/dhclient.go
- pkg/dhclient/dhcp4.go
- pkg/dhclient/dhcp6.go
- pkg/dhclient/iscsiuri.go
- pkg/dhclient/iscsiuri_test.go
Somebody tell me how to write a proper parser. I did what I remember from writing a compiler, but that was ages ago...
> pkg/dhclient: support iSCSI URIs

- pkg/uio/progress.go
- pkg/uio/progress_test.go
> Add utility for a simple progress bar

- cmds/exp/cpu/cpu.go
Make host an argument, not a global, as it's no longer
a flag.
> clean up arg processing for client side

- cmds/core/kexec/kexec_linux.go
- integration/multiboot_test.go
- pkg/vmtest/fields.go
- pkg/vmtest/fields_test.go
- pkg/vmtest/integration.go
cc @krystian-hebel
I couldn't push to your fork's branch, so I opened this PR with the test fix and some debug improvements.
> kexec: change flag type for modules

- integration/README.md
better developer instructions to clearly let people repro the integration tests locally.
the docker container will take some more work to get right, so let's improve documentation in the meantime.
rendered: https://github.com/u-root/u-root/blob/1dea793ccf1732d78cdbb7798322dca13cf3fda8/integration/README.md
> integration: give clear repro steps

- cmds/core/dhclient/dhclient.go
- integration/dhclient_test.go
- pkg/dhclient/dhclient.go
It's possible that the user will ask for DHCP on some interfaces that won't get a link-local IPv6 address. Let's not hang forever when they do that.
> dhclient: make sure DHCPv6 client cannot hang forever

- pkg/dhclient/dhclient.go
- pkg/dhclient/dhcp4.go
- pkg/dhclient/dhcp6.go
- Move lease configure4&6 to their respective file.
- Update v6 configuration call to be consistent with v4.
> [pkg/dhclient] refactor lease configuration.

- pkg/dhclient/dhclient.go
> dhclient: typo fix.

- cmds/core/wget/wget.go
> wget: support tftp

- pkg/bb/bbmain/cmd/main.go
> Prevent possible panic in bbmain

- cmds/exp/getty/getty.go
- pkg/termios/termios.go
- pkg/termios/termios_linux.go
- pkg/termios/var.go
There are no special options and no login support
Also getty exits after starting the shell so if one exits the shell,
there is no more shell!
Signed-off-by: Julien Viard de Galbert <julien.viard-de-galbert@itrenew.com>
> getty Open a TTY and invoke a shell

- cmds/core/init/init.go
- pkg/libinit/proc_linux.go
> libinit: return cmdCount from RunCommands

- pkg/qemu/qemu.go
- pkg/rand/random_linux.go
Implement with kernel cmdline as an alternative to https://github.com/u-root/u-root/pull/1408
> kernel cmdline uroot.nohwrng to disable blocking random read

- cmds/exp/hdparm/hdparm.go
- pkg/scuzz/ata.go
- pkg/scuzz/const_amd64.go
- pkg/scuzz/control.go
- pkg/scuzz/doc.go
- pkg/scuzz/fns.go
- pkg/scuzz/sg_linux.go
- pkg/scuzz/sg_linux_test.go
If this package looks ok I can write an hdparm command which
implements a few needed functions, and fill it in over time.
> package for interfacing with the kernel sg device

- cmds/exp/hdparm/hdparm.go
Improves documentation according to #1416. Small readability fixes.
> hdparm: increase readability

- pkg/ipmi/ipmi.go
- pkg/ipmi/ipmi_linux.go
Add a way to check if the watchdog is running and to stop it.
> [pkg/ipmi] watchdog utils

- pkg/uroot/uroot.go
- pkg/uroot/uroot_test.go
- pkg/vmtest/integration.go
- u-root.go
> uroot: allow specifying custom uinit

- cmds/core/wget/wget_test.go
Impossible to debug status code without output of the binary...
> wget: improve test error message

- pkg/storage/blockdev.go
* Get the UUID of an XFS fs
* Merge duplicated code
* Return error if any
* Avoid printing on the functions
> [pkg/storage] tryXFS

- integration/multiboot_test.go
- pkg/qemu/qemu.go
should fix: https://github.com/u-root/u-root/issues/1209
Signed-off-by: Julien Viard de Galbert <julien.viard-de-galbert@itrenew.com>
> integration/multiboot: try to fix flaky test

- cmds/boot/uinit/main.go
Signed-off-by: Johnny Lin <johnny_lin@wiwynn.com>
> uinit: Stop IPMI watchdog timer before booting to OS

- cmds/boot/stboot/main.go
- pkg/bootconfig/bootconfig.go
> STBoot: Check filesize of kernel, initramfs and devicetree

- cmds/boot/stboot/main.go
- pkg/bootconfig/zipconfig.go
- tools/stconfig/commands.go
Had to close other pr, cause I messed up my repo and couldn't fix it. Sorry for the hassle.
> STConfig: Validates file presence

- pkg/bootconfig/bootconfig.go
- pkg/bootconfig/zipconfig.go
> STBoot: Overhaul of errors in bootconfig pkg

- .cirrus.yml
Could someone with the necessary access rights set this up? It's free for public repos. :)
https://github.com/marketplace/cirrus-ci/
> CI: set up Cirrus CI

- .cirrus.yml
> Cirrus CI: fix the build command where an underscore snuck in

- .cirrus.yml
- pkg/cpio/fs_unix.go
- pkg/cpio/mknod_freebsd.go
- pkg/cpio/mknod_unix.go
- pkg/cpio/sysinfo_freebsd.go
- pkg/ldd/ldso_freebsd.go
:clapper: based on #1429 and #1448 :sparkles:
> RUN BSD! Take two

- cmds/boot/stboot/main.go
- pkg/stboot/netvars.go
- pkg/stboot/network.go
- pkg/stboot/stboot.go
removed log-calls and replaced with proper error handling.
> STBOOT: moved stboot functions to pkg stboot

- cmds/exp/pxeserver/main.go
Return Server Identifier option, IP lease time, and Client Identifier
when appropriate.
See also https://github.com/insomniacslk/dhcp/pull/333
> pxeserver: be an RFC-compliant server

- pkg/uroot/uroot.go
- pkg/uroot/uroot_test.go
- u-root.go
> u-root: improve missing shell/init error messages

- pkg/boot/stboot/network.go
> Netrefac of STBoot configuration

- README.md
This new website looks nicer and supports a few more features.
> Update godoc link to pkg.go.dev

- cmds/boot/stboot/main.go
- pkg/boot/stboot/bootball.go
- tools/stconfig/commands.go
> Typofix: This bothered me a long time

- pkg/bootconfig/bootconfig_test.go
> Fixed a 'typo'

- cmds/exp/pxeserver/main.go
This seems a bit more correct and fixes it for MacOS and likely linux too.
> pxeserver: adjust the address we send dhcp replies to

- cmds/core/kexec/kexec_linux.go
- cmds/exp/esxiboot/esxiboot.go
- pkg/boot/esxi/esxi.go
- pkg/boot/esxi/esxi_test.go
- pkg/boot/multiboot.go
- pkg/boot/multiboot/description.go
- pkg/boot/multiboot/module.go
- pkg/boot/multiboot/multiboot.go
- pkg/boot/multiboot/reader.go
- pkg/bootconfig/bootconfig.go
- pkg/cpio/fs_unix.go
- pkg/curl/schemes.go
- pkg/uio/lazy.go
> Multiboot ReaderAt take 2

- cmds/core/cpio/cpio.go
- cmds/core/cpio/cpio_test.go
Fixes #1301
Signed-off-by: Ward Vandewege <ward@jhvc.com>
> cpio: handle hard links correctly.

- cmds/exp/pxeserver/main.go
DHCP packets being sent to 255.255.255.255 are being
swallowed whole. In a lot of ways, 255.255.255.255 is
a very odd place to send: it technically matches all
interfaces, but we're sending on one interface.
My brain seems to recall that you can send a broadcast
packet on a subnet, given the subnet address, but you
can't send to the broadcast address. But that's probably
just a Total Recall.
This fixes the packet swallowing problem and the Atomic
Pi can once again be booted from pxeserver running on OSX.
> OSX/pxeserver: Change response for DHCP to match subnet

- cmds/core/cpio/cpio_test.go
> cpio: put test file in temp dir

- cmds/boot/systemboot/main.go
- cmds/exp/dmidecode/dmidecode.go
- pkg/smbios/README.md
- pkg/smbios/entry64.go
- pkg/smbios/info.go
- pkg/smbios/info_linux.go
- pkg/smbios/table_type.go
- pkg/smbios/type0_bios_information.go
- pkg/smbios/type17_memory_device.go
- pkg/smbios/type1_system_information.go
- pkg/smbios/type2_baseboard_information.go
- pkg/smbios/type38_ipmi_device_information.go
- pkg/smbios/type3_chassis_information.go
- pkg/smbios/type43_tpm_device.go
- pkg/smbios/type4_processor_information.go
- pkg/smbios/type7_cache_information.go
Readability stuff. Convenience. Package comments.
> Some small SMBIOS enhancements

- cmds/exp/ipmidump/ipmidump.go
- pkg/ipmi/ipmi.go
Print IPMI LAN config of IP information.
Send IPMI raw command and print response.
Signed-off-by: Jingle Hsu <jingle_hsu@wiwynn.com>
> cmds/ipmidump: Add arguments for LAN config and raw command

- pkg/tss/capabilities.go
- pkg/tss/constants.go
- pkg/tss/pcr.go
- pkg/tss/structures.go
- pkg/tss/tpm_linux.go
- pkg/tss/tss.go
> TPM-TSS-Refactor: fixed comments.

- pkg/termios/termios_test.go
> Fix termios test

- cmds/core/msr/msr.go
- pkg/msr/msr_linux.go
> Move msr functions into a package

- pkg/boot/linux.go
> boot: fix Linux label

- cmds/exp/pox/pox.go
- cmds/exp/pox/pox_test.go
> pox: make test work, error if neither -c or -r is set

- cmds/core/lockmsrs/lockmsrs.go
- pkg/msr/msr_linux.go
The msr package was erroring in an init due to my mistake. Removed the
init and just added a helper function for all CPUs.
Sorry about that! can you try this out and see if its better?
> Fix msr package

- pkg/msr/msr_linux.go
- pkg/msr/msr_linux_test.go
- pkg/testutil/testutil.go
> MSR package fixes

- pkg/qemu/devices.go
- pkg/qemu/qemu.go
> qemu: add PCAP capturing

- cmds/exp/pxeserver/main.go
DHCPv6: MaxUint32 * nanoseconds is... 4 seconds of lease time. That is too short! This used to be correct, but the type changed from uint32 to time.Duration and I forgot to update this user.
DHCPv6: use new getters.
DHCPv6: add bootfileurl.
> pxeserver: fix misc issues

- pkg/msr/intel.go
Fix a fat-finger error in msr values
> Fix typo in msr values

- cmds/boot/systemboot/main.go
- cmds/boot/systemboot/systemboot_linux.go
- pkg/ipmi/ioctl_unix.go
- pkg/ipmi/ipmi.go
- pkg/ipmi/oem.go
@pmazzini @dhendrix @jonzhang-fb @morganjangwiwynn @JingleHsuWiwynn
> Implement OEM IPMI CMOS clear command

- pkg/boot/acpi/rsdp.go
> Also search through EBDA for RSDP

- pkg/ulog/klog_linux.go
> pkg/ulog: fix KernelLog Reinit()

- cmds/boot/boot2/boot.go
most people don't find stack barf from main all that useful.
Don't panic, just Fatal.
> boot2: don't panic. Just Fatal.

- pkg/msr/msr_linux.go
- pkg/msr/msr_linux_test.go
> msr: Add String function for CPUs

- cmds/core/ts/ts.go
- pkg/ts/ts.go
> ts: Add option to print timestamp relative to the previous line

- cmds/core/dhclient/dhclient.go
> dhclient: add dry run mode that doesn't try to configure anything

- pkg/tss/capabilities.go
- pkg/tss/nvram.go
- pkg/tss/tss.go
> TSS: Add some more functionality to tss layer

- cmds/exp/pxeserver/main.go
> pxeserver: allow specifying HTTP and TFTP ports

- cmds/exp/pox/pox.go
Update pox to use the uzip package for zip instead of finding zip in the
PATH.
> Update pox to use uzip

- cmds/exp/pogosh/pogosh.go
- pkg/pogosh/arithmetic.go
- pkg/pogosh/arithmetic_test.go
- pkg/pogosh/ast.go
- pkg/pogosh/builtins.go
- pkg/pogosh/exec.go
- pkg/pogosh/lexer.go
- pkg/pogosh/lexer_test.go
- pkg/pogosh/parser.go
- pkg/pogosh/shell.go
- pkg/pogosh/shell_test.go
- pkg/pogosh/state.go
This is a posix-compatible shell written in Go which is 20% implemented.
Import from: https://bitbucket.org/rjoleary/pogosh/
Signed-off-by: Ryan O'Leary <ryan@ryanoleary.ca>
> Import pogosh into u-root experimental

- pkg/dhclient/dhcp4.go
- pkg/dhclient/dhcp4_test.go
Doesn't really hurt. v4 spec says it must be in root path, but DHCPv6
similarly reuses the boot file URL field for this. So let's allow both.
> dhcp4: allow iSCSI URL in bootfilename field

- .circleci/config.yml
- .circleci/images/test-image-amd64/Dockerfile
- .circleci/images/test-image-arm/Dockerfile
- README.md
- azure-pipelines.yml
- cmds/core/date/date.go
- cmds/core/mkfifo/mkfifo.go
- cmds/core/readlink/readlink.go
- docs/index.html
- docs/index.md
- u-root.go
- uroot_test.go
The Unwrap() is compelling and is used in another PR.
> Move to Go 1.13

- Gopkg.lock
- Gopkg.toml
- vendor/pack.ag/tftp/client.go
- vendor/pack.ag/tftp/conn.go
> vendor: tftp from master (IPv6 support for TFTP)

- pkg/boot/grub/entry.go
- pkg/boot/grub/entry_test.go
env files are a general grub concept.
> grub: move gboot/entry into GRUB

- pkg/boot/syslinux/syslinux.go
- pkg/boot/syslinux/syslinux_test.go
Makes the test setup a bit more readable. Adds tests for some corner cases. Fixes a bug for when no working directory is specified.
> pkg/syslinux: simpler test configuration, more tests

- cmds/core/elvish/edit/location/location.go
- cmds/core/elvish/store/dir.go
- cmds/core/elvish/store/storedefs/storedefs.go
- integration/gotests/gotest_test.go
> bare minimum: remove blacklist from the terms we use

- pkg/mount/mount_linux_test.go
- pkg/scuzz/ata.go
- pkg/scuzz/ata_test.go
- pkg/scuzz/control.go
- pkg/scuzz/sg_linux.go
- pkg/storage/blockdev.go
This never worked... most likely due to the ioctl error, at least, where p.cmd was passed instead of the SG_IO ioctl req.
Added a QEMU Test for the Identify command.
> scuzz: make some fixes

- Gopkg.lock
- pkg/tss/capabilities.go
- pkg/tss/constants.go
- pkg/tss/nvram.go
- pkg/tss/structures.go
- pkg/tss/tss.go
- vendor/github.com/google/go-tpm/tpm/commands.go
- vendor/github.com/google/go-tpm/tpm/tpm.go
-dependency update
-nvread12 reads with noAuth/OwnerAuth/BlobAuth and calls the correct function from go-tpm
> TSS: nvRead12 expansion

- pkg/boot/bls/testdata/fedora_32.json
- pkg/boot/bls/testdata/fedora_32/loader/entries/de8380606ce44a2dabad127eb049acbe-0-rescue.conf
- pkg/boot/bls/testdata/fedora_32/loader/entries/de8380606ce44a2dabad127eb049acbe-5.6.6-300.fc32.x86_64.conf
> bls: rename dirs with - and . to use _ instead

- Gopkg.lock
- cmds/core/sluinit/uinit.go
- pkg/dhclient/dhcp4.go
- pkg/dhclient/dhcp6.go
- pkg/dhclient/iscsiuri.go
- pkg/dhclient/iscsiuri_test.go
- vendor/github.com/u-root/iscsinl/LICENSE
- vendor/github.com/u-root/iscsinl/initiator.go
- vendor/github.com/u-root/iscsinl/netlink.go
sluinit now has support to scan iscsi disks via dhclient parser and mount these disks via iscsinl library.
> securelaunch: iscsi support

- cmds/core/sluinit/uinit.go
@sipasing I couldn't push to TrenchBoot/u-root before merging, so here's my follow-up.
> sluinit: simplify iscsi netroot parsing

- cmds/boot/boot/boot.go
- pkg/boot/localboot/localboot.go
> Fixup flags

- README.md
Signed-off-by: Sergei Semenchuk <binjip978@gmail.com>
> rename -initramfs to -initrd in README examples

- pkg/boot/localboot/localboot.go
> localboot: re-enable GRUB, syslinux, BLS parsing

- cmds/boot/stboot/data.go
- cmds/boot/stboot/hostvars.go
- cmds/boot/stboot/main.go
- cmds/boot/stboot/network.go
Wait for non loopback devices to appear.
On real hardware this takes about 3 seconds after stboot has started.
Improve error message while on it.
> Stboot wait for harddisks

- cmds/boot/systemboot/main.go
- pkg/ipmi/ocp/ocp.go
- pkg/ipmi/odm/ocp.go
Signed-off-by: Tim Chu <Tim.Chu@quantatw.com>
> Rename pkg/ipmi/wiwynn to pkg/ipmi/odm

- cmds/exp/disk_unlock/disk_unlock.go
> Add flag.Parse() to disk_unlock

- pkg/boot/syslinux/syslinux.go
- pkg/boot/syslinux/syslinux_test.go
> syslinux: add multi-initrd support

- cmds/core/ping/ping.go
> ping: fix off by one error

- pkg/crypto/measure.go
- pkg/securelaunch/tpm/tpm.go
- pkg/tss/constants.go
- pkg/tss/pcr.go
- pkg/tss/tss.go
> pkg/tss: fix hash for TPM2.0

- cmds/core/io/cmos.go
- cmds/core/io/io.go
- cmds/core/io/io_linux.go
- cmds/core/io/ports.go
- pkg/memio/mmap.go
- pkg/memio/path_linux.go
- pkg/memio/ports_linux.go
- pkg/memio/ports_plan9.go
- pkg/memio/seek.go
- pkg/memio/seek_linux.go
- templates.go
We get both io and cmos querying commands.
> Port the io command to plan9

- pkg/sh/run.go
> sh: use io rather than os.File

- cmds/core/sshd/const_plan9.go
- cmds/core/sshd/const_unix.go
- cmds/core/sshd/sshd.go
The shell in Plan 9 is called rc.
> sshd: adjust for Plan 9 shell, called /bin/rc

- pkg/boot/grub/grub.go
> grub: Recognize hex escape sequences

- pkg/boot/menu/menu.go
Signed-off-by: Ryan O'Leary <ryan@ryanoleary.ca>
> menu: Change 'NERF Boot Menu' to 'LinuxBoot Menu'

- cmds/core/blkid/blkid.go
- templates.go
> Add blkid command

- pkg/dt/fdt.go
- pkg/dt/fdt_test.go
- pkg/dt/node.go
- pkg/dt/print.go
These functions are needed to enable kexec'ing a
Flattened Image Tree.
Signed-off-by: Ronald G Minnich <rminnich@gmail.com>
> fdt: add utility functions

- u-root.go
Signed-off-by: Ryan O'Leary <ryan@ryanoleary.ca>
> Add Go 1.15 to supported list

- cmds/core/init/init_linux.go
- pkg/libinit/root_linux.go
Moving the installModules to the libinit pkg so it can be called from
multiple places. Also updating it so that there is the option to install
individual modules by name.
> Move installModules to pkg/libinit

- cmds/core/ip/ip.go
> ip: add a route delete command

- cmds/core/installcommand/installcommand.go
- cmds/core/installcommand/installcommand_plan9.go
- templates.go
There is more to do but it at least gets an error when it runs.
> installcommand: make it build on plan 9

- pkg/boot/bootcmd/bootcmd.go
> Check mountPool isnt nil before unmounting

- docs/index.html
- docs/index.md
> docs: link to Mirtchovski's memorial page

- .circleci/config.yml
Signed-off-by: Medicine Yeh <medicinehy@gmail.com>
> circleci: Integrate go code coverage reports with codecov

- docs/index.html
- docs/index.md
> Change back link to andrey's github repo

- cmds/exp/dumpebda/main.go
> dumpebda: Add command

- cmds/core/ls/ls.go
- cmds/core/ls/ls_test.go
Signed-off-by: binjip978 <binjip978@gmail.com>
> ls: add -F flag to classify files

- cmds/core/ls/ls.go
- cmds/core/ls/ls_test.go
Add support for '-d' flag - list directories but not their contents.  Also add tests for this new flag.
> ls: add support for '-d' flag - list directories but not their contents

- cmds/exp/smbios_transfer/smbios_transfer.go
- pkg/ipmi/blobs/blob_transfer.go
Signed-off-by: Jie Yang <jjy@google.com>
> Add a command that transfers SMBIOS tables to BMC

- cmds/core/date/date.go
> Fix typo in midification

- pkg/termios/sgtty_darwin.go
- pkg/termios/termios_darwin.go
- pkg/termios/var_darwin.go
- pkg/termios/var_linux.go
- pkg/termios/var_unix.go
> pkg/termios: add darwin support

- pkg/boot/netboot/ipxe/ipxe.go
- pkg/boot/netboot/ipxe/ipxe_test.go
A standard ipxe script can have one or multiple initrd=... lines, and now u-root can support that too. After the change, both the following ipxe formats are supported (and cause identical boot behavior):
_...
initrd=file.001,file.002
boot
- or -
...
initrd=file.001
initrd=file.002
boot_
Signed-off-by: Robi Buranyi <rburanyi@google.com>
> boot: support multiple initrd lines in ipxe

- cmds/exp/cbmem/cbmem_linux_test.go
> cmds/exp/cbmem: fix broken test

- cmds/boot/pxeboot/pxeboot.go
> Add option to skip DHCP in pxeboot and just specify a remote file

- u-root.go
> Remove go1.16 warning

- README.md
> Add README warning for depending on non-uroot cmds

- .circleci/images/test-image-amd64/Dockerfile
- .circleci/images/test-image-arm/Dockerfile
- .circleci/images/test-image-arm64/Dockerfile
> Update Dockerfiles to go1.15

- .circleci/images/test-image-amd64/Dockerfile
- cmds/exp/uefiboot/README.md
move uefipayload from my personal account to linuxboot.
> change uefipayload to linuxboot fork

- pkg/dhclient/dhcp4.go
Signed-off-by: Colin Mitchell colinmitchell@google.com
> Allow changing the default scheme for dhcpv4

- u-root.go
> Add support for specifying build tags

- cmds/core/wget/wget.go
> Check error return of wget Close method

- README.md
> Update minimum Go version

- README.md
This caused trouble for someone today, as they followed the instructions
in the order shown.
> Fix the warning on modules

- cmds/core/backoff/main.go
- cmds/core/backoff/main_test.go
- cmds/core/backoff/run.go
> Improve cmd/core/backoff test coverage

- pkg/boot/bzimage/bzimage.go
Support more decompression types.
> pkg/bzimage: add more types

- pkg/pci/pci.go
- pkg/pci/pci_linux.go
> pci: The irq can be larger than 8 bits

- cmds/core/ping/ping.go
> Update usage of ping command

- pkg/boot/fit/vfit.go
> fit/vfit: add a missing function comment

- cmds/core/dd/dd.go
- cmds/core/dd/dd_test.go
- pkg/progress/progress.go
- pkg/progress/progress_test.go
This commits refactors a majority of the code within cmds/core/dd in
order to make it testable. Additionally it moves part of the code into
it's own package (pkg/progress) and adds tests for this package, and the
cmd itself.
Signed-off-by: Christian Walter <christian.walter@9elements.com>
> cmds/core/dd: Refactor code, add tests and push code into pkg/progress

- cmds/contrib/spidev/dit.sh
> Remove dit.sh

- cmds/core/dd/dd_test.go
writing test file to "current" directory can lead
to indeterministic test run results in places.
> cmd/core/dd: fix dd_test to write data file to tmp

- cmds/exp/bzimage/bzimage_test.go
Something about time formatting changed. Zowie.
> bzimage: re enable testing

- .circleci/config.yml
- .github/workflows/go.yml
> Move linters from circleci to actions

- .circleci/config.yml
- integration/testcmd/gotest/uinit/gotest.go
- pkg/vmtest/gotest.go
This pull request is a rebase of https://github.com/u-root/u-root/pull/1958 and reopened here because of CI reasons
> Add coverage reporting from VM tests

- go.mod
- go.sum
- vendor/github.com/insomniacslk/dhcp/dhcpv4/client4/client.go
- vendor/github.com/insomniacslk/dhcp/dhcpv4/dhcpv4.go
- vendor/github.com/insomniacslk/dhcp/dhcpv4/option_relay_agent_information.go
- vendor/github.com/insomniacslk/dhcp/dhcpv4/option_vivc.go
- vendor/github.com/insomniacslk/dhcp/dhcpv6/dhcpv6.go
- vendor/github.com/insomniacslk/dhcp/dhcpv6/dhcpv6message.go
- vendor/github.com/insomniacslk/dhcp/dhcpv6/modifiers.go
- vendor/github.com/insomniacslk/dhcp/dhcpv6/option_relayport.go
- vendor/github.com/insomniacslk/dhcp/dhcpv6/options.go
- vendor/github.com/insomniacslk/dhcp/iana/entid.go
- vendor/modules.txt
This contains some bug fixes for dhcp.
> Import latest dhcp module

- cmds/core/base64/base64.go
- cmds/core/base64/base64_test.go
> base64 command

- pkg/uroot/builder/bb_test.go
> pkg/uroot/builder/bb_test.go: Only run if GO111MODULE=off

- go.mod
- go.sum
- pkg/uroot/builder/bb.go
- pkg/uroot/builder/binary.go
- pkg/uroot/builder/builder.go
- pkg/uroot/builder/gbb.go
- pkg/uroot/builder/gbb_test.go
- pkg/uroot/uroot.go
- u-root.go
- vendor/github.com/u-root/gobusybox/src/pkg/bb/bb.go
- vendor/modules.txt
See commit messages for what's up.
> Various fixes to gobusybox builds in u-root

- .github/workflows/auto-assign.yml
- MAINTAINERS
> Add basic MAINTAINERS file

- pkg/strace/epsocket.go
- pkg/strace/print.go
- pkg/strace/syscall_linux.go
- pkg/strace/syscalls.go
- pkg/strace/syscalls_test.go
- pkg/strace/tracer.go
> Add ByName and ByNumber functions, to get system call numbers and names

- cmds/core/echo/echo.go
- cmds/core/echo/echo_test.go
Refactored the echo pkg to make it testable and then added reworked the tests in echo_test.go.
> echo.go & echo_test.go: Refactored echo pkg and added tests.

- cmds/core/blkid/blkid_linux.go
- cmds/core/blkid/blkid_test.go
Signed-off-by: Christian Walter <christian.walter@9elements.com>
> cmds/core/blkid: Add unit tests

- CONTRIBUTING.md
> CONTRIBUTION.md: Add details about vmtest side effects.

- cmds/core/wc/testfiles/file1
- cmds/core/wc/wc.go
- cmds/core/wc/wc_test.go
Refactored wc.go and wc_test.go.
> Cover/cmds/core/wc: Add tests.

- cmds/core/uniq/testfiles/file1
- cmds/core/uniq/testfiles/file2
- cmds/core/uniq/uniq.go
- cmds/core/uniq/uniq_test.go
Refactored uniq.go and uniq_test.go.
> Cover/cmds/core/uniq: Add tests.

- cmds/core/comm/comm.go
- cmds/core/comm/comm_test.go
Refactored comm.go and added tests in comm_test.go.
> Cover/cmds/core/comm: Add tests.

- cmds/core/strings/strings.go
- cmds/core/strings/strings_test.go
Refactored strings.go and tests in strings_tests.go.
> Cover/cmds/core/strings: Add tests.

- cmds/core/sort/sort.go
- cmds/core/sort/sort_test.go
Refactored sort.go and tests in sort_test.go.
> Cover/cmds/core/sort: Add tests.

- cmds/core/cmp/cmp.go
- cmds/core/cmp/cmp_test.go
Refactored cmp.go and added tests to cmp_test.go.
> Cover/cmds/core/cmp: Add tests.

- cmds/core/chmod/chmod.go
- cmds/core/chmod/chmod_test.go
Refactored chmod.go and tests in chmod_test.go.
> Cover/cmds/core/chmod: Add tests.

- cmds/core/md5sum/md5sum.go
- cmds/core/md5sum/md5sum_test.go
Refactored md5sum.go and tests in md5sum_test.go.
> Cover/cmds/core/md5sum: Add tests.

- cmds/core/chroot/chroot.go
- cmds/core/chroot/chroot_test.go
Refactored chroot.go and chroot_test.go and added some tests.
> Cover/cmds/core/chroot: Add tests.

- cmds/exp/cbmem/cbmem_linux_test.go
- cmds/exp/cbmem/main_linux.go
- cmds/exp/cbmem/timestamps.go
- cmds/exp/cbmem/timestamps_test.go
Added more tests for coverage.
Signed-off-by: llogen <christoph.lange@9elements.com>
> Cover/cmds/exp/cbmem: Add tests.

- cmds/exp/ed/address_test.go
- cmds/exp/ed/filebuffer_test.go
Added tests for filebuffer.go and address.go.
Signed-off-by: llogen <christoph.lange@9elements.com>
> Cover/cmds/exp/ed: Add tests. Part 1

- cmds/exp/ed/commands.go
- cmds/exp/ed/ed.go
- cmds/exp/ed/ed_test.go
- integration/gotests/gotest_test.go
* Rework for testability
* Add tests for command execution, excluding input mode commands
> Cover/cmds/exp/ed: Add tests. Part 2

- cmds/core/shasum/shasum.go
- cmds/core/shasum/shasum_test.go
Refactored shasum.go and added tests in shasum_test.go.
Signed-off-by: llogen <christoph.lange@9elements.com>
> Cover/cmds/core/shasum: Add tests.

- cmds/core/shutdown/shutdown_linux.go
- cmds/core/shutdown/shutdown_test.go
Added tests for shutdown.go in shutdown_test.go.
> Cover/cmds/core/shutdown: Add tests.

- cmds/core/backoff/main_test.go
- cmds/core/backoff/run.go
* Add test for reworked backoff command
> cmds/core/backoff:

- README.md
Signed-off-by: Nobuhiro MIKI <nob@bobuhiro11.net>
> docs: fix broken link to vmlinuz

- cmds/core/grep/grep.go
- cmds/core/grep/grep_linux.go
- cmds/core/grep/grep_plan9.go
> Tweak grep so the -q flag becomes -s on Plan 9.

- .circleci/config.yml
- .circleci/images/builduploadall.sh
- .circleci/images/test-image-amd64/Dockerfile
- .circleci/images/test-image-arm/Dockerfile
- .circleci/images/test-image-arm64/Dockerfile
(bump up major version to reflect major upgrade to qemu)
> Migrate integration test qemu version to 7.0.0

- pkg/boot/kexec/doc.go
- pkg/boot/kexec/kexec_fileload_other_linux.go
- pkg/boot/kexec/memory_linux.go
- pkg/boot/linux/load_linux_amd64.go
- pkg/boot/linux/load_other_linux.go
- pkg/boot/purgatory/asm.go
- pkg/boot/zbi/zbi.go
- pkg/dt/fdt_test.go
- pkg/dt/node.go
- pkg/syscallfilter/doc.go
- pkg/syscallfilter/syscallfilter_linux.go
- pkg/uefivars/boot/boot.go
- pkg/uroot/builder/builder.go
> Aesthetics fixups

- cmds/core/kexec/kexec_linux.go
- pkg/boot/initrd.go
- pkg/boot/initrd_test.go
Signed-off-by: Andrew <andrewsun@google.com>
> Add helper function to create initrd

- cmds/core/date/date_plan9.go
- go.mod
- go.sum
- vendor/github.com/u-root/gobusybox/src/pkg/bb/findpkg/bb.go
- vendor/modules.txt
This includes the new code that will fail on a build error
(i.e. a good thing)
> Update go busybox

- RELEASES
> Create v0.9.0 release notes

- go.mod
- go.sum
- vendor/github.com/cenkalti/backoff/v4/.gitignore
- vendor/github.com/cenkalti/backoff/v4/.travis.yml
- vendor/github.com/cenkalti/backoff/v4/README.md
- vendor/github.com/cenkalti/backoff/v4/context.go
- vendor/github.com/cenkalti/backoff/v4/exponential.go
- vendor/github.com/cenkalti/backoff/v4/retry.go
- vendor/modules.txt
> modules: add updated cenkalti/backoff to vendor/

- cmds/core/kexec/kexec_linux.go
- pkg/boot/linux.go
- pkg/boot/linux/opts.go
- pkg/boot/linux_test.go
- pkg/boot/syslinux/syslinux.go
- pkg/boot/syslinux/syslinux_test.go
- pkg/dt/fdt_linux.go
- pkg/dt/fdt_test.go
> boot: remove duplicate device tree field

- pkg/logutil/logutil.go
- pkg/logutil/logutil_test.go
TeeOutput will setup a log file read from UROOT_LOG_PATH and tee output
into the file.
Signed-off-by: Andrew <andrewsun@google.com>
> Add TeeOutput function to logutil

- pkg/boot/linux_test.go
Small change to create all files in tempdir.
Signed-off-by: Andrew <andrewsun@google.com>
> Small fix for linux_test.go

- cmds/core/wget/wget_test.go
The unused port was closed before acquiring the server port.
Thus, the unused port may be the same as server port and fail the test.
Signed-off-by: Medicine Yeh <medicinehy@gmail.com>
> cmds/core/wget: Fix unit test unused port

- README.md
> add codeql badge

- cmds/core/base64/base64.go
- cmds/core/base64/base64_test.go
> based64: fix a bug and make it more testable

- cmds/core/id/id_test.go
This commit removes the dependency of using testutil and run command. This is a follow up commit of 86a86bb.
Signed-off-by: Medicine Yeh <medicinehy@gmail.com>
> cmds/core/id: modify to make it more testable, followed up

- cmds/core/df/dev.go
- cmds/core/df/dev_uint32.go
- cmds/core/df/df.go
- cmds/core/df/df_test.go
Signed-off-by: Siarhiej Siemianchuk <pdp.eleven11@gmail.com>
> df: add support for passing file arguments

- pkg/boot/bzimage/bzimage.go
Whole-file CRC checking cannot work with signed images (See https://github.com/u-root/u-root/issues/2513).
The whole-file CRC check is also redundant because the image has it's own CRC32 checksum at the end, and signed images have a signature as well.
This change does not solve the problem with loading signed kernels, it only fixes half of the problem. Future pull requests will be needed to support signed kernels.
Signed-off-by: Avi Brender <avibrender@gmail.com>
> [bzImage] Remove whole-file CRC checking.

- pkg/dhclient/dhclient.go
Allow caller to substitute their own port for sending DHCPv6 requests from, defaulting to the normal port (546).
Signed-off-by: Conrad Parker <conradparker@google.com>
> pkg/dhclient: Allow custom client v6 port

- cmds/core/shasum/shasum.go
- cmds/core/shasum/shasum_test.go
Signed-off-by: Siarhiej Siemianchuk <pdp.eleven11@gmail.com>
> cmds/core/shasum: work with multiple files

- cmds/core/uniq/testfiles/file2
- cmds/core/uniq/uniq.go
- cmds/core/uniq/uniq_test.go
gofmt and typo fix
Signed-off-by: Siarhiej Siemianchuk <pdp.eleven11@gmail.com>
> cmds/core/uniq: add ignore case flag

- pkg/efivarfs/fs_test.go
f12209a invoked restore to fix a tmpdir removal problem. However, restore returns the file to an immutable state, not a mutable one. As such, the file was left in an immutable (and hence unremovable) state at the end of the test.
The previous code was likely passing tests because the erroneous code was being skipped when the immutable flag couldn't be set on the test file. I've tested my changes as root and confirmed that they work and do not skip any parts of this test.
The following changes are made to fs_test.go:
* Remove the restore == nil check, since makeMutable only returns nil restore on error
* To properly test makeMutable:
* Set the file's immutable bit before calling makeMutable
* Observe that the file's immutable bit is now unset
* End the test without calling restore to …
> efivarfs: Fix fs_test.go to end with mutable file

- cmds/core/tail/tail.go
- cmds/core/tail/tail_test.go
don't skip additional new line if new lines appeared in sequence
Signed-off-by: Siarhiej Siemianczuk <pdp.eleven11@gmail.com>
> cmds/core/tail: fix issue with multiple new lines

- cmds/core/readlink/readlink.go
- cmds/core/readlink/readlink_test.go
Signed-off-by: Siarhiej Siemianczuk <pdp.eleven11@gmail.com>
> cmds/core/readlink: remove testutil

- cmds/boot/fbnetboot/main.go
Signed-off-by: Avi <avibrender@gmail.com>
> [fbnetboot] Change type assertion to errors.As

- pkg/dt/fdt.go
- pkg/dt/fdt_linux.go
- pkg/dt/fdt_test.go
The New takes a variadic of FDTReader functions.
The Linux code now supplies 2 kinds: one for
io.ReaderAt and another for filenames.
The tests now use these. No more racing with changes to a package-level variable.
> pkg/dt: create idiomatic New(), minimize Linux special-ness

- pkg/boot/netboot/ipxe/fuzz_test.go
- pkg/boot/netboot/ipxe/ipxe_test.go
Signed-off-by: AdamKorcz <adam@adalogics.com>
> ipxe: move fuzzer to separate file

- pkg/libinit/root_linux.go
Function Create() and types like Mount, Dir, Creator are useful if users want to create their own root fs instead of using CreateRootfs(), which has little flexibility.
Signed-off-by: Changyuan Lyu <changyuanl@google.com>
> libinit: Export types and functions

- pkg/mount/loop/losetup_linux.go
Use the IoctlRetInt function and the LOOP_* constants defined in the golang.org/x/sys/unix package instead of locally duplicating them.
> mount/loop: use IoctlRetInt and constants from golang.org/x/sys/unix

- go.mod
- go.sum
- u-root.go
- uroot_test.go
- vendor/github.com/hashicorp/errwrap/LICENSE
- vendor/github.com/hashicorp/errwrap/README.md
- vendor/github.com/hashicorp/errwrap/errwrap.go
- vendor/github.com/hashicorp/go-multierror/LICENSE
- vendor/github.com/hashicorp/go-multierror/Makefile
- vendor/github.com/hashicorp/go-multierror/README.md
- vendor/github.com/hashicorp/go-multierror/append.go
- vendor/github.com/hashicorp/go-multierror/flatten.go
- vendor/github.com/hashicorp/go-multierror/format.go
- vendor/github.com/hashicorp/go-multierror/group.go
- vendor/github.com/hashicorp/go-multierror/multierror.go
- vendor/github.com/hashicorp/go-multierror/prefix.go
- vendor/github.com/hashicorp/go-multierror/sort.go
- vendor/github.com/u-root/gobusybox/src/pkg/bb/bb.go
- vendor/github.com/u-root/gobusybox/src/pkg/bb/bbinternal/bb.go
- vendor/github.com/u-root/gobusybox/src/pkg/bb/findpkg/BUILD.bazel
- vendor/github.com/u-root/gobusybox/src/pkg/bb/findpkg/bb.go
- vendor/modules.txt
Making #2583 by breaking out some stuff. Want to merge this before #2583.
> Small independent fixes of #2583

- pkg/uroot/builder/binary_test.go
> binary builder: basic test

- pkg/vfile/vfile.go
- pkg/vfile/vfile_test.go
Use case: some boot processes verify their next stage of boot before the
time has been set verifiably. Verification needs to work despite
unreliable time in these cases; e.g. when the system time is 1970 and
the "creation" time of the signature is technically in the future.
This use case was unintentionally broken when https://github.com/u-root/u-root/commit/61dfd7c430390cf2b56cf43cc0c64a671903ab96 was merged in December. protonmail's openpgp implementation introduced expiration time & creation time checking.
> vfile: add ability to ignore time conflicts

- pkg/ipmi/blobs/blob_transfer.go
This change resolves https://github.com/u-root/u-root/issues/2622 and cleans up the implementation of the IPMI blob protocol somewhat, by replacing casts between []byte and string with a helper type that ensures that the IPMI endpoint always sees the NUL-terminated blob ID, but the caller receives (and may provide) regular string representations.
To preserve backward-compatibility, the caller may still provide a NUL-terminated string.
Fixes #2622
> replace raw casts with a helper type for blob IDs

- u-root.go
- uroot_test.go
There are errors which have confusing diagnostics.
A typical one is this
u-root -files `which ethtool` -files `which bash` all
if ethtool is not installed, this expands to
u-root -files -files `which bash` all
and a warning that is very confusing:
Skipping /usr/bin/bash because it is not a directory
This is not even remotely related to the problem.
Still worse, this command will create a badly broken initrd!
This problem has been known to hold up interns for weeks at a time :-)
Add checkArgs, which looks for common problems in os.Args, and is easily expanded. Add a test.
> u-root command: add checkArgs function

- pkg/gzip/file.go
- pkg/gzip/file_test.go
- pkg/gzip/gunzip_test.go
- pkg/gzip/options_test.go
- templates.go
updating gzip as part of tinygo updating, and because it needed some cleanup. There is more to do, of course. I just want to see what the tools think of the coverage (beside it being worse)
> Tinygoupdate

- cmds/core/wc/testfiles/file1
- cmds/core/wc/wc.go
- cmds/core/wc/wc_test.go
remove globals flags from run function
rewrite test with tempDir
seperate stdin tests from file tests
> cmds/core/wc: fix bug with early quit if file is not exists

- cmds/core/wget/wget.go
- cmds/core/wget/wget_test.go
gnubin wget allows args after URL.
> cmds/core/wget: allow args after URL

- README.md
> README: fix reference to bb docs, add note on templates

- README.md
> README: use internal references in description, dedup notes on embedding initramfs

- u-root.go
hi
this typo was really really bothering me
> fix typo in help flags

- cmds/core/grep/grep.go
- cmds/core/grep/grep_linux.go
- cmds/core/grep/grep_plan9.go
- cmds/core/grep/grep_test.go
> grep improvements

- go.mod
- go.sum
- vendor/github.com/containerd/console/README.md
- vendor/github.com/containerd/console/console.go
- vendor/github.com/containerd/console/console_other.go
- vendor/github.com/containerd/console/console_windows.go
- vendor/github.com/containerd/console/tc_unix.go
- vendor/modules.txt
Minor fix to enable proper rawmode setup was pushed to containerd/console. Updating dependency to incorporate the change.
> Update containerd/console version

- cmds/core/gosh/completer.go
- cmds/core/gosh/completer_nobuild.go
- cmds/core/gosh/gosh.go
- cmds/core/gosh/gosh_test.go
Reduce compressed build size by up to 300k
Updates #2376
> gosh: make tab complete optional at build

- .circleci/config.yml
- .circleci/images/builduploadall.sh
- .circleci/images/test-image-arm/Dockerfile
- .circleci/images/test-image-tamago/Dockerfile
- update version to 4.5.0
- move tamago to 1.20.6
- change arm to use python3, python is gone
> update test images

- cmds/core/netcat/netcat_test.go
current test may fail if net.Dial will run when net.Listen is not ready yet
> cmds/core/netcat: fix connection refused error in test

- cmds/core/mv/mv.go
- cmds/core/mv/mv_test.go
add test helper, remove dependency on test ordering
> cmds/core/mv: remove globals flags

- cmds/core/uname/uname.go
- cmds/core/uname/uname_test.go
domain is not avaliable on unix'es and man uname
on linux don't know about it either
> cmds/core/uname: add tests, remove domain flag

- pkg/cpio/utils.go
cpio/utils: use path, not filepath, for archives
cpio is a Unix standard, the separator has to be /.
Absolute paths are prefixed with / in cpio archives,
not strings like C:/ as in Windows.
Paths must be cleaned with /, not \.
Lessons learned the hard way when poring the cpu client
to Windows.
Before this change, the cpio test would not pass on windows.
With this change, it passes on darwin, linux, and windows.
> cpio/utils: use path, not filepath, on archives

- cmds/exp/disk_unlock/disk_unlock.go
- cmds/exp/nvme_unlock/nvme_unlock.go
- pkg/hsskey/filereader.go
- pkg/hsskey/filereader_test.go
- pkg/hsskey/hsskey.go
Add reading HSS from arbitrary files & allow HSS from multiple sources
Expose HSS filereader functions for reading/writing files
For files, allow more lax conditions on number of HSS required
> Add reading HSS from arbitrary files

- cmds/core/cat/cat.go
- cmds/core/cat/cat_test.go
io errors tested with testing.iotest ErrReader
> cmds/core/cat: make files variadic and io tests

- cmds/core/xargs/xargs.go
- cmds/core/xargs/xargs_test.go
trace enable printing each command to stderr
> cmds/core/xargs: add trace flag

- README.md
But, note, we do have some work to do.
> Add our OpenSSF score

- pkg/boot/kexec/memory_linux.go
a tiny contribution for a very humble New Year's resolution
> pkg/boot/kexec: fix typo in Godoc comment

- cmds/core/chmod/chmod.go
- cmds/core/chmod/chmod_test.go
if any file is not exists or some other error chmod will return and not process other files in args. Add stderr to print all the errors and remove mode as return value.
> cmds/core/chmod: fix issue with multiple files

- cmds/exp/syscallfilter/main_linux.go
- pkg/syscallfilter/syscallfilter_linux.go
- pkg/syscallfilter/syscallfilter_linux_test.go
support the same build tags as strace package
> cmds/exp/syscallfilter: build with more architectures

- pkg/strace/syscalls_test.go
there is no unix.SYS_OPEN for arm64
> pkg/strace: fix linux/arm64 test

- cmds/fwtools/flash/flash_linux.go
- cmds/fwtools/flash/spi_linux.go
- pkg/flash/flash_linux.go
Believe it or not, this code worked last week. And not today. But Stefan and I did a bit of soldering action on the QSPI MUX and, who knows, maybe we busted it. But the logic analyzer shows the right things happening. 
I think this is a forward step, but if you see an error, please let me know.
> Spidevwrite

- go.mod
- pkg/align/align.go
- pkg/boot/kexec/memory_linux.go
- pkg/boot/kexec/memory_linux_test.go
* Improved FindSpace API to locate holes in MemoryMap.
Depends on https://github.com/u-root/u-root/pull/2878
> FindSpace with options

- pkg/termios/sgtty_netbsd.go
- pkg/termios/termios_bsd.go
- pkg/termios/var_netbsd.go
I don't have a netbsd box to test, but per my research, this seems like it should work...
If it doesn't, happy to fix whatever I did wrong.
Thanks!
> termios: support netbsd

- cmds/fwtools/flash/flash_linux.go
Add -size and -offset switches, for partial
reading and writing.
> fwtools/flash: allow user to set size and offset

- cmds/core/gosh/completer.go
- cmds/core/gosh/completer_common.go
- cmds/core/gosh/completer_liner.go
- cmds/core/gosh/completer_nobuild.go
- cmds/core/gosh/completer_test.go
- go.mod
- go.sum
- vendor/github.com/peterh/liner/COPYING
- vendor/github.com/peterh/liner/README.md
- vendor/github.com/peterh/liner/bsdinput.go
- vendor/github.com/peterh/liner/common.go
- vendor/github.com/peterh/liner/fallbackinput.go
- vendor/github.com/peterh/liner/input.go
- vendor/github.com/peterh/liner/input_darwin.go
- vendor/github.com/peterh/liner/input_linux.go
- vendor/github.com/peterh/liner/input_solaris.go
- vendor/github.com/peterh/liner/input_windows.go
- vendor/github.com/peterh/liner/line.go
- vendor/github.com/peterh/liner/output.go
- vendor/github.com/peterh/liner/output_solaris.go
- vendor/github.com/peterh/liner/output_unix.go
- vendor/github.com/peterh/liner/output_windows.go
- vendor/github.com/peterh/liner/unixmode.go
- vendor/github.com/peterh/liner/unixmode_solaris.go
- vendor/github.com/peterh/liner/width.go
- vendor/modules.txt
```
go build -tags=goshsmall
-rwxr-x--- 1 chrisko primarygroup 4.0M Feb  5 21:23 gosh
go build -tags=goshliner
-rwxr-x--- 1 chrisko primarygroup 4.2M Feb  5 21:23 gosh
go build
-rwxr-x--- 1 chrisko primarygroup 6.0M Feb  5 21:24 gosh
```
It's shitty, but I think it works?
Stripped binary sizes:
```
u-root world
21:38:45 Successfully built "/tmp/initramfs.linux_amd64.cpio" (size 21213340).
u-root -tags=goshsmall world
21:39:09 Successfully built "/tmp/initramfs.linux_amd64.cpio" (size 19935388).
u-root -tags=goshliner world
21:39:30 Successfully built "/tmp/initramfs.linux_amd64.cpio" (size 20045980).
```
> gosh with tab completion and history with small dependencies

- cmds/core/gosh/completer.go
- cmds/core/gosh/completer_liner.go
- cmds/core/gosh/completer_test.go
- cmds/core/gosh/gosh.go
- cmds/core/gosh/gosh_test.go
- cmds/core/gosh/testdata/setenv.sh
- integration/generic-tests/fork_bomb_test.go
And a couple of other ways that gosh arg interpretation was wrong.
Fixes #2938.
> Fix fork bomb

- pkg/ipmi/ipmi.go
to avoid possible confusion with Go builtins
> pkg/ipmi: rename len to length

- tools/vpdbootmanager/add.go
- tools/vpdbootmanager/main.go
using delete as a function prevent removing elements from a map in whole package
> tools/vpdbootmanager: rename delete to remove

- pkg/namespace/parser.go
- pkg/namespace/parser_test.go
to parse ./mount or mount syscall
> pkg/namespace: basename first argument

- cmds/core/unshare/unshare_linux.go
> cmds/core/unshare: align godoc with recent default shell

- cmds/core/sshd/sshd.go
- cmds/core/sshd/sshd_test.go
Start approach may not always able to send response back
> cmds/core/sshd: fix race condition

- CITATION.cff
Please add your information if you wish.
> Add a CITATION.cff

- pkg/boot/syslinux/syslinux.go
For systems with limited memory we can conserve memory by fetching initrd file without cache.
> Syslinux fetch initrd files without cache

- README.md
Let me know if this is sufficient or if I should add anything to this item.
> docs: update README for webiste deployments

- cmds/cluster/nodestats/main.go
- cmds/cluster/nodestats/main_test.go
Takes no arguments, dumps useful information.
> add cluster/nodestat command

- cmds/core/du/du.go
- cmds/core/du/du_test.go
If a symbolic link is specified on the command line, du shall count the size of the file or file hierarchy referenced by the link.
> cmds/core/du: add -H flag

- .github/workflows/codeql-analysis.yml
- .github/workflows/go.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/test-images.yml
- .github/workflows/tests.yml
Sorry if I missed a dependabot PR. Was just experimenting with this as one of the workflows was failing.
> update github/workflow actions 

- pkg/ipmi/ipmi.go
buf.Bytes()[2] <= 0xFF are always true, wrap error and simplify error handling
> pkg/ipmi: remove buf.Bytes()[2] <= 0xFF check

- cmds/core/msr/doc_linux_amd64.go
- cmds/core/msr/msr_linux_amd64.go
- pkg/forth/forth.go
- pkg/forth/forth_test.go
I think this makes the other msr PR unnecessary. 
I started to rip the forth out of msr, but ... it's just too handy. I figure if I can make the experience less awful, it may be nice to leave it in.
> Fixforth and msr

- pkg/strace/tracer.go
Implementation of issue #3157 
I believe the only issue is that the [three if statements](https://github.com/u-root/u-root/blob/main/pkg/strace/tracer.go#L410) will not be executed (but the `cont` function shouldn't be executed)
I also didn't want to duplicate the other 2 if statements
I tested the speed bump with a basic wget command, and it resulted in a 20-second improvement (Intercepting only connect & recvmg syscalls)
Also, this is how I implemented the seccomp tracing on `strace` `cmd` program (To only intercept the connect & recvmg syscalls):
<details>
<summary>Code Sample</summary>
```go
/// Copyright 2012-2018 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
//go:build (!tinygo || …
```
> Seccomp-bpf tracing

- pkg/strace/tracer.go
I was wondering the best way to implement `SecComp` to the `Trace` function (Continuation of #3158)
One idea: 
Introduces a new TraceWithSecComp function, allowing users to enable or disable seccomp filtering during tracing
operations, while maintaining the existing Trace function for backward compatibility.
> Add Seccomp Support to Trace Function

- pkg/boot/universalpayload/universalpayload_test.go
- pkg/securelaunch/launcher/vm_test.go
- pkg/securelaunch/policy/vm_test.go
copy testdata/mbrdisk to a private copy
write test files to a private directory
> pkg/securelaunch: fix launcher vmtests

- u-root.go
- uroot_test.go
This does not work, I don't see why.
> Default to ShellBang=true if GOOS=plan9

- cmds/exp/page/page.go
fixes https://github.com/u-root/u-root/issues/2039
> cmds/exp/page: restore terminal back if case of signal

- go.mod
- go.sum
- vendor/github.com/u-root/gobusybox/src/pkg/bb/bbmain/cmd/main.go
- vendor/github.com/u-root/gobusybox/src/pkg/golang/build.go
- vendor/github.com/u-root/gobusybox/src/pkg/golang/compiler.go
- vendor/modules.txt
ShellBang will not work on plan 9 builds until this goes in.
> Update gobusybox so Plan 9 builds work

- pkg/netstat/sockets.go
All numeric fields but one are hex, not decimal. It's surprising we did not hit this since last May. To date, there is only one entry in /proc/net/unix that actually HAS a hex number, but that was enough.
rminnich@pop-os:~/u-root/cmds/core/netstat$ grep B /proc/net/unix 0000000000000000: 0000000B 00000000 00000000 0002 03  3238 /run/systemd/journal/socket
I'd argue that, unless you NEED these to be numbers, you should just parse it as strings. The next time Linux messes with the format of /proc/net/unix, this may break.
See unix_seq_show() in net/unix/af_unix.c.
Make the return error more useful. The fmt package was returning the unhelpful 'expected space in input to match format', which was very confusing.
> pkg/netstat: fix parsing of /proc/net/unix

- cmds/core/netstat/netstat_linux.go
- pkg/netstat/format.go
- pkg/netstat/interfaces.go
> netstat integer overflow

- cmds/core/tail/tail.go
- cmds/core/tail/tail_test.go
tail -f file should not return an error for single file
> cmds/core/tail: fix follow and remove uint

- cmds/core/netcat/connect.go
- cmds/core/netcat/connect_test.go
- cmds/core/netcat/listen.go
- cmds/core/netcat/listen_test.go
- cmds/core/netcat/netcat.go
> netcat: explicit use of IPv4 and IPv6

- pkg/boot/bzimage/bzimage.go
If no decompressions succeed, show the errors for them all. This can be helpful when things go badly.
Also, show the names of decompressions tried, so people don't have to guess.
Create ErrNoMagic so we can write better tests. Shorten the error message.
Tidy things up a bit.
> pkg/boot/bzimage: use errors.Join for decompress

- integration/generic-tests/brctl_test.go
> integration/generic-tests: add brctl tests

- cmds/core/netcat/connect.go
- integration/generic-tests/netcat_test.go
The first patch is a small bugfix.
The second patch is an integration test to cover the use case from https://github.com/u-root/u-root/issues/3215 (which describes a symptom that I can't reproduce).
> integration/generic-tests: add netcat --exec tests

- cmds/core/netcat/netcat.go
- cmds/core/netcat/netcat_test.go
- pkg/netcat/exec.go
Remove unimplemented features.
> netcat: clean-up usage message

- pkg/cpio/newc_test.go
fix https://github.com/u-root/u-root/issues/3382
> pkg/cpio: fix Debug output

- .vmtest.yaml
- cmds/core/ip/tunnel_linux.go
- cmds/core/ip/tunnel_linux_test.go
- integration/generic-tests/ip_test.go
This PR adds the IP tunnel subcommand to the IP integration test.
It also contains some fixes and extensions of the cmd itself.
> Ip tunnel integration test

- cmds/exp/traceroute/main.go
- integration/generic-tests/traceroute_test.go
- pkg/traceroute/tcp6.go
- pkg/traceroute/traceroute.go
- pkg/traceroute/udp6.go
- pkg/traceroute/util.go
Add integration tests for traceroute
TODO:
> integration/generic: add traceroute

- cmds/core/date/date.go
- cmds/core/date/date_unix.go
./date +%j returns 188, and date +%j returns 181,
propagate error from setDate anyway run will call Fatal
> cmds/core/date: fix +%j calculation

- go.mod
- go.sum
- vendor/github.com/ulikunitz/xz/README.md
- vendor/github.com/ulikunitz/xz/SECURITY.md
- vendor/github.com/ulikunitz/xz/TODO.md
- vendor/github.com/ulikunitz/xz/lzma/header.go
- vendor/github.com/ulikunitz/xz/lzma/reader.go
- vendor/github.com/ulikunitz/xz/lzma/writer.go
- vendor/modules.txt
dependabot picked 5.14, which had a 32-bit problem
> update to ulikunits/xz 5.15
