u-root/u-root

- cmds/ln/ln.go
- cmds/ln/ln_test.go
I added some common treatment at GNU implementation of ln.
The command in that moment works that way:
```
SYNOPSIS:
ln [OPTIONS]... [-T] TARGET LINK_NAME   (1st form) (posix)
ln [OPTIONS]... TARGET                  (2nd form) (gnu)
ln [OPTIONS]... TARGET... DIRECTORY     (3rd form) (posix)
ln [OPTIONS]... -t DIRECTORY TARGET...  (4th form) (gnu)
OPTIONS:
-t [string] receive a directory to put the links (gnu)
-i interactive mode to ask for overwrite (gnu)
-f force the last flag and don't ask about overwrite (posix)
-s create symbolic links instead hard links (gnu)
-v verbose mode to print each link created (gnu)
-T treat LINK_NAME operand as a normal file always (gnu)
-r create symbolic links relative to link location (gnu)
-P make hard links directly to symbolic links (posix)
-L …
```
> Add command ln full POSIX compliant + tests

- README.md
Just a little typo at the end of url. 'uroot' -> 'u-root'.
I think is better show up build status at top of readme.md.
Because that I moved the badge location on readme.
> Badge of build status fixed at README

- cmds/ps/ps.go
- cmds/ps/ps_linux.go
- cmds/ps/ps_test.go
We have a problem here, the -x implies the long command line expansion
at executing ps. However, if we don't put a limit, at example erlier
I assumpt the the width size of terminal, unfortunally the
visual table will break. For that, i disabled the long command line
expansion @ line 118 on ps_linux.go file.
Probably now the build at travis will works. Because I did can't
reply the 'process dissapears error' I only try a fix here.
Let's see what travis-ci will say.
> ps.go: remove terminal stuff and fixed error when process disappears

- .travis.yml
I setup at slack of u-root an integration with travis CI
https://slack.com/apps/A0F81FP4N-travis-ci
I think is nice receive the build status of PR and commits
to easily see if something is broken.
> travis.yml: add slack notifications -> #build-notices

- scripts/ramfs.go
However, the dhcp doesn't compiling yet. Now we have some
trouble about deadlock goroutines.
> ramfs.go: add netlink to keep at src, solve the dhcp import problem

- cmds/dhcp/c2.go
beats a panic due to a deadlock any day.
> dhcp: if there are no interfaces that match our re, print a nice message

- uroot/root.go
This matters when we merge into other initramfs instances.
> init: set paths in the right order and with the right elements.

- cmds/init/init.go
- cmds/tcz/tcz.go
- uroot/root.go
We're very, very close. Here is how I build an initramfs with a combined tinycore cpio:
go run ramfs.go -cpio ~/projects/u-root/tinycore64-6.4/boot/corepure64
This gets all the way to an ash prompt. You can then run ordinary commands.
If you want a uniquely u-root command you can just type, e.g.
rush
and the right things happen. If you want a command that is also in /bin, e.g. date,
/buildbin/date
If you're in a stupid shell that wants to be smart and remember things, like ash, you'll have to do this:
hash -r
to clear its hash.
rush has no such problem but it has lots of limits too.
Tinycore package fetching is not quite right yet in the combined initramfs. I'm not sure why.
> initramfs: clean things.

- uroot/root.go
This way, when a u-root command in /buildbin is built into /ubin, it will
be found in /ubin.
With this change, tinycore integration works very smoothly. To install a new command,
e.g. bash, one simply does
sudo -E tcz bash
and bash is ready to use.
> initramfs: set $IFS to `hash -r` so newly build u-root commands are found

- RUN_ME_FIRST
- scripts/getimports.go
getimports.go is intended to replace the external tool we are currently using. It will remove
the need to maintain a .yaml to list the packages. To find the packages it needs it will
walk the tree of cmds, compute the imports, and go get them.
> getimports.go

- cmds/date/date.go
- cmds/date/date_test.go
It now accepts the MMDDhhmm[[CC]YY][.ss] format.
> date: change argument management so we can also set the date.

- cmds/kexec/kexec.go
- cmds/kexec/kexec_test.go
This is only going to work on 4.x kernels.
> kexec: add support for kexec_file_load

- cmds/date/date.go
> Change the variable names for the set command to match the command names.

- cmds/kexec/kexec.go
We don't want to fatalf unconditionally for kexec. Only do so if we
actually get an error
> Fix unconditional FatalF

- cmds/validate/validate.go
- cmds/validate/validate_test.go
move the individual validates into a function.
h.New() panics if the function is not compiled in, have the function
recover from that
Keep track of what hashes could be tried and what were tried. Print out the
ones we actually tried at the end.
The signature file might be binary; if the signature fails, try its contents
as a binary signature.
> validate: check binary signatures, handle missing libraries

- cmds/gpgv/gpgv.go
usage
gpgv [-v] keyring signature file
There doesn't seem to be a way to do this in the domain of the crypto
package, or did I miss something?
> gpgv: add a gpgv command

- cmds/rush/parse.go
- cmds/rush/rush.go
Rush was not properly closing redirection files. This was a
result of our not having fork/exec; things just have to be done
differently.
Add a map of io.Closers to the Command struct, called files, and have
OpenRead and OpenWrite add opened files to it.
In runit, add a defer() to close all files in the files map.
> rush: fix dangling open files from > and <

- scripts/ramfs.go
I was incorrectly stripping off two levels of directory, not one.
> ramfs.go: correctly guess the goroot from the go binary path.

- cmds/sort/sort.go
- cmds/sort/sort_test.go
"Essential options" includes reverse (-r) and output file (-o). This
implementation is nowhere near the sophistication of coreutil's 4500+
line implementation. I did not implement any parallelization,
compression, etc... Also, the entire dataset to sort must be loaded into
memory at once.
Testing does not include inputting multiple files and a few edge cases
(such as concatenating files which do not end with a newline character).
Examples usages:
sort < a.in > b.out
sort -r < a.in > b.out
sort a.in -o b.out
This is my first u-root contribution, so be diligent! Also, is there anything manual to be done for the following?
- busybox sort command
- add sort_test.go to travis CI
> Implement sort command, essential options and test

- README.md
This creates a link to https://godoc.org/github.com/u-root/u-root which is an HTML page generated from the comments in our go source code.
It looks really nice and looks almost like a man page. I'll try to add more comments in the proper format to make the page more complete.
Also, all the badges are now on the same line.
> Add a link to a generated html godocs

- cmds/builtin/builtin.go
In github, you can see where it says "100755 → 100644" on the file. That means the exec bit is removed.
The go source file does not require exec bits. Correct me if I'm wrong and I will add a comment explaining why this file requires an exec bit.
Additionally, this commit removes the misleading docstring on the package. I think it was a copy-paste error. I will come up with a man-page for it when I do another run-through on the man pages.
> Remove the exec bit from builtin.go

- cmds/dmesg/dmesg_test.go
As they stand, these tests are really bad for the following reasons:
- Tests are non-deterministic (cannot predict the contents of dmesg)
- The second test requires root permissions to run. When uid != 0, the
second test is skipped to allow the build to pass in travis.
These issues result from the inability to mock the syscall.
I'm brainstorming a way to place syscall in an interface so that it can
be mocked in the test. It is a teensy bit tricky because the executable
and test code are in separate binaries.
> Dmesg test

- cmds/fmap/fmap.go
- cmds/fmap/lib/fmap.go
- cmds/fmap/lib/fmap_test.go
The checksum flag (`-c sha1`) creates a hash checksum in the same manner as the open source C implementation (https://flashmap.googlecode.com/).
In addition to sha1, this tool support md5 and sha256 (which is extremely easy to do in Go).
> Perform a checksum of the static flash areas

- cmds/ps/ps_linux.go
Running ps (at least for me) would always panic when attempting to call
the `Error` member on `err`.
> Fix panic when running ps

- cmds/printenv/printenv_test.go
Before, the test was guaranteed to fail if an environment variable
contained a newline. This part of a larger problem of sending
unstructured data through pipes.
> Use preset env variables for printenv_test.go

- cmds/shutdown/shutdown.go
- cmds/shutdown/shutdown_test.go
This one has few niceties. It does what you ask: halt, suspend, or reboot.
It does not have nice friendly delays. You get what you ask.
Usage:
shutdown [-dryrun] [halt|suspend|reboot]
> shutdown: add a shutdown command.

- cmds/init/init.go
- cmds/installcommand/installcommand.go
I noticed something inefficient regarding the process tree:
```
- init
- installcommand (symlinked from rush)
- rush
- installcommand (symlinked from ps)
- ps
```
`init` is PID 1. `installcommand` is `init`'s child. `rush` is
`installcommand`'s child. Etc...
By using syscall.Exec in installcommand, the tree is simplified to what
you would expect:
```
- init
- rush
- ps
```
This will likely make process control easier because a process's
children are always its children regardless of being run through
`installcommand`. Features like `CTRL-C`, `CTRL-Z`, and `&` should be
easier to implement.
Also in this PR:
- Reboot gracefully when the init process exits
> Installcommand exec

- bb/bb.go
- scripts/ramfs.go
ramfs will default, as before, to all the files in cmds/.
It uses the filepath.Glob to find those files with the
pattern [a-zA-Z]* (this avoids useless warnings about
files like .gitignore).
If there are arguments left after flag.Parse, these are
used as Glob patterns instead. For example,
ramfs rush date
will build a ramfs with the full go toolchain but only
rush and date.
ramfs i*
will include commands starting with i.
It is NOT an error to specify a glob which matches nothing.
This results in an initramfs with init and Go toolchain,
but no pkg sources or u-root commands. This is useful for merging
into another initramfs cpio if you want to put a Go toolchain
in it.
> ramfs: support selection of package names

- uroot/root.go
It might also be worth looking into CONFIG_DEVTMPFS_MOUNT which performs
the same action, but from within the kernel.
> Mount a devtmpfs

- cmds/fmap/fmap.go
- cmds/fmap/fmap_test.go
- cmds/fmap/lib/fmap.go
- cmds/fmap/lib/fmap_test.go
This add two flags:
- `-jr JSON_FILE`: read from the flash and write a JSON encoded flash
map to `JSON_FILE`
- `-jw JSON_FILE`: read from the JSON file and overwrite the flash map
of flash at the location given in the JSON file
Admittedly, the tool could be a lot safer. For example, the FMap
clobbers any data if it needs to grow larger. Instead, the tool should
(not implemented yet!) check to see if the data it is overwriting is
used (contains all 0x00 or all 0xff) and emit and appropriate warning.
> Implement reading/writing FMap to/from JSON files

- cmds/ectool/commands.go
- cmds/ectool/eclib.go
- cmds/ectool/ectool.go
- cmds/ectool/info.go
- cmds/ectool/io.go
- cmds/ectool/lpc.go
This removes a huge chunk of warnings from our go report card. Only changes in identifiers and comments. The only test I performed was compiling + running `ectool --help`. 
> Apply lint suggestions to ectool

- cmds/dd/dd_test.go
- shared/testutil/testutil.go
Add benchmark for dd command
Example usage:
Benchmarking u-root's dd command:
$ go test -bench=Dd
BenchmarkDd-12           10000        16263 ns/op    644.55 MB/s
PASS
ok      github.com/u-root/u-root/cmds/dd    4.198s
Benchmarking your system's dd command:
$ EXECPATH=dd go test -bench=Dd
BenchmarkDd-12           30000         4809 ns/op    2180.25 MB/s
PASS
ok      github.com/u-root/u-root/cmds/dd    2.075s
The "op" unit measures 1 MiB block.
> Dd benchmark

- cmds/ps/ps.go
- cmds/ps/ps_linux.go
- cmds/ps/ps_test.go
Procfs is very alive. Subdirectories can be added and removed at
anytime. `os.Walk`ing over `/proc` and expecting a file to exist on a
subsequent syscall is a race condition waiting to happen.
The solution is to implement a simpler version of `os.Walk` which simply
walks over a single directory. Additionally, "file does not exist"
errors are ignored.
I tested this issue by killing many processes per second:
while true; do /bin/true; done
In another terminal, run:
for i in {1..1000}; do ./ps > /dev/null; done
No longer will you see fatal error messages and SIGSEVs.
Fixes #28
> Fix ps to be stable with terminated processes

- cmds/dd/dd.go
It now reads and writes at the blocksize, e.g. 1M.
Sadly, however, the performance is really not catching up with dd.
The test fails, but that is because of a bug in the test. When you take
string(out) it's adding three nulls. Ryan, help!
> dd: make it a bit better at IO.

- cmds/dd/dd.go
> dd: set default block size to 512 bytes

- cmds/init/bgbuild.go
- cmds/init/init.go
- cmds/installcommand/installcommand.go
Commands will start building themselves without any user input. These
"background builds" occur in low priority processes, so in theory, they
should not affect the overall performance of the system. If you
continuously `ls /ubin`, you will see commands appearing automatically.
Here are some design decisions which had to be made:
- `installcommand` sets its own priority to low when passed in the
`-lowpri` flag. When `installcommand` runs `go build`, `go build` will
inherit the priority of `installcommand`. Go does not provide the
means to create processes at a specified priority, so this was the
work-around.
- Commands are built approximately in order from smallest to largest
length of the command name. So, two letter commands like `ls` and `cd`
will be built before `mknod` and `mount`. …
> Build commands in a background process

- bb/bb.go
realistically, we should be pid 1, and if we're not, we should not
set things up. This makes some aspects of testing in a chroot harder
but it's probably the right thing to do anyway.
> busybox init; test against pid 1

- cmds/init/init.go
- cmds/uinit/uinit.go
This acts as a shitty init script that we can use to run commands before
starting the shell.
> Crappy uinit.go

- scripts/ramfs.go
This saves about 700K in the COMPRESSED initramfs, over 3M uncompressed.
> bin/go: build bin/go with tags cmd_go_bootstrap

- bb/bb.go
- cmds/rush/rush.go
Change init() -> Init() for every command.
Create a map of command names to init functions.
In the init() function, if os.Args[0] is in the map, then
run its Init().
The startup code now only runs one init, not all of them for all
commands.
For tools that don't set their own usage, the usage is now usable, e.g.:
ls -q
flag provided but not defined: -ls.q
Usage: ls:
Flag Q: 'quoted', Default false, Value false
Flag R: 'equivalent to findutil's find', Default false, Value false
Flag l: 'long form', Default false, Value false
the 'flag provided but not defined .... '
text ought to go away at some point however.
That said, this is a big improvement; it's also one Russ
also suggested we use, so we independently reached this
same point.
> fix busybox mode init() and argument error processing

- cmds/comm/comm.go
- cmds/date/date.go
- cmds/ps/ps.go
- cmds/pwd/pwd.go
- cmds/rm/rm.go
- cmds/seq/seq.go
In some cases we had been writing our own usage function,
which leads to awkward looking output. It turns out that
if one wants more information than just os.Args[0], one
can set os.Args[0] before calling flag.Usage.
This change uses a function literal to create closure
to be assigned to flag.Usage such that we can set os.Args[0]
and get more natural looking output, e.g.
date -z
flag provided but not defined: -z
Usage of date [-u] [+format] | date [-u] [MMDDhhmm[CC]YY[.ss]]:
-u    Coordinated Universal Time (UTC)
This will also allow us to better use the busybox mode. It provides
its own usage function but this design will let us provide our additional
text while still using the busybox functtion too.
> usage: fix up usage so we can keep using flag.Usage

- bb/bb.go
Fixed so as to iterate over initMap while initializing. Symlinks are created in /ubin now.
> Init cmds in ubin

- cmds/dhclient/dhclient.go
missing return.
We'll take on the cleanup he suggested later. This is simple and gets it done.
> dhclient: fix error pointed out by Chris

- cmds/init/init.go
- scripts/ramfs.go
It's becoming more and more clear as Xuan and I try to get control tty working
that init needs to have some idea that it's in a chroot, i.e. test mode.
Add a test flag to init which disables setting Ctty and Setsid in the
command; have ramfs set this flag when it runs the chroot.
> init: add a test flag

- cmds/field/field.go
This is an implementation of the `field` command, essentially the same
as the so-named command inthe Harvey operating system.  It splits lines
of files up into fields and prints selected fields.  The behavior is
similar to that of the `awk` and `cut` commands.
Signed-off-by: Dan Cross <cross@gajendra.net>
> Add 'field' command.

- cmds/rush/rush.go
- cmds/rush/tty_linux.go
We add a tty() function to be called before the main command loop;
and a foreground() function which is called at the top of the loop.
This is basically what ash does and it works fine.
Any new kernels this is ported to will have to define a tty handler.
This will let us test the broken tty setup in our initramfs. We've got something
wrong somehow.
> rush: add tty  support

- cmds/comm/comm.go
- cmds/cp/cp.go
- cmds/date/date.go
- cmds/field/field.go
- cmds/ps/ps.go
- cmds/pwd/pwd.go
- cmds/rm/rm.go
- cmds/seq/seq.go
The code to set up the chaining of calls to flag.Usage was
just a bit too clever for it's own good: it created a lambda
that took the old value as an argument, but all that lambda
did was set up a closure over that same old value that invoked
it with the right argument string.
It seems simpler and more easier to understand to just copy
the old value into a new variable and close over that.
Signed-off-by: Dan Cross <cross@gajendra.net>
> Clean up overriding of flag.Usage functions.

- cmds/ls/fileinfo_linux.go
- cmds/ls/ls.go
somewhere along the line ls stopped displaying anything useful about symlinks.
Fix it.
TODO: The tests here are really bad.
> ls: fix display of information

- uroot/root.go
We need it, and especially need /dev/tty. Plus, it's just
way easier to have it in source like this.
> uroot: bring back device creation

- cmds/installcommand/installcommand.go
Because of uncertainties about os.Exec, we biased towards not exec'ing
unless told otherwise. With this change, we bias towards having
installcommand use os.Exec unless INSTALLCOMMAND_NOEXEC is set.
This leads to a much tidier process tree.
> installcommand: use os.Exec unless told not to by INSTALLCOMMAND_NOEXEC

- cmds/ps/ps.go
with -x you can now see pgrp, sid, tty, which has been invaluable in debugging.
At some point this needs to be redone to let you specify your display but this
is very helpful for now.
> ps: add more info

- uroot/root.go
Create /dev/urandom during initialization, so as to provide alternative if booting up happens earlier than random number generator getting prepared.
Signed-off-by: xchenan <xchenan@gmail.com>
> Mknod /dev/urandom

- uroot/root.go
A small fix for tty's device id. /dev/console has 0x501, abd /dev/tty has 0x500.
Signed-off-by: xchenan <xchenan@gmail.com>
> Small fix for device id of /dev/tty

- cmds/dhclient/dhclient.go
When numRenewals is zero or negative, dhclient requests for renewal infinitely.
By default dhclient requests for renewal infinitely.
Signed-off-by: xchenan <xchenan@gmail.com>
> Enabled infinite renewal from dhclient

- cmds/mount/mount.go
Add filesystem mount options (-o) to cmds/mount. At some point it may be worth parsing the mount options in the same way mount(8) does.
@rminnich
> cmds/mount: add filesystem mount options flag

- uroot/root.go
In the process of exporting variables I screwed up some
strings. Next time I'll use the tools. Sorry.
Review if you want but I'll probably chump this one in. Stupid of me.
> rootfs: fix moron bug (Dev->dev, etc.)

- bb/bb.go
- bb/config.go
When I first did this I did not reckon with the full
need we'd have for GOPATH.
This also includes cleanup from some of the gross ways I used
config struct for per-command data; it has a new Command struct
which is used instead.
> bb: allow GOPATH with multiple elements

- cmds/rush/tty_linux.go
- cmds/stty/stty.go
- cmds/stty/termios.go
- cmds/stty/termios_linux.go
You can do things like
stty raw
Default is to just print stuff out.
You can say
stty dump
and it will dump JSON. then you can say:
stty load < file.json
and it get restored, or even
stty Save | sed command > load.json
stty load load.json
and you can have a filter that modifies stty settings.
You can also do this:
stty save > push.json
stty raw
do stuff
stty load  push.json
i.e. stty is more unix-like than it's been.
Also, the stty struct in termios.go is intended to have enough struct members to cover a superset of uses, so it
may nbot fit all cases. I.e. there might be a variable in there that would have no meaning on OSX
Just keep in mind, termios.go is supposed to be sort of OS-agnostic, with nasty bits in termios_os.go. Also, lest anyone
forget, this should be able to work on systems …
> add stty command

- cmds/ps/ps.go
It just was not acting well with flag.Parse in init.
> ps: move flag.Parse to main

- bb/bb.go
- cmds/rush/rush.go
- cmds/rush/tty_linux.go
This set of changes finally makes rush work sanely, for foreground and background processes, and
gets minimega way farther along.
> busybox init and cmds/rush: make tty behavior correct, helps minimega

- pkg/cpio/fs_unix.go
- pkg/cpio/sysinfo_darwin.go
- pkg/cpio/sysinfo_linux.go
Stat_t are just different enough that we need a sysInfo function
for each kernel type.
Signed-off-by: Ron Minnich <rminnich@gmail.com>
> pkg/cpio: add support for darwin

- uroot/root.go
We have to create dev/pts AFTER trying to mount devtmpfs, else
that is lots, and the devpts mount fails.
Tested and fixes a minimega problem.
> uroot/root: create dev/pts AFTER trying to mount devtmpfs

- bb/bb.go
For convenience, it's nice to ignore globs that have no match (e.g.
when switching around between branches).
But it is awful if you end up with unmatched things and don't know it
(right Gan?)
For each unmatched glob, print a warning; if there are ZERO match
globs, print a warning. Sometimes we *want* zero matched globs,
so this is not an error.
> bb: warn people when there are unmatched globs

- cmds/dhclient/dhclient.go
* If lease time is 0, the renewals are unnecessary anymore.
* Sleep time should be applied for testing mode also (dhcpv4).
> Fixed dhcp timing issue

- bb/devCPIO.go
- pkg/cpio/fs_unix.go
- pkg/cpio/newc/newc.go
- pkg/cpio/newc/newc_test.go
- pkg/cpio/types.go
It's important to not have lots of files open, and
to not read all the files in, and to close files
we open as soon as we are done. So we need to implement
ReadCloser.
We implement a struct that implements ReadCloser with a Close
that always works, since it does nothing;
and another struct that implements Read
by remembering the name and deferring the open until first use.
The assumption here is that our pattern of use is read, then close.
That applies to cpio perfectly.
> cpio: fix Record so it implements ReadCloser

- cmds/msr/msr.go
- cmds/msr/msr_linux.go
usage:
msr r glob 32-bit-number
msr w glob 32-bit number 64-bit value
Unlike the rdmsr/wrmsr commands, this one lets you do a whole bunch
of processors in one pass. It accumulates a list of errors, one per msr
operation. If there is an error,
it will print an error for that one operation. If there is not an
error, for read, it prints the msr value.
I tried several approaches for the specification of the set of cores
and the glob was by far the most convenient. It's possible we'll have
an OS where a string will not suffice to name an MSR but we can cross
that bridge when we come to it.
> msr command

- cmds/dhclient/dhclient.go
- pkg/dhcp6client/dhcp6client.go
- pkg/dhcp6client/packetSock.go
If DHCPv6 client has not been receiving packets for a certain amount of time after it sends out a DHCPv6 solicit message, it will try to resend the solicit message. This handles the situation when interface is not even up, or some other unknown issues probably
> Dhcpv6 timeout

- bb/bb.go
- bb/devCPIO.go
- bb/ramfs.go
- pkg/cpio/cpio.go
- pkg/cpio/fs_unix.go
- pkg/cpio/newc/newc.go
- pkg/cpio/types.go
You can now do this:
bb -cmds /bin/bash 
and it will include bash in the initramfs. It's a space-separated
list so you can, for example, say:
bb -cmds '/bin/bash /usr/bin/git'
and it works.
this will be helpful as we bring u-root up to speed on chromebooks
and minimega
> Extend bb so we can add existing commands

- cmds/tcz/tcz.go
This commit corrects the way TCZ looks for duplicate symlinks when
it is creating symlinks from fetched pacakges. Before, the command
would abort on symlinks that should exist. Now it will safely
ignore existing symlinks. Use correct go error handling.
Signed-off-by: laconicpneumonic <tonyprolland@gmail.com>
> Correct duplicate symlink check in TCZ

- cmds/tcz/tcz.go
1. It downloads tcz packages that already exist
2. It will mount on top of older versions
3. It does not create tcloop directories correctly
- It spltis on "." instead of removing ".tcz" from the command names
- This causes packages to be mounted in the same place i.e. "Xorg-7.7.tcz" and "Xorg-7.7-bin.tcz" both mount to "Xorg-7"
4. It needs a debug flag "-d" to enable/disable print statements
All code written with @ananion-cation
> Fix and Upgrade TCZ

- uroot/root.go
In the case that we use persistent storage, "/tmp" should be mounted as "tmpfs". Now programs that count on "/tmp" being empty on boot like Xorg, tcz, etc, will not fail.
> Mount tmpfs on /tmp during the creation of Rootfs

- pkg/cpio/cpio.go
- pkg/cpio/fs_unix.go
It turns out cpio files are not required to specify the
directories for files, i.e. if you have
a/b/c/d
you don't need records for a, a/b, and a/b/c. This is
kind of nuts because when you unpack the archive
you've got no idea as to ownership and modes of
a, a/b, or a/b/c. But I did not write the spec.
So, we'll do our best. For each file/special/symlink,
we split out the dir and do a MkdirAll with mode 755.
Note that if the directory existed with a different mode
we may change that mode. The go runtime doesn't actually
check if the directory exists before trying to make it.
I don't think this matters: cpio is a dead
format save for the kernel initramfs.
> pkg/cpio: create dir when creating files/specials/symlinks

- cmds/ps/ps.go
Now ps can accept any permutation of "aux" as its first argument and it
will return the GNU ps output for "axu". "-x" now returns the
appropriate categories.
> Add "aux" option to ps and correct output for "-x"

- bb/ramfs.go
1. Allows for multiple spaces ex: "a    (4 spaces) b c d" will  be interpreted as [a,b,c,d]
2.Combine cmd and extra flag so it is just cmd
> ramfs:Fixing multiple spaces between commands and merging cmds and extra flag into just cmds

- cmds/tcz/tcz.go
This will allow us to build a NiChrome image ahead of time
that contains all the packages,
i.e. avoid the need to fetch the images after we boot.
Note that fetching after boot will still work. If we
want a package after boot and it's not there, and the
net is up, tcz will fetch it. But if it's there, there's
no need to fetch and tcz won't.
Hence, we don't need to change xinit
one bit, but we can make its life much easier by preloading
a set of tcz's on the usb stick.
The -i switch, which defaults to true, determines whether we
install the packages, i.e. do the loopback mount and create
symlinks.
The -r switch, which defaults to /tcz, lets us determine where the
packages go.
Suppose in NiChrome we have a list of packages we want to
make available on ROOT-A. Suppose it's just bash
and …
> tcz: add options so we can fetch all the tcz files

- cmds/wifi/wifi.go
- cmds/xinit/xinit.go
- uroot/root.go
I just tested this on the chromebook parrot and it
works.
tcz wifi (assuming you don't automatically load that package)
PATH=$PATH:/usr/local/sbin
wifi essid password
and we're up.
> wireless: add a simple wifi tool

- travis.sh
until we fix this, tpm and arm breaks go, so turn of arm for now.
This whole experience uncovered an interesting fail in github ...
> ARM breaks go

- cmds/xinit/xinit.go
xinit need not do the package loading; that should be done
by an init script. In NiChrome, that is uinit.go
Note that a new PR for NiChrome implements the package loading
already. The next step here is to remove sshd startup from
xinit.go
> xinit: remove package loading

- cmds/builtin/builtin.go
- cmds/pflask/pflask.go
- cmds/ps/ps_linux.go
- cmds/rm/rm.go
- cmds/rm/rm_test.go
- cmds/rush/parse.go
- cmds/rush/rush.go
- cmds/validate/validate_test.go
- cmds/which/which.go
- pkg/memmap/memmap.go
- pkg/memmap/memmap/memmap.go
- pkg/memmap/memmap/memmap_test.go
- pkg/memmap/memmap_test.go
This pull request resolves https://github.com/u-root/u-root/issues/206
I ran the `travis.sh` tests inside of a _travis like_ container using the following command.  I expect this pr will run the same but wanted a way to test locally as well.
```
% docker run -e "PATH=/home/travis/gopath/bin:$PATH" --privileged -u travis -it -v /Users/bkochendorfer/go/src/github.com/u-root/u-root:/home/travis/gopath/src/github.com/u-root/u-root quay.io/travisci/travis-go:latest bash
% # setup golang 1.9 using gimme
% bash travis.sh
... output ...
Mon Sep 18 18:49:42 UTC 2017
Did it blend
root@d2a1a53b5130:/home/travis/gopath/src/github.com/u-root/u-root# echo $?
0
root@d2a1a53b5130:/home/travis/gopath/src/github.com/u-root/u-root# exit
```
> Replace path.join with filepath.join

- bb/bb.go
- bb/ramfs.go
All the nonsense is gone and flag handling is sane.
Basic idea is to create per-package FlagSet variable per for flags,
then rewrite all usages of the flag package to use the per-package
variable.
I've been testing this and it's working extremely well.
Let me know if you see an issue. The code is far better than it
was.
> fix the crummy busybox flags code

- cmds/xinit/xinit.go
xinit really should not be in the business of starting sshd.
We can define another tool for that later.
We can test for the existence of /tmp/.X*/X? (the X socket)
and once that is there, start X clients. That's much better than
the 5 second timeout.
With these changes startup is much faster. X display is up in 8 seconds
and aterm and opera are there in 10. There's a few more seconds that will
be shaved off once we are on the MMC. I think we can get to 4 or 5.
> xinit: remove ssh startup, speed up x startup

- cmds/ip/ip.go
I blanket-replaced use of argv[0] with calls to one()
in all the functions. This caused a bug in one place.
That further messed up nichrome. It's fixed now.
> ip: fix bug introduced by substring commands

- cmds/ip/ip.go
Here comes a few enhancements for the `ip` command. Everything in this pull request is done to help the `ip` command to behave like the standard implementation.
* Output formating for `ip addr` and `ip link`
* `ip link` command now print links information like `ip link show` do instead of printing usage
* Command shortcuts (e.g. `ip l sh` for `ip link show`)
```
% ip addr
ip: &{{1 65536 1 lo  up|loopback 65609 0 0 <nil>  0xc42007d12c 0 <nil> loopback <nil> unknown}}: [127.0.0.1/8 lo ::1/128]
ip: &{{2 1500 1000 enp0s3 02:19:3b:8a:ad:b3 up|broadcast|multicast 69699 0 0 <nil>  0xc42007d5d0 0 <nil> ether <nil> up}}: [10.0.2.15/24 enp0s3 10.0.2.200/24 enp0s3 fe80::19:3bff:fe8a:adb3/64]
```
```
% ip link show
ip: &{{1 65536 1 lo  up|loopback 65609 0 0 <nil>  0xc42007d12c 0 <nil> loopback <nil> …
```
> `ip` command enhancements

- cmds/cp/cp.go
- cmds/ln/ln.go
- cmds/rm/rm.go
The first commit is an actual bugfix (index out of bounds). The second one unifies how answers to '-i' are handled.  So far every command did that slightly different, where some strictly only accepted 'y', where some accepted 'y'something, some used Scanner, some ReadString, some fmt.Scanln().
So this is a fist step to unify them: Use ReadString and accept what coreutils accept as "yes".
If you want me to move that AskYes() in its own package, just tell me. Could be a follow up or an update to this PR. If so, suggestions for a pkg name? "utils"? :-P. Any preferences on strings.ToLower() vs. == 'y' || == 'Y'?
> Fix bug in rm -i and streamline how -i is handled

- cmds/pci/pci_linux.go
- cmds/pci/types.go
Enable the use of the "-n" argument to show vendor and device ID.
Signed-off-by: Ben Allen <bensallen@me.com>
> cmds/pci: Enable numbers argument

- cmds/field/field.go
- cmds/pwd/pwd.go
- cmds/rm/rm.go
- cmds/seq/seq.go
- cmds/uname/uname.go
As stated by Chris in the truncate PR, this should always happen in main().
Found them with some git grep -A5 -B5. Maybe I missed some, but this is a start. I don't see how this should break something. I ran the tests, and tried the ones that do not have a _test.go manually.
> Move flag.Parse() to main

- README.md
The existing invocation is missing a glob on the end that causes a build
failure.
Beyond that it is lacking in context of which directory it must be run
from to work correctly, and the required packages for elvish.
I don't know how best to explain the need to go get boltdb/bolt. It
seems to be a bug in the build tool that it doesn't look in the proper
vendor directories.
Updates #420
Signed-off-by: Michael Pratt <michael@pratt.im>
> README: provide a working bb invocation

- bb/config.go
That change broke the handling of GOPATH that had multiple
:-separate elements. This gets it back to how it used to
work.
This does not fix the problem reported in #420, with an elvish
build requiring a go get of boltdb.
> bb: Fix Gopath/Gopaths handling broken in bf8bc

- pkg/kexec/kexec_linux_amd64.go
- pkg/kmodule/kmodule_linux.go
- pkg/kmodule/kmodule_linux_amd64.go
- pkg/kmodule/kmodule_linux_arm64.go
- pkg/kmodule/kmodule_linux_ppc64le.go
Use the architecture-specific syscall numbers for kexec_file_load(2) and finit_module(2) from golang.org/x/sys/unix instead of locally duplicating them. Also switch the packages to use functions from x/sys/unix instead of syscall (as per the comment in https://github.com/golang/go/blob/master/src/syscall/syscall.go#L21-L28).
> Use syscall numbers from x/sys/unix

- cmds/pflask/pflask.go
- cmds/pflask/termios.go
- pkg/pty/pty.go
- pkg/termios/termios.go
- pkg/termios/termios_linux.go
Follow up on #429 and convert pkg/termios to use functions, types and constants from golang.org/x/sys/unix. Also convert cmds/pflask to use the updated termios package instead of locally duplicating its functionality.
The last commit fixes some golint warnings in cmds/pflask (already present before this PR), which I encountered while checking my changes.
> Convert pkg/termios to use x/sys/unix

- cmds/switch_root/switch_root.go
A couple quick lint fixes for the `switch_root` command.
> Lint fixes for `switch_root`

- pkg/uroot/bb.go
Fixes #447.
Signed-off-by: Christopher Koch <c@chrisko.ch>
> pkg/uroot: remove bbsh before regenerating.

- pkg/uroot/uroot.go
- u-root.go
This enables people to include pkg/uroot in their own packages and be
met with the same API available on the command-line.
Fixes #440.
> pkg/uroot: define the command-line interface as a Go API.

- cmds/xinit/xinit.go
chrome: make chrome the startup browser in xinit
midori is just a bug-filled pit and opera-12 is just
not good enough to keep trying to start. Chrome works.
We can add firefox quantum later if anyone cares.
>     chrome: make chrome the startup browser in xinit

- pkg/uroot/util/root.go
It is a bit bizarre but the convention nowadays is to mount
tmpfs on /dev/shm. If you don't do this chrome throws a
memory allocation error.
> chrome: mount tmpfs on /dev/shm

- roadmap.md
we don't need or want - for stdin ever
we need gzip for chrome
> fix entry for cat and add gzip

- pkg/gpt/gpt.go
- pkg/gpt/gpt_test.go
Instead of just 'things differ'
TODO: PartitionsDiffer
> package gpt: make the EqualHeader return useful info

- cmds/pci/pci.go
- pkg/pci/devices.go
- pkg/pci/ids.go
- pkg/pci/lookup.go
- pkg/pci/lookup_test.go
- pkg/pci/parse.go
- pkg/pci/pci.go
- pkg/pci/pci_linux.go
- pkg/pci/types.go
- Strip unused text from literal pci.ids slice of bytes
- Add NewIDs() function which contains the pci.ids itself, but returns the parsed
map. This is now only done on start of the pci cmd.
- Add a test for Lookup
- Minimize scan() since we can assume more about pci.ids' format
- PCI and Device stringers now return the numeric IDs, because they
don't have a way to get to the ids map now thats its not global.
- Add a Vendor and Device type for the generated lookup map.
- Runtime reduce by ~50%.
- Compressed bb cpio image reduced by 79kB.
Signed-off-by: Ben Allen bensallen@me.com
> pkg/pci, cmd/pci: Parse pci.ids on start and update to use stripped plain text pci.ids

- cmds/archive/toc.go
- cmds/cat/cat_test.go
- cmds/ectool/lpc.go
- cmds/ip/ip.go
- cmds/kill/list_linux.go
- cmds/msr/msr.go
- cmds/mv/mv.go
- cmds/mv/mv_test.go
- cmds/rm/rm_test.go
- cmds/rush/parse.go
- cmds/rush/rush.go
- cmds/which/which.go
- cmds/which/which_test.go
Pull out the value when iterating a range rather than simply iterating
the index and looking up the value in the slice.
Signed-off-by: Alistair Ferguson <ferguson.alistair@gmail.com>
> archive, cat, ectool, ip, kill, msr, mv, rm, rush, which: Tidy ranges

- cmds/rm/rm.go
- cmds/rm/rm_test.go
The force flags disables interactive mode (if enabled) and ignores
errors when trying to delete nonexistent file(s).
This allows to invoke `rm` on multiple files and be sure that they will
all be deleted even if one or more is missing. Suppose we have a folder
`foo/` with files `a` and `c` in there. On `rm foo/a foo/b foo/c` only
`foo/a` will get deleted, because `foo/b` is missing and thus the
command will fail. On `rm -f foo/a foo/b foo/c` on the other hand, the
command will succeed and both `foo/a` and `foo/c` will be deleted.
Fixes #335.
Signed-off-by: Kiril Vladimiroff <kiril@vladimiroff.org>
> cmds/rm: Add force flag

- cmds/shutdown/shutdown.go
shutdown uses the reboot syscall, not kexec.
> cmds/shutdown: fix typo in dryrun help message

- cmds/uname/uname.go
- pkg/uroot/util/uname.go
After PR #454, util.Uname is merely a wrapper around unix.Uname. Make
its only user in cmds/uname use unix.Uname directly and drop the uname
related parts of pkg/uroot/util.
> cmds/uname: use unix.Uname directly

- cmds/mknod/mknod_test.go
- Swap use of user.Current() to syscall.Getuid(). user.Current() from "os/user" ends up using CGO in lookupUnixUid().
Ref: https://golang.org/src/os/user/cgo_lookup_unix.go
Signed-off: Ben Allen <bensallen@me.com>
> cmds/mknod: Remove use of user.Current() which requires CGO

- cmds/dd/dd_test.go
- Stream stdout of from dd via cmd.Stdoutpipe()
- Add compare function and count fields to the table tests struct to allow for two compare functions to be used.
- For tests that check stdout against a sequential set of identical bytes, create func byteCount. Fixes having to allocate large slices to compare stdout against.
- For tests that need string like comparison, create func stdoutEqual, which compares stdout a byte at a time to the input []byte
- Use byte slices instead of strings where possible
- Don't output error messages including all of stdout, use explicit error messages from new functions.
- Move table tests struct inside test function so its no longer global.
- Make each test a sub-test of TestDd via tt.Run(), changing comments around each test into a new name field.
- …
> cmds/dd: Rewrite dd_test to lower memory use

- .circleci/config.yml
- Adds initial CircleCI configuration that mostly replicates travis.sh
- Lowers CI time to ~2:30 min, largely due to CircleCI providing up to 4 runners for OSS projects and easy parallel workflow configuration.
- Capture artifacts (compressed lzma)
- Adds enforcing CGO_ENABLED=0 while running tests
- CircleCI allows you to rerun tests with SSH enabled. I've found this to be quite handy for debugging tests.
- Example: https://circleci.com/gh/bensallen/u-root/
- Goal is to run CircleCI along side of Travis for a week or so to see how it fairs.
- Eventually want to use CircleCI's API to fetch (or just get the file size) the last initrd image from the master branch to compare size against the current build.
> Initial CircleCI Configuration

- cmds/pci/pci.go
- pkg/pci/devices.go
- pkg/pci/ids.go
- pkg/pci/lookup_test.go
- pkg/pci/parse.go
- pkg/pci/pci.go
- pkg/pci/pci_linux.go
To lookup a name, users should not have to be aware of maps. PCI devices
now have a default VendorName/DeviceName that is numeric. To map them to
names, one can call p.SetVendorDeviceName, which also works on []*PCI, i.e.
Devices.
Since no error checking was done on the parse (it should be done at build
time anyway), remove the error return and simplify that logic.
ToString() is no longer needed, so go with String.
This is all in preparation to make it easy to dump config space.
pci: allow user to specify the glob
This may still fail the convenience test, as one could argue you must name
the glob exactly (e.g. 0000:02:00.0) but otoh you can say pci -s *02:00*
and it works. That's not much worse, I guess, than pci -s 0:2.0? Or is it?
Plus pci *18* gets all devices with an 18. So far it's …
> pci pkg/cmd: simplify printing and name lookup

- cmds/kexec/kexec_linux.go
When building in bb mode, flags handled within this FlagSet are ignored. Only flags declared by a call on the flag package are correctly included into the Flagset created by bb.
> Using flag.FlagSet is not compatible with bb mode

- cmds/boot/boot.go
Simplify the partition finding code and allow for partition-free disks
that might have a filesystem and /boot on them. Support a full
dryrun capability.
This set of changes has revealed some issues in the grub parsing code; that's
next.
> boot: changes driven by testing

- cmds/pci/pci.go
- pkg/pci/devices.go
- pkg/pci/pci.go
Back in the day, this pci command would have been incredibly handy.
Suppose you want to dump 16 bits @ 0 and 2, and 32 bits at 4, and 8 bits at 4.
This is device and vendor id, and 32 bits @ 4, and 8 bits of command register.
And you want it for all devices at device 18, a root port.
pci -s *18* 0.w 2.w 4.l 4.b
0000:00:18.0: VMware PCI Express Root Port
00000000:15ad
00000002:07a0
00000004:00100007
00000004:07
0000:00:18.1: VMware PCI Express Root Port
00000000:15ad
00000002:07a0
00000004:00100007
00000004:07
0000:00:18.2: VMware PCI Express Root Port
00000000:15ad
00000002:07a0
00000004:00100007
00000004:07
0000:00:18.3: VMware PCI Express Root Port
00000000:15ad
00000002:07a0
00000004:00100007
00000004:07
0000:00:18.4: VMware PCI Express Root Port
00000000:15ad
00000002:07a0 …
> pci: allow for dumping and setting of config registers

- pkg/uroot/uroot.go
The : syntax lets you do stuff like this:
-files /path/to/prototype/root:etc
It will source from /path/to/prototype/root/etc but
put it into the cpio archive as etc. It's impossible to
live without, I keep learning.
I used SplitN, not Split, as there are valid paths (maybe?)
with : in them. That said, we may find we want a more robust
way to do this.
> uroot package: add : syntax back for extra files

- cmds/cmp/cmp.go
This uses the unit package for the offsets.
While at it, return with an exit code as defined in the man-page, and not 1 from log.Fatal(). 1 is for "different", 2 is for "trouble".
> cmp: use unit package and clean up

- Gopkg.lock
- cmds/cmp/cmp.go
- cmds/dd/dd.go
- vendor/github.com/rck/unit/unit.go
- vendor/github.com/rck/unit/unit_test.go
Just some cleanup that resulted from the previous work on the unit package. At least the GNU tools have this rule, so no need for every command to define it on its own.
> mv 'kB' to default units, switch tools that defined it

- cmds/ping/ping.go
So far "defer" was used in a loop, which keeps fds open till the program
terminates or we run out of fds.
You can watch fd creation without giving them up like this:
watch -n1 sudo ls /proc/`pidof ping`/fd
> ping: fix fd exhaustion

- cmds/echo/echo.go
- cmds/echo/echo_test.go
- roadmap.md
The `echo` command now interprets escaped characters when the `-e`
argument is set.
Signed-off-by: Alistair Ferguson <ferguson.alistair@gmail.com>
> echo: implement -e argument

- pkg/find/find_test.go
This test failed on my Linux install because of a weird umask. Added a setumask(0) and cleaned up the test.
> pkg/find: clean up find tests.

- pkg/uroot/uroot.go
The previous commit b7cae605bd439eeef5c169a6f65819ddae3d6e55 introduced
a regression where using the old syntax (e.g. `-files something.txt`) is
truncating the first character (e.g. the resulting rootfs will contain
"omething.txt"). This diff avoids the truncation when the old syntax is
used.
Tested with multiple combinations:
* `-files something.txt`
* `-files something.txt:whatever.txt`
* `-files something.txt:wat something.txt`
> uroot package: fix: syntax for extra files

- travis.sh
[Travis always sets `$GOPATH` to `/home/travis/gopath`](https://travis-ci.org/y0ssar1an/u-root/jobs/309876685#L441), so we don't need this check.
> Remove $GOPATH check from travis.sh

- cmds/tcz/tcz.go
This fixes NiChrome when we have multiple users and private /tmp mounts.
> tcz: put packages in TinyCorePakcages/tcloop

- cmds/tail/tail.go
- cmds/tail/tail_test.go
- cmds/tail/test_samples/read_backwards.txt
- cmds/tail/test_samples/read_from_beginning.txt
- roadmap.md
Added new command: tail.
This is a very simple implementation, it currently supports only the `-n` (number of lines) option, and
adds the scaffolding for the `-f` (follow) option. It can read from seekable and non-seekable files (e.g.
stdin). If stdin is detected, it will try reading from the beginning instead of reading backwards from the
end.
> cmds/tail: added tail command

- pkg/uroot/binary.go
- pkg/uroot/uroot.go
This is mostly meant to be used for local testing and debugging, e.g. to
compare against source and bb mode correctness.
Signed-off-by: Christopher Koch <c@chrisko.ch>
> pkg/uroot: add new compilation format to just compile binaries.

- pkg/uroot/util/root.go
Removed the override on `/etc/resolv.conf`. This lets users specify their own `resolv.conf`, but it still leaves the default `nameserver 8.8.8.8` that is set in  https://github.com/u-root/u-root/blob/master/pkg/uroot/uroot.go#L29 .
This is the only entry in the namespace that doesn't seem necessary to have there.
* Tested with `go run u-root.go`: the content is "nameserver 8.8.8.8" from `pkg/uroot/uroot.go`
* tested with `go run u-root.go -files /etc/resolv.conf:etc/resolv.conf`: the content is copied from my local machine
The above steps were tested in both `bb` and `source` mode.
> Remove resolv.conf override to allow users to specify their own

- pkg/kmodule/kmodule_linux.go
Summary:
By returning *SyscallError rather than error in some cases it was
always
evaluating as != nil. This change refactors it to use the error
interface.
Test:
Using this code:
https://gist.github.com/claudiozz/5e932b5929eb63f8e2b1d5b2eb43eedc
Before the change:
[root@scw-ffea63 ~]# lsmod | grep ^loop
[root@scw-ffea63 ~]# ./test
2018/01/27 13:24:50 Error is not nil and is SyscallError, value is
<nil>
[root@scw-ffea63 ~]# lsmod | grep ^loop
loop                   19177  1 cryptoloop
After the change:
[root@scw-ffea63 ~]# lsmod | grep loop
[root@scw-ffea63 ~]# ./test
2018/01/27 13:26:37 Success
[root@scw-ffea63 ~]# lsmod | grep ^loop
loop                   19177  1 cryptoloop
>     Fixing errors in kmodule_linux.go

- pkg/kmodule/kmodule_linux.go
Fix module lookup by suffix in kmodule_linux, currently it matches for
moduleName.ko which matches _any_ module ending with that name in the
depMap. In some cases this means random modules are loaded instead of
the correct one.
Before the fix:
$ for i in {1..5}; do ./modprobe_linux -n loop ; done
Unique dependencies in load order, already loaded ones get skipped:
/lib/modules/4.14.0-0.bpo.3-amd64/kernel/drivers/block/loop.ko
Unique dependencies in load order, already loaded ones get skipped:
/lib/modules/4.14.0-0.bpo.3-amd64/kernel/sound/soundcore.ko
/lib/modules/4.14.0-0.bpo.3-amd64/kernel/sound/core/snd.ko
/lib/modules/4.14.0-0.bpo.3-amd64/kernel/sound/core/snd-timer.ko
/lib/modules/4.14.0-0.bpo.3-amd64/kernel/sound/core/snd-pcm.ko …
> kmodule_linux: Fix module lookup

- cmds/wifi/wifi.go
- cmds/wifi/wifi_test.go
Before this commit, when call wifi with no arugments, the goroutine will
panic and give you an error.
Now, when call wifi with no arguments, the flag.Usage() function will get
call and the standard usage message will be printed. This is a more
graceful way of handing this error
Signed-off-by: Thien M. Hoang <thienhoang@google.com>
> Add Error Handling for wifi cmd when called with no arguments

- pkg/uroot/util/root.go
Even though mounts succeeds without a source for proc, devtmpfs, etc, some code that parses /proc/self/mountinfo expects there to be three fields after the "-" separator. Notable libcontainer's mount_linux.go.
Helps with runc testing in #508.
Signed-off by: Ben Allen <bensallen@me.com>
> pkg/uroot/util: Specify a source for each mount

- cmds/rush/rush_test.go
Before: The format of the bad test case was real 0.2\d\d\nuser 0.00\d\nsys 0.00\d\n which assumes that the program will return a result within the 0.200 - 0.299 seconds time range. However, that is not guaranteed.
Now: We only care about the matching format which is \d+.\d{3}. This format does not care about the actual run time, which will prevent any false positive failure.
> Fixed a bad test case in rush_test.go

- cmds/cpio/cpio.go
- pkg/cpio/cpio.go
- pkg/cpio/fs_unix.go
- pkg/cpio/newc.go
- pkg/cpio/newc_test.go
- pkg/cpio/types.go
- pkg/pxe/schemes.go
- pkg/uio/cached.go
- pkg/uio/cached_test.go
- pkg/uio/lazy.go
- pkg/uio/lazy_test.go
- pkg/uio/reader.go
- pkg/uroot/cpio.go
- pkg/uroot/files_test.go
io.Reader only allows you to read the record once; and there's no point
in reading it from a bytes.buffer into a bytes.Buffer just to be able to
read it multiple times. So, we go with io.ReaderAt.
making these improvements to improve netboot stuff, so i can hand off to samee.
> various cpio improvements

- cmds/cp/cp.go
The code would not correctly handle the case of an errors
that was not ENOENT. Fuse can deliver some very strange
errors and we would end up with a segv.
> cp: fix incorrect handling of error on Stat of dst

- cmds/ps/ps_linux.go
We were testing for ErrNotExist but some kernels return
no such process
which led to occasional test failures.
> ps: fix the case when the stat file goes away

- cmds/wifi/wifi.go
- cmds/wifi/wifiCommsUtils.go
- cmds/wifi/wifiServer.go
- cmds/wifi/wifi_test.go
* As a proof of concept, write an http server that will start when wifi cmd is run, thus allowing user to interact with the cmd over a RESTful interface.
* Since this is a proof of concept at the moment, stub data is used to prove that the concept works. 
* Test cases have been written and manual tests have been carried out to ensure backward compatability with previous version of wifi cmd.
> (Experimental) Make wifi cmd RESTful

- cmds/wifi/iwlistStubOutput.txt
- cmds/wifi/wifi.go
- cmds/wifi/wifiCommsUtils.go
- cmds/wifi/wifiServer.go
- cmds/wifi/wifiServer_test.go
- cmds/wifi/wifi_test.go
Majority of this PR are test cases in `wifi_test.go` and a big `.txt` file to emulate the output of iwlist.
The **main new logic** of this PR is in the `parseIwlistOut(o []byte)` function in `wifi.go`
> Implement the functionality to see a list of nearby WiFi and their authorization protocols in to wifi cmd and its server

- cmds/wifi/wifi.go
- cmds/wifi/wifiCommsUtils.go
- cmds/wifi/wifiServer.go
2+ browser tabs will encounter the following problems:
- If they all press Refresh at the same time, then only 1 of them can go through, the other ones are going to fail due to that one going through hogging the up the WiFi scanning resources.
- If a tap updates its state after the refresh, nothing about this update is reflected on the other tabs. That is, there will be some inconsistencies between the tabs.
However, for a one-user system, there aren't any use cases where a user needs more than 1 tab to connect to the WiFi. If he/she is not most up to date to the state of the server, they can just hit Refresh.
> (Experimental) Support Wifi Scanning from 1 browser tab

- README.md
The kernel has some restrictions to decompress xz files. See
Documentation/xz.txt.
As initramfs.xz is embedded in the firmware file for Linuxboot
it is highly suggested to follow this recommendation
Signed-off-by: Francois-Frederic Ozog <ff@ozog.com>
> doc: added xz compression notes so that kernel can decompress.

- cmds/ps/ps_linux.go
I debated just having it print nothing but that's kinda
counterintuitive.
Testing this would add another test that requires we run as root.
Maybe we should anyway.
> ps: fix bug when /proc is not mounted

- cmds/losetup/losetup.go
- cmds/mount/mount.go
- pkg/loop/losetup_linux.go
Summary:
Split losetup in binary/library to manage loop devices
Fix losetup to use RDWR when possible and use library
Fix options in mount
Add loop option in mount
Former pull request: https://github.com/u-root/u-root/pull/575
> Fix losetup / mount

- cmds/ip/ip.go
Provide the ability for u-root to modify the hardware (mac) address.
Follows the same structure as other 'ip link set' commands.
usage:
~/> ip link set eth1 address 00:00:00:02:01:01
results:
~/> ip link show
3: eth1: <UP,BROADCAST,MULTICAST> mtu 1500 state UP
link/ether 00:00:00:00:00:01
error reporting:
~/> ip link set eth1 address 00:00:00:02:01:0h
ip: &{{3 1500 1000 eth1 00:00:00:02:01:01 up|broadcast|multicast
69699 0 0 <nil>  0xc42017c0e4 0 0xc420016680 ether <nil> up 0 0 0}}
cant parse mac addr : address 00:00:00:02:01:0h: invalid MAC address
> cmds/ip: add ip link set (hardware) address

- cmds/sshd/sshd.go
sshd didn't use to check err when calling pty.New()
Added in an error and return in that case.
> Fixing ssh pty error

- .gitignore
- Gopkg.lock
- cmds/init/init.go
- cmds/rush/rush.go
- pkg/bb/cmd/main.go
- pkg/bb/register.go
- pkg/uroot/bb.go
- pkg/uroot/bb_test.go
- pkg/uroot/uroot.go
- tools/makebb/.gitignore
- tools/makebb/makebb.go
So far, you are forced to use rush and forced to use init as compiled into bb by default.
This will allow users to include a custom init and a custom default shell in bb mode. You can also choose not to include an init and not to include a shell in bb: init and rush are just two other normal bb programs.
This will also allow users to eventually write commands directly targeted at bb, by using a bb command that Registers them manually:
```go
bb.Register("my-own-command", func() {
log.Printf("init stuff")
}, func() {
log.Printf("main stuff")
})
```
rush and init both are just another command compiled into bb mode. No reason to be special.
> De-couple bb mode from init and rush. Add standalone makebb tool.

- u-root.go
A template is a name that expands to more names.
It is defined in a map in the u-root command as a
map[string][]string
So you might, for example, define
"facebook": "/bin/ed"
you can use more than one template, and they can be freely
mixed with real names:
./u-root facebook cmds/wifi
If there are duplicates that is not a problem.
> u-root: Add templates

- cmds/wifi/server.go
- cmds/wifi/server_test.go
- cmds/wifi/service.go
- cmds/wifi/service_test.go
- cmds/wifi/wifi.go
- pkg/wifi/iwl.go
- pkg/wifi/iwl_test.go
- pkg/wifi/native.go
- pkg/wifi/native_test.go
- pkg/wifi/stub.go
- pkg/wifi/types.go
- pkg/wifi/wireless.go
This is to enable a native linux wifi capability.
pkg: mv wifi to iwl (intel wireless lan)
pkg: remove repeated use of the word wifi in names where it stutters
pkg: all Wifi becomes WiFi (wireless fidelity is kind of a silly name but ...)
pkg: move common types to types.go
pkg: interface methods should have pointer receivers
pkg: Create wireless.go from the .h
cmd: update for these changes
> wifi: set up for native support, and clean up

- cmds/chmod/chmod_test.go
- cmds/comm/comm_test.go
- cmds/dd/dd_test.go
- cmds/dhclient/dhclient_test.go
- cmds/dirname/dirname_test.go
- cmds/false/false_test.go
- cmds/fmap/fmap_test.go
- cmds/grep/grep_test.go
- cmds/hexdump/hexdump_test.go
- cmds/id/id_test.go
- cmds/kill/kill_test.go
- cmds/ls/ls_test.go
- cmds/mkdir/mkdir_test.go
- cmds/mkfifo/mkfifo_test.go
- cmds/mknod/mknod_test.go
- cmds/readlink/readlink_test.go
- cmds/rush/rush_test.go
- cmds/sort/sort_test.go
- cmds/truncate/truncate_test.go
- cmds/uniq/uniq_test.go
- cmds/validate/validate_test.go
- cmds/wc/wc_test.go
- cmds/wget/wget_test.go
- pkg/testutil/testutil.go
This implements @rjoleary's suggestion from #721.
Eliminates the use of the go compiler in all tests. This makes u-root build-system-independent.
> Eliminate go compiler in tests

- cmds/modprobe/modprobe_linux.go
Using modprobe with the -a flag will parse all arguments as module names, rather than as one module with multiple parameters.
-va is an alias to -a.
Updates #712
> Add -a option to modprobe command.

- pkg/uroot/bb.go
- pkg/uroot/bb_test.go
- pkg/uroot/binary.go
- pkg/uroot/source.go
- pkg/uroot/uroot.go
- u-root.go
@rminnich only allowed by the package right now -- what do you want the command-line API to look like?
Eventually, NiChrome should vendor in u-root and use the package rather than the command-line tool anyway.
Signed-off-by: Christopher Koch <c@chrisko.ch>
> pkg/uroot: allow mixed build modes in package API.

- pkg/kmodule/kmodule_linux.go
Since different kernels from different distributions expect kernel modules to be in slightly different paths (depending on whether /usr has been merged) check in both paths.
> Check both /lib/modules and /usr/lib/modules

- cmds/init/init.go
Environment has to be set in main() not via an initializer,
possibly due to something in the os package.
> init: fix environment handling

- pkg/golang/build.go
- pkg/uroot/bb.go
- pkg/uroot/cpio.go
- pkg/uroot/uroot.go
- tools/.gitignore
- tools/makebb/makebb.go
- tools/makebbmain/main.go
- tools/mkinitramfs/main.go
- tools/rewriteast/main.go
This is not intended to replace the u-root utility. It refactors some of pkg/uroot such that most of the standalone utilities are just single function calls.
>  pkg/uroot & tools: add standalone build tools to facilitate bazel/buck rules.

- cmds/upspin/server.go
- cmds/upspin/upspin.go
Add an SoS server skeleton for Upspin integration in the future. These changes are for development of the [NiChrome project](https://github.com/u-root/NiChrome).
Upspin: https://upspin.io
Service of Services (SoS): u-root/cmds/sos, u-root/pkg/sos
Signed-off-by: Trevor Farrelly <trevorfarrelly@google.com>
> Add basic Upspin frontend for future SoS integration

- cmds/wifi/server.go
- pkg/sos/server.go
- pkg/sos/server_test.go
Also, add a switch, soshtml, so that on tests, one
can use a different root for finding html.
Hence any command using this package can be invoked with
a different root, e.g.
wifi -soshtml ~/go/src/github.com/u*/u*/pkg/sos/html
> sos: add HTMLPath function; remove /etc/sos/html hardcodes

- cmds/upspin_sos/server.go
- cmds/upspin_sos/service.go
- cmds/upspin_sos/upspin_sos.go
Writes entered config data to $HOME/upspin/config, and calls `upspin keygen` with the entered seed, writing keys to $HOME/.ssh/yourusername@email.com.
> Implements Upspin service backend

- cmds/upspin_sos/service.go
`upspin keygen` does not work if generated keys already exist, you need to run it with the `-rotate` flag to replace them. This adds this functionality to the Upspin SoS service.
> allow rotating upspin keys from SoS page

- cmds/rm/rm.go
- cmds/rm/rm_test.go
this is not very nice, but -rf is just about the most common
option in scripts.
Really, we probably should do the "all the permutations" code but,
really, we probably ought to get argument parsing people expect,
and that's not how Go does it.
> rm: implement -rf

- pkg/bb/cmd/main.go
- pkg/bb/register.go
- pkg/uroot/bb.go
- pkg/uroot/bb_test.go
This way, we don't have to make the Go toolchain guess what imports may
be missing, and we only rewrite statements within each file.
> pkg/uroot/bb: avoid having to fix import statements.

- pkg/sos/html/upspin.html
This addresses u-root/NiChrome issue #105.
> Fix Upspin SoS tab name

- cmds/cat/cat.go
Subtle bug prevented using arguments on cat. For example, the following
did not print "hi":
echo "hi" | cat -u
> cat: Fix arg counting

- cmds/strings/strings.go
`strings` now works well with large (or infinite) files which are completely printable. For example:
cat /dev/zero | tr "\0" a | ./strings | pv > /dev/null
Performance:
GNU binutils: 119MiB/s
u-root:       94.9MiB/s
> strings: Simplify and make responsive

- .circleci/config.yml
This will ensure that required packages are checked in and there is no diff in vendor after running dep ensure. The checks before this should check if `Gopkg.toml` has been updated based on what is in the code.
Resolves https://github.com/u-root/u-root/issues/813
> Run dep ensure -vendor-only in CI

- pkg/uroot/bb.go
Necessary for bazel/buck/blaze skylark busybox rules, since the name of "go_binary" rules is determined by what's in the BUILD file. It'll be passed via flag from Skylark.
> pkg/uroot/bb: allow defining package name.

- cmds/srvfiles/srvfiles.go
This will strip any caching headers from the client (probably a browser in this case) and have the server always serve the file/directory. Caching is hard and this would have the downside of always serving up a static file which may have not changed. 
I tested that this works with the test case outlined by @rjoleary in https://github.com/u-root/u-root/issues/808 .
> Do not serve cached index

- pkg/uroot/uroot.go
Fixes #857.
Based on a change from Christopher Koch <chrisko@google.com>.
Signed-off-by: David Disseldorp <ddiss@suse.de>
> pkg/uroot: ignore empty extra files arguments

- pkg/uroot/util/root.go
We need them for other things anyway.
This necessitated changes to termios, and pty
code, but it was all broken anyay.
We include the testramfs.go program as an example
of both interactive and scripted usage. You can now
script a ramfs running in a container with
private name spaces.
stty command is now considerably simpler.
> Move stty support functions to termios

- cmds/switch_root/switch_root.go
Follow up for commit cc9ad413aab2, where unix.Exec was not there yet.
> cmds/switch_root: complete switch from syscall to x/sys/unix

- cmds/init/init.go
We now have the defaultsh symlink
so just use that.
I'm not a real fan of this symlink magic, because it always
starts with one symlink and ends up here:
(google etc alternatives)
So if we could do something else I could worry less. 
But, assuming it's here to stay, and a correctly formed u-root
/ always has defaultsh, then we might as well just try to run
that one thing. 
All these choices are making testramfs a pain.
> Remove all the shell attempts from init

- pkg/uroot/source.go
A goal of source mode images is that they be able to recreate themselves.
Leave the installcommand source in the image so this capability
is not impossible (although it may have stopped working, no need to
make it worse).
> Keep installcommand source in source mode

- cmds/installcommand/installcommand.go
- pkg/uroot/uroot.go
The creation of /tmp in the first program goes back
a long way, and now that we have a cpio which is the template
for /, we should put the /tmp in there.
Also, the mode needs to be 777 now.
> tmp: create the /tmp in the cpio, not the installcommand

- pkg/uroot/util/root.go
Before setting up a root file system, set umask
to 0 and restore it when done. This is essential
for any environment in which "not UID 0" will be
used.
Fixes NiChrome 0.
> root file system create: setup with empty umask

- Gopkg.toml
We do not need the google/uuid package anymore.
> dep: Remove extraneous warning

- pkg/loop/loop.go
- pkg/loop/loop_linux.go
- pkg/mount/mount.go
- pkg/mount/mount_linux.go
- xcmds/pox/pox.go
- xcmds/pox/pox_test.go
A portable executable is a squashfs containing a set of files,
.so's, and anything else you want to bring along. It is inspired
by tinycore packages and appimage. While appimages and
tinycore packages are a bit involved to build, pex makes
it easy.
Why we're doing this: we've had a lot of trouble bringing along binaries due to
shared library issues. For example, if we build the cgpt tool from chromeos
static, on debian, it core dumps. GNU and glibc are no longer friendly to
static linking.
pex is a program that builds portable executables that look like
tinycore tczs.
For example, we might want some random programs such as
/usr/bin/minicom and a few files such as /etc/minicom.d.
We can say this:
pex /usr/bin/minicom /etc/minicom.d
The command, its .so dependencies, and /etc/minicom.d
will …
> pox: POrtable eXecutables

- .circleci/config.yml
- Gopkg.lock
This updates the CI to the latest release of dep (v0.5.0). When running `dep ensure` locally, it is important to use the latest release of dep (not whatever is on the master branch) to avoid unexpected breakages. To get the latest release:
( cd ${GOPATH-$HOME/go}/src/github.com/golang/dep && git fetch && git checkout v0.5.0 && ./install.sh ) && dep version
> Bump dep version

- cmds/scp/scp.go
- cmds/scp/scp_test.go
Add protocol test for sink and source scp.
SCP sink failed to exit gracefully, which is now fixed.
> scp: fix sink and add tests

- cmds/ip/ops.go
Fixes https://github.com/u-root/u-root/issues/931
```
$ ./ip a
1: lo: <UP,LOOPBACK> mtu 65536 state UNKNOWN
link/loopback 
inet 127.0.0.1 scope host lo
valid_lft forever preferred_lft forever
inet6 ::1 scope host 
valid_lft forever preferred_lft forever
2: wlp2s0: <UP,BROADCAST,MULTICAST> mtu 1500 state UP
link/ether 00:fa:ce:b0:0c:00
inet 172.16.x.y brd 172.16.3.255 scope global wlp2s0
valid_lft 6545sec preferred_lft 6545sec
inet6 2620:[snip] scope global 
valid_lft 603248sec preferred_lft 84510sec
```
> cmds/ip: fix output for addr subcommand

- cmds/more/more.go
Admittedly, this does not follow the conventions of GNU more. Instead,
it is built with the goal of not relying on any special ttys, ioctls or
special ANSI escapes. This is ideal when your terminal is already
borked. For something with more features, look at less.
> more command

- cmds/scp/scp.go
- cmds/scp/scp_test.go
Return only base name to be compliant with openssh's scp.
Signed-off-by: Christian Svensson <bluecmd@google.com>
> scp should not return absolute path names

- cmds/rsdp/rsdp.go
- cmds/rsdp/rsdp_test.go
includes work from jean-marie:
Fix rsdp with Go 1.11, and imply early exit of kmesg read if RSDP pointer value
is found. This is a mandatory patch to make work Ubuntu 16.04 installer
booting on Winterfell node, otherwise the installer kernel is unable to properly
detect IRQ mapping
The trick to making this work is to open a unix fd with O_NONBLOCK
and open an os.File with that fd. Then all the messiness
goes away.
> redo rsdp and remove unneeded goroutine; add a test

- scripts/checklicenses/checklicenses.go
Some code imported from, e.g., gvisor, has a
different license and that needs to remain unchanged.
We now support an array of re's for the license check.
> checklicenses: allow for more than one license regexp

- pkg/kexecbin/kexecbin.go
The package kexecbin calls by default the command `kexec`. It uses the syntax of the `kexec` implementation of `kexec-tools`. However u-root already implements a simpler `kexec` command with different command line arguments. To avoid ambiguity, I propose that KexecBin calls a binary with a different name.
The user who creates the ramfs will have to bundle `kexecbin` instead of `kexec`. This would also avoid accidental overwrites of u-root's kexec.
> KexecBin to call non-ambiguous kexecbin command

- pkg/strace/epsocket.go
- pkg/strace/socket.go
So now, for example, with
telnet localhost 2448
you see things like
telnet(18797) E connect(0x3, 0x55efe8c7a1f0 {Family: AF_INET, Addr: 0x7f000001, Port: 2448}, 0x10)
telnet(18797) X connect(0x3, 0x55efe8c7a1f0 {Family: AF_INET, Addr: 0x7f000001, Port: 2448}, 0x10) = {0xffffffffffffff91} (452.745µs)
It's not complete but it's better. And you can see how long it wasted on that connect :-)
> Add printing for network operations

- pkg/uroot/initramfs/files.go
This change broke nichrome. Also, there's a lot of software
in various places that depends on things being symbolic links,
so following them can cause a different issue than this problem
fixed. We're going to need to figure out another way to solve
the problem.
This reverts commit 8ebf81a3bb98549c3c14b65068deacc3528a36ed.
> Revert "initramfs: now that we follow symlinks, don't lstat."

- pkg/uroot/builder/bb/bb.go
- tools/makebbmain/main.go
In the standard Go toolchain, a packages' files are all in the same
directory.
In the blaze/bazel/buck world, a packages' Go files may be spread across
different directories.
> bb: allow packages with files in multiple directories.

- pkg/uroot/builder/builder.go
- pkg/uroot/builder/source.go
- pkg/uroot/uroot.go
- u-root.go
In our never ending quest to shrink the images, no matter what
it takes, this PR shows how we might do so.
The idea is to drop a file, zzzzinit.go, into go/src/cmd/build,
which is
1) the last init function run, and
2) the init function.
The function looks at os.Args[0] and, if it is /init, proceeds
to build installcommand, then runs /ubin/init, which gets built
and is then run.
So the go command is now init, with special behavior when it is
called as such.
The zzzzinit.go is not placed in the command directory unless
GOROOT is set, and the file does not already exist. It is removed
once u-root is run. If you run two u-root's at the same time one will fail.
Results:
With compiling installcommand on boot, it's dramatically slower, 13 seconds
vs 5 seconds
but it's also 35M vs 37.5M
And note …
> gang of four: allow u-root to start with 4 binaries not 5

- .circleci/config.yml
- u-root.go
It is possible to have an initramfs for "hosted" mode, i.e. a
mode in which u-root is installed onto an existing system
such as a chromebook.
In that case we should not create defaultsh and init symlinks,
or try to populate /dev, /usr, /lib, and so on.
This works today with the right commandline usage:
go run u-root.go -base=/dev/null -defaultsh="" -initcmd=""
Add a bit more cmdline documentation for 'hosted' mode,
and add two tests to make sure nobody breaks it by accident
in the future. NiChrome will be using this mode.
Kind of cool: I did not know this would even work but the command
needed no changes.
> Add comments for hosted mode; add tests to ensure it keeps working

- .circleci/config.yml
This test ensures we handle aspects of symlinks correctly.
The first test makes sure we DO NOT follow symlinks from -files <dir>.
Hopefully, as more symlink issues are found and fixed, we can grow
this regression test.
> Add symlink regression test

- cmds/lddfiles/lddfiles.go
- pkg/ldd/ldd_unix.go
On many linux systems, /bin/xyz can be a link to, e.g.,
/etc/alternatives/xyz, and from the to /bin/someotherthing.
We considered the following:
if /bin/xxx is a link to /etc/alternatives/xxx, and then to /bin/zzz,
create /bin/xxx as a file, contents /bin/zzz
The problem is that it can often by extremely useful to see the
alternatives structure:
/bin/nc -> /etc/alternatives/nc -> /bin/nc.openbsd
so you know which nc you're getting (in this case the openbds version).
It seems easy to produce this information and it is useful,
so we now produce output like this:
/lib/x86_64-linux-gnu/ld-2.27.so
/lib64/ld-linux-x86-64.so.2
/lib/x86_64-linux-gnu/librt.so.1
/lib/x86_64-linux-gnu/librt-2.27.so
/lib/x86_64-linux-gnu/libpthread.so.0
/lib/x86_64-linux-gnu/libbsd.so.0 …
> ldd package: also follow symlinks for the commands

- pkg/uroot/initramfs/files.go
- pkg/uroot/initramfs/files_test.go
- pkg/uroot/uroot.go
We've had issues with some build systems using symlinks.
Further, some distros drop extraneous symlinks into the
Go source tree.
Change u-root behavior as follows:
for /go and /bbin and friends, always follow symlinks.
There should never be symlinks in those trees anyway.
For -files, do not follow symlinks. Following symlinks
causes really problematical behavior that's not always obvius.
> symlinks: handle them differently for -files commands

- pkg/uroot/uroot.go
We recently changed lddfiles to return all the files, including
the source. This is arguably far more convenient for lddfiles
package users but caused a problem for uroot.
This change resolves the problem: when we're adding files
from ldd, we don't add the file we ran ldd on, since we
previously added it anyway.
Hence, if we do something like this:
go run u-root.go -build=bb -files /bin/date:d -files /etc/hosts:h
the right set of files is added, as well as the right set of libraries.
> pkg/uroot: fix the -files rename case

- cmds/ps/ps.go
- cmds/ps/ps_linux.go
- cmds/ps/ps_test.go
Suppose you have a lot of hosts' /proc mounted in /tmp/netproc/*
You would do this
UROOT_PSPATH=/proc:/tmp/netproc/* ps aux | grep dnsmasq
You see:
PID     PGRP      SID TTY             STAT         TIME  COMMAND
a22/1996     1995     1995 ?               S        00:00:00  dnsmasq
2069     2068     2068 ?               S        00:00:00  dnsmasq
you might even export UROOT_PSPATH so you always see what you want to see.
The path can have more than 2 elements, of course. The code assumes the first
path element is the local one.
> ps: additional paths now work

- pkg/uroot/builder/source.go
- pkg/uroot/uroot_test.go
For hosted mode on a chromebook turns out we need to allow
relative symlinks in buildbin. The links are now, e.g.,
/buildbin/cat -> installcommand
instead of
/buildbin/cat -> /buildbin/installcommand
This seems to work, save I can not create relative link
for defaultsh, i.e.
/bin/defaultsh -> ../buildbin/elvish
fails. That fix can come later I guess.
How I miss plan 9 union mounts. None of this nonsense would be
needed.
> u-root: create relative links, not absolute

- cmds/init/init.go
- cmds/installcommand/installcommand.go
- pkg/uroot/uroot.go
- pkg/uroot/uroot_test.go
- pkg/uroot/util/urootpath.go
- pkg/uroot/util/urootpath_test.go
installcommand now honors UROOT_ROOT. If UROOT_ROOT is set, then
variables such as GOROOT, GOPATH, and others needed by u-root,
will have UROOT_ROOT prepended.
pkg/uroot/uroot.go now creates init as a relative symlink, i.e.
it points to buildbin/init, not /buildbin/init.
To test this I do this:
go run u-root.go # build a dynamic u-root
mv /tmp/initramfs.linux_amd64.cpio /tmp/initramfs.linux_amd64.cpio.dynamic
go run u-root.go  -build=bb -files /tmp/initramfs.linux_amd64.cpio.dynamic:i.cpio -files /bin/bash # build a static u-root with the dynamic one inside it
sudo ./testramfs -i /tmp/initramfs.linux_amd64.cpio
bash-4.4# export UROOT_ROOT=/usr/local # we are now in the static u-root
bash-4.4# mkdir /usr/local
bash-4.4# cd /usr/local
bash-4.4# cpio i < /i.cpio
bash-4.4# ./init # Yep, run …
> rel paths: make installcommand use UROOT_ROOT, /init -> rel symlink

- cmds/tac/tac.go
tac reads file[s] and returns the lines in reverse order.
Note that we can't use stdin, since there is no end condition.
This is a bit silly save it demonstrates creating a new desired
interface from two existing ones.
> tac: backwards cat

- cmds/tcz/tcz.go
This reverts commit f21adf3c4d9e32f041107830123591320714925d.
The cleanup is very good but something is not working with multiple mounts.
So we'll need to bring it in more gradually.
> Revert "tcz: cleanup."

- cmds/init/init.go
- pkg/bb/cmd/main.go
- pkg/uroot/uroot.go
- pkg/uroot/uroot_test.go
The defaultsh link is a problem for things like sshd as it is so non-standard.
/bin/sh is a symlink now on everything and we might as well use that convention.
bb mode will now deal with any number of symlinks.
> Add a /bin/sh link to elvish for busybox mode

- cmds/grep/grep.go
If -c is set, only counts will be printed.
TODO: tests.
> grep: add -c switch

- cmds/uname/uname.go
chipsec uses this.
It has the same value as -m on x86_64. I'm not sure how you get it
on other systems.
> uname: add -p switch

- cmds/kexec/kexec_linux.go
- integration/multiboot_test.go
Use absolute path of the running bb binary
to extract trampoline.
> multiboot: Use absolute path of the running bb binary to extract trampoline.

- pkg/bb/cmd/main.go
Python and other programs do things like this:
sh -c "echo hi"
what you see as an error is that the command
echo hi
does not exist.
What's going on here?
It's a few steps.
When elvish runs /bin/sh, it calls exec ad the child gets argv like this:
["/bin/sh" "-c" "echo hi"]
That child is bb and from this name it needs to figure out which u-root command to run.
But sh is not a u-root command; it's a symlink to a u-root command.
bb looks at filepath.Base("/bin/sh"), fails to find sh, and runs the default handler.
The default handler attempts to do something reasonable with os.Args.
When the default handler sees len(os.Args) > 1, it calls run with with os.Args[1:]
so the sequence is this:
/bin/sh -c "echo hi"
calls run with
-c "echo hi"
and since that is 2 args and -c is not found then it …
> bb: fix issues when the command is not a direct symlink to bb

- xcmds/sshd/sshd.go
Because we pass the ssh command to a sh as a -c style
string we need to merge the args into one command.
> xcmds/sshd: fix multiple args

- pkg/bb/cmd/main.go
This fixes cases where there is a direct link to /bbin/bb,
e.g.
/init -> /bbin/bb
> bb: check filepath.Base of Args[0]

- xcmds/sshd/sshd.go
Right now it only takes one key, but it's not clear we want
more. We might in figure glob /etc/ssh for keys and add them
all. It just doesn't seem necessary.
This gets rid of all warnings from ssh to this daemon.
> xcmds/sshd: add support for host keys

- cmds/date/date_test.go
- cmds/df/df.go
- cmds/pci/pci.go
- cmds/rm/rm_test.go
- cmds/which/which_test.go
- pkg/pci/lookup_test.go
- scripts/checklicenses/checklicenses.go
This is so they do not get mixed in with the godoc.
> Require a blank line after the license

- integration/tcz_test.go
- xcmds/cpu/cpu.go
- xcmds/cpu/doc.go
CPU is an ssh client that starts up a shell on a remote machine,
as usual; but, further, makes a namespace of the local machine
available in a private mount rooted at /tmp/cpu on the remote.
On the remote machine, you can access your local files with
cp, moving things back and forth, running binaries, and
so on.
Whereever you go, there your files are.
> add plan9 style cpu command

- cmds/dhclient/dhclient.go
change 1: change "%d" to "%s" for time print stmt
change 2: append newline at end of final print stmt
outcomes:
before: link "eth1" still down after 30000000000 seconds
after: link "eth1" still down after 30s
before: 3 dhclient attempts were sent%
after: 3 dhclient attempts were sent
Signed-off-by: Lincoln Thurlow <lincoln@isi.edu>
> dhclient: printf formatting changes

- pkg/kmodule/kmodule_linux.go
- pkg/kmodule/kmodule_linux_test.go
The current implementation of Probe tries to load the module first
without checking if it's loaded or if it has dependencies to load first.
In the case of trying to load a module that has dependencies, this
fails by design and the returned error is used to properly load the
module.
This patch introduces parsing /proc/modules to find loaded modules and
removes the logic of special error handling.
Signed-off-by: Nikolas Sepos <nikolas.sepos@gmail.com>
> Avoid error when probing module

- pkg/bb/cmd/main.go
The logic of resolving symlinks until we encounter "bb" introduced in
aaa8821 also broke a use cases when the
binary generated with makebb is not named "bb" after all. This can be
easily acheved by calling makebb with -o switch.
```
$ go build
$ ./makebb -o test ../../cmds/{ls,df}
$ ln -s test ls
lrwxrwxrwx 1 lsiudut lsiudut       4 Jan 30 11:18 ls -> test
-rwxr-xr-x 1 lsiudut lsiudut 8929697 Jan 30 11:14 makebb
-rw-r--r-- 1 lsiudut lsiudut    1112 Jan 30 11:12 makebb.go
-rwxr-xr-x 1 lsiudut lsiudut 2290720 Jan 30 11:18 test
$ ./ls
2019/01/30 11:18:10 os.Args is [test]: you need to specify which command to invoke.
```
I propose to check if resolved path is a symlink and continue traversal if it is. If
not - assume that this is our final bb binary.
This is repost of PR 1115 which went into …
> [bb] check if symlink instead of whether resolved filename is "bb"

- pkg/kmodule/kmodule_linux.go
Unconditionally parsing /proc/modules for preloaded (and subsequently
skipped) kernel modules breaks use-cases where DryRunCB is used for
kernel module dependency gathering.
Add a new ProbeOpts.IgnoreProcMods parameter, which allows the caller to
explicitly disable this behaviour.
Signed-off-by: David Disseldorp <ddiss@suse.de>
> kmodule_linux: add ProbeOpts.IgnoreProcMods parameter

- pkg/bb/cmd/main.go
- pkg/bb/cmd/symlink_test.go
fixes:
- use `lstat` instead of `stat`, none of them were ever coming up as symlinks
- resolve symlinks correctly if they are relative
> bb: fix symlink resolution.

- pkg/strace/epsocket.go
- pkg/strace/socket.go
This validation can never fail. This code looks to have been copied from
github.com/google/gvisor without much consideration.
> Remove nonsense function argument

- pkg/kexec/memory_linux.go
- pkg/kexec/memory_linux_test.go
- pkg/multiboot/multiboot.go
modified kexec RangeType consts and multiboot rageTypes map for compatibity
with e280 memory mep.
modified kexec RangeType consts and multiboot rageTypes map for compatibity
with e280 memory map. Ranges found as "ACPI Non-volatile Storage" at firmware
memory map, needs to be mapped to type 4 in multiboot in order to work
properly with e820.
Changes are still compliant with multiboot spec.
> kexec/multiboot: fix memory mapping

- cmds/dhclient/dhclient.go
- cmds/pxeboot/pxeboot.go
- integration/dhclient_test.go
- pkg/dhclient/dhclient.go
- pkg/dhclient/dhcp4.go
- pkg/dhclient/dhcp6.go
- pkg/pxe/pxe.go
- pkg/qemu/devices.go
This commit updates pxeboot to fire DHCP requests on IPv4 and IPv6 in
parallel. The first response response will be use as DHCP configuration
and the other will be discarded.
Signed-off-by: Luis Alberto Herrera <luisalberto@google.com>
> Add support for pxeboot to get DHCP configuration on IPv6.

- pkg/qemu/devices.go
QEMU in CircleCI seems to in solve cases fail when using just ':1234' format.
It fails with "address resolution failed for :1234: Name or service not known"
hinting that this is somehow related to DNS resolution. To work around this,
we explicitly bind to 127.0.0.1 (IPv6 [::1] is not parsed correctly by QEMU).
> qemu: Bind to 127.0.0.1 explicitly

- pkg/uroot/util/root.go
securityfs is needed for among other things AppArmor.
Try to mount it on startup.
> uroot: Mount securityfs

- cmds/dmesg/dmesg_test.go
Kind of sucks, because only CircleCI requires root access for that. Oh
well.
> dmesg: require root for test. fixes #1160

- cmds/kexec/kexec_linux.go
- pkg/kexec/memory_linux.go
- pkg/multiboot/multiboot.go
- pkg/multiboot/multiboot_test.go
In some cases we want to extend the ACPI tables with more.
This change adds a -a switch to kexec, which allows one to add
a single table. For now that is all we need; if we want more we
change the operation later, once we are sure this is the usage
mode we need.
Note that due to Linux limitations, the -a switch only
works with multiboot kernels.
This is tested and seems to work with our toy multiboot kernel.
> kexec: add support for adding more ACPI tables

- pkg/acpi/ibft.go
- pkg/multiboot/multiboot.go
For esxiboot or other programs that will create a Tabler,
we need a function to take a tabler, not a pathname.
Another nice result is that we can now add any number of tables
to the ACPI table for multiboot. We can even add 0 tables and just
force a remarshaling if we so desire.
> multiboot: add ACPITable function

- cmds/cpio/cpio.go
- pkg/cpio/fs_unix.go
- pkg/uroot/initramfs/files.go
Make CPIO record writer inode counter into its own object to ensure that
the inode cache is flushed between cpio creations.
Fixes #1171
> cpio: Limit inode cache lifetime

- cmds/pxeboot/pxeboot.go
Without this print, the ipxe error is inaccessible which makes debugging
difficult.
> Print ipxe error message

- .circleci/config.yml
The circleci UI makes you click through each sub-directory to get to the
serial output. By copying it to /serial, it's now just one click.
This also reduces the redundancy in the circleci config by using the
inheritance feature of yaml.
> circleci: Copy serial output to /serial

- integration/integration.go
- integration/testcmd/kexec/uinit/kexec.go
- integration/testdata/pxe/pxelinux.cfg/default
Calling it a bzImage is confusing for non-x86 platforms.
> integration: Rename bzImage to kernel

- pkg/uroot/util/root_linux.go
- pkg/uroot/util/root_linux_test.go
- xcmds/cpu/cpu.go
- xcmds/cpu/doc.go
- xcmds/cpu/init.go
cpu will do init-like things if it is run as pid 1, or the optional -init flag is supplied.
Building and testing with qemu:
```
go run . -build=bb -files ssh_host_rsa_key:etc/ssh/ssh_host_rsa_key -initcmd=/bbin/cpu -files ~/.ssh/cpu_rsa.pub:key.pub all github.com/u-root/u-root/xcmds/cpu
sudo /usr/bin/qemu-system-x86_64 -kernel \
/home/rminnich/projects/linuxboot/linux/arch/x86/boot/bzImage \
-cpu  max \
-s   \
-m 1024m \
-machine q35  \
-initrd /tmp/initramfs.linux_amd64.cpio \
-object rng-random,filename=/dev/urandom,id=rng0 \
-device virtio-rng-pci,rng=rng0 \
-device e1000,netdev=n1 \
-netdev user,id=n1,hostfwd=tcp:127.0.0.1:23-:2222,net=192.168.1.0/24,host=192.168.1.1 \
-serial stdio  \
-append earlyprintk=ttyS0,115200\ console=ttyS0 \
-monitor /dev/null  \
```
Choosing what and how to …
> cpu: run as init

- pkg/uroot/initramfs/files.go
- pkg/uroot/initramfs/files_test.go
- uroot_test.go
u-root will not create archives with absolute paths in them.
It's too dangerous: one wrong command in a wrong window and
your machine is toast. I've done it.
The path rewrite commands of the form -files /etc:/etc
were therefore forbidden, but people find this inconvenient.
Now, when we have an absolute path as the destination, we will
adjust it to be relative to /.
A test is included.
> u-root: automagically adjust absolute paths with a warning

- pkg/kexec/kexec_linux_amd64.go
With the fixrsdp command, there should no longer be a need for this
command line parameter. This was also wrong as it only ever added the
parameter if we got an error back.
> kexec: remove rsdp command line parameter.

- pkg/mount/switch_root_linux.go
* do not move special mounts if they aren't mounts
* do not panic on error
* allow target dirs to be non-empty
> Improve behavior of mount.SwitchRoot

- cmds/kexec/kexec_linux.go
- cmds/pxeboot/pxeboot.go
- pkg/boot/boot.go
- pkg/boot/linux.go
- pkg/boot/multiboot.go
- pkg/multiboot/description.go
- pkg/multiboot/module.go
- pkg/multiboot/multiboot.go
- pkg/uio/lazy.go
- xcmds/esxiboot/esxiboot.go
- users shouldn't have to figure out what trampoline to use -- it's an implementation detail (make the multiboot package figure it out on its own)
- use boot.MultibootImage instead of multiboot.Multiboot -- the multiboot package should be internal.
> Higher-level multiboot interface

- pkg/multiboot/header.go
- pkg/multiboot/info.go
- pkg/multiboot/module.go
- pkg/multiboot/multiboot.go
- pkg/multiboot/multiboot_test.go
Also disambiguate info-structure flags from executable file header flags.
> multiboot: unexport more internals

- pkg/dhclient/dhclient.go
Report ourselves as "PXE UROOT" so we can be distinguished from other
pxe clients. Also always request a subnetmask option rather than only in
the DISCOVER message.
> Add Vendor Class Identifier for dhclient.

- integration/multiboot_test.go
- pkg/kexec/memory_linux.go
- pkg/kexec/memory_linux_test.go
- pkg/multiboot/module.go
- pkg/multiboot/multiboot.go
Pre-requisite for inserting things traditionally marked as reserved by firmware in memory maps like ACPI tables or iSCSI Boot Firmware Table.
> kexec: allow allocating memory as firmware-reserved

- pkg/cpio/newc.go
Let's do a thought experiment: you wish to save, say, /sys/log,
a directory of files that contain messages from various daemons.
You also want to verify that it worked right.
find /sys/log | cpio o | cpio -v i | wc
You discover that the number of files in /sys/log, and what wc
reports from cpio i, differ.
Or, worse, you are told the archive is corrupt.
What happened? Our cpio has a problem: it stats the file
to get the size, but then does not verify that the actual number
of bytes it wrote matches the stat.
Recall that newc records consist of a header, with an embedded size,
with a block of data that is supposed to match that size. The location
of the next record is determine by adding the size in the header
to the header offset. If you are thinking this is a fragile format,
you're right; …
> ensure that cpio does not create corrupt archives

- pkg/gpio/gpio_linux.go
I realized that filepath.Join incorrectly added a slash - this fixes
that so that the path used is /sys/class/gpio/gpio565/direction instead
of /sys/class/gpio/gpio/565/direction. Not sure what kind of unit tests
I can add to catch this kind of stuff
> Fixing gpio pkg paths

- pkg/dhclient/dhclient.go
- pkg/dhclient/dhcp4.go
Add support for dhcp options 15 and 119. Adds the domain and search
options to resolv.conf.
Signed-off-by: Lincoln Thurlow <lincoln@isi.edu>
> dhclient: support search domain options

- pkg/uroot/builder/bb/bb.go
The importer was only included to debug the build system itself, not for
users.
> pkg/uroot: stop spamming long error messages

- .circleci/images/test-image-amd64/Dockerfile
@rjoleary @hugelgupf I believe this is the only option needed for qemu to support 9p
> circleci amd64: enable virtfs

- cmds/boot/pxeboot/pxeboot.go
- cmds/core/dhclient/dhclient.go
- cmds/core/dhclient/dhclient_test.go
- pkg/dhclient/iface.go
- pkg/dhclient/iface_test.go
It's handy to be able to take an RE and get a set of interfaces
from it. We've found a need for this function in more than one
program now; time to make it part of a package.
The Interfaces function takes an RE and returns a list of
netlink.Link that matches it, or an error. It is an error
for the returned list to be empty.
> provide a function to get net interfaces from an RE

- .circleci/config.yml
- .circleci/images/test-image-amd64/Dockerfile
Fix CircleCI QEMU build after #1304 
cc @mpictor
> Fix CircleCI QEMU build

- .circleci/config.yml
I'm not sure why, but the total timeout has increased a little over 10
minutes. CircleCI has a default timeout of 10m when no output is
detected and Golang has a 10m default timeout for all tests together.
To make #1310 pass.
> circleci: increase test timeout

- templates.go
When we merged systemboot in we included the systemboot uinit
in all by accident. Explicitly select the commands we want in
boot.
Also, use the power of the glob for the cmds/boot to include
cmds/boot/*boot*, which includes any new ones we add and nicely
excludes the uinit.
> Do not include the cmds/boot/uinit in the "all" template

- cmds/core/dhclient/dhclient.go
This PR fixes infinite retry (as implied by the negative retry value).
```
dhclient -retry=-1
```
- Expected behavior: enters infinite retry loop.
- Actual behavior: context deadline exceeded.
> dhclient: fix negative -retry flag

- pkg/esxi/esxi.go
I misread
https://github.com/vmware/esx-boot/blob/abe46c4b2edb507e5486c3996075d9bd7ade4ba1/safeboot/bootbank.c#L194
because it checks the bank->bootstate *AFTER* it has been updated (see
the call to bank_set_bootstate a couple lines before).
The only bootable states are "valid" and "upgrading".
State transitions (which we do not implement) are supposed to be:
valid -> upgrading (done by upgrader)
upgrading -> dirty (done by bootloader)
dirty -> valid     (done by booted OS)
dirty -> invalid   (done by bootloader)
> pkg/esxi: boot 'upgrading' partitions, not 'dirty' ones

- cmds/core/cp/cp.go
- cmds/core/cp/cp_test.go
Patch for https://github.com/u-root/u-root/issues/1349
When copying from a source cp should print a skipped
error when the source is a directory and the recursive flag
is not set.
Signed-off-by: Brett Kochendorfer <brett.kochendorfer@gmail.com>
> cp: non-recursively copying dir should error

- cmds/boot/pxeboot/pxeboot.go
Add a -interface switch to pxeboot and set the default
value to allow pxeboot to use any interface, not just eth0.
> Allow pxeboot to use any ethernet

- cmds/boot/pxeboot/pxeboot.go
- When lease configuration failed, there is
still a default ip/ipv6 address available
locally, which was auto configured before
pexclient can send request packet. There
are usecases where DHCP server does not
assign IP and prefer local hardware based
address to be picked up. So updating pxeboot
to acommendate that.
- Arguably, it may be good to always have IP
assigned from server. This CL does not intend
to address the ask/argument about what is
best, but to update pxeboot to provide the
flexibility to the particular usecase mentioned
above.
- On a separate note, it maybe good to retry
lease configuration a few times upon failures
and then give up to boot further.
> pxeboot: continue to boot when lease failed.

- cmds/core/elvish/program/shell/interact.go
elvish would print an error message on startup if rc.elv
did not exist.
Turns out this was an error in the original; the author
expected filepath.Abs to return an error if the file
did not exist, and that is not the job of Abs.
Move the error test to the right place; no more annoying
error message. This has been a surprisingly common source
of confusion over the years so it's nice to have it gone.
> Remove annoying rc.elv error message on startup

- pkg/urlfetch/schemes.go
RFC7440:
TFTP is virtually unused for Internet transfers today, TFTP is still
massively used in network boot/installation scenarios including EFI
(Extensible Firmware Interface).
UEFI continues to put the legacy in legacy boot and the
backwards in backwards compatibility :-)
Anyway, since we are booting over networks that are essentially
error free (having a BER better than disk in some cases!) it makes
sense to boost the block and window sizes. Do so.
While we're at it, fetch in ModeOctet. ModeAscii is a legacy of the PDP10
and other machines with 7 bit bytes. Or 6. Or even 5. Not kidding. The
PDP10 byte pointer had a 6 bit field for byte length.
> Set more reasonable defaults for urlfetch tftp scheme

- pkg/kexec/kexec_linux_implemented.go
- pkg/kexec/kexec_linux_other.go
Recent kernels now support it.
Signed-off-by: Jean-Marc Eurin <jmeurin@google.com>
> Enable kexec on arm64 architecture.

- pkg/termios/termios.go
- pkg/termios/termios_linux.go
The serial configuration is highly inspired from other getty implementations
- agetty in util-linux
- getty in busybox
Signed-off-by: Julien Viard de Galbert <julien.viard-de-galbert@itrenew.com>
> pkg/termios: Add documentation to the Serial functions

- pkg/dhclient/dhclient.go
Extends the timeout waiting for a non-tentative IPv6 address.
If c.Timeout is too short, no DHCPv6 lease will be attempted at all. Internally, this messed us up at 3 seconds. For now, let's just give a default timeout.
> dhcp6: extend link timeout

- cmds/core/id/groups.go
- cmds/core/id/id.go
- cmds/core/id/id_test.go
- cmds/core/id/testdata/group-comments.txt
- cmds/core/id/testdata/group-simple.txt
- cmds/core/id/testdata/passwd-comments.txt
- cmds/core/id/testdata/passwd-simple.txt
- cmds/core/id/users.go
Resolves #1363 
Set out to resolve this issue with `id`, but also did some refactoring and added the following functionality:
- Now supports `id <user/uid>` syntax
- Now supports `-r` to get real uid/gid instead of effective
If {/etc/passwd,/etc/group} aren't present, it still prints an error, but doesn't fail.  See below example:
```console
2019/10/29 18:23:19 Welcome to u-root!
_
_   _      _ __ ___   ___ | |_
| | | |____| '__/ _ \ / _ \| __|
| |_| |____| | | (_) | (_) | |_
\__,_|    |_|  \___/ \___/ \__|
/# id
2019/10/29 18:23:24 id: unable to read /etc/passwd: open /etc/passwd: no such file or directory
2019/10/29 18:23:24 id: unable to read /etc/passwd: open /etc/group: no such file or directory
uid=0(0) gid=0(0) groups=0(0)
/# 
```
> Updated `id` command

- cmds/exp/hdparm/hdparm.go
- pkg/scuzz/ata.go
- pkg/scuzz/control.go
- pkg/scuzz/sg_linux.go
- pkg/scuzz/sg_linux_test.go
The ATA identify reads information from those disks
which support the command.
This PR adds the Response interface, which allows programs
to query the result.
We separate what look like transport errors, i.e. the system
call failed for some reason, from target errors, i.e. the system
call worked but the drive rejected the command. The kernel does
not make such a seperation, which calls our seperation into
question.
Error determination from the status block is a work in progress,
not expected to be completed quickly.
This is nevertheless a basic starting point for an identify.
> scuzz: add ATA identify command

- website/docs/index.md
It was removed in e0163ad96bfdfb9896bbb3bb73d759575357905b
> webiste: remove obsolete reference to pre-commit hook

- cmds/core/ip/ip.go
- cmds/core/ip/ops.go
Add basic support for bridge devices to ip. The following runes are implemented:
- ip link add [ name ] NAME type bridge
- ip link set [ dev ] NAME master DEV
Further, "ip link show" has been updated to show the link's master device, if any.
Please excuse my probably not entirely idiomatic Go code, feedback appreciated. Lightly tested w/ modified uinit as shown here: https://gist.github.com/mato/69e11d2078a7924be5e9ad5d3a628452
> ip: Add basic support for bridge devices

- cmds/core/hostname/hostname.go
Add support to set system hostname, like the standard hostname command.
Signed-off-by: Martin Lucina <martin@lucina.net>
> hostname: Add support to set system hostname

- .circleci/config.yml
- .circleci/images/test-image-arm/Dockerfile
- .circleci/images/test-image-arm/config_linux5.2.0_arm.txt
We want to update the ARM kernel config used in our circleci tests to
have 9p support (since we are changing our vm tests to always use 9p).
This updates the configs and Dockerfile to reflect the new kernel.
> Updating circleci docker image

- .circleci/config.yml
- .circleci/images/test-image-arm/Dockerfile
We want to update the ARM QEMUused in our circleci tests to
have 9p support (since we are changing our vm tests to always use 9p).
This updates the configs and Dockerfile to reflect that.
> Update circleci docker image

- integration/README.md
- integration/dhclient_test.go
- integration/io_test.go
- integration/kexec_test.go
- integration/multiboot_test.go
- integration/tcz_test.go
- integration/testcmd/generic/uinit/generic.go
- integration/testcmd/gotest/uinit/gotest.go
- integration/uinit_test.go
- pkg/qemu/devices.go
- pkg/vmtest/gotest.go
- pkg/vmtest/integration.go
Our current test infra builds the test itself into the initramfs, which
means that we cannot separating building and testing or test with a
custom initramfs. To solve this, we separate the test from the
initramfs as follows:
Instead of building a uinit.go with the caller's provided commands, have
a generic uinit.go that finds an Elvish shell script of test commands in
the P9 directory exposed to the VM. This way callers can either 1)
provide a custom uinit or 2) provide commands to run for testing.
As part of that, we add some options to vmtest.Options and change the
tmpDir to be easier to work with.
(I can break this into smaller commits if thats better)
> Integration tests: separate test from initramfs

- pkg/dhclient/dhcp6.go
The return value is an Option, not an option pointer.
> Fix option parsing for dhcp6 package

- pkg/ulog/log.go
- pkg/ulog/ulogtest/log.go
- pkg/vmtest/integration.go
While using u-root in bb mode I noticed that commands using the "flag"
package got all the -test.* flags in their help message.
Removing the "testing" package from the default build fixes this.
Signed-off-by: Julien Viard de Galbert <julien.viard-de-galbert@itrenew.com>
> pkg/ulog: move test logger in a sub package

- cmds/core/find/find.go
- pkg/cpio/cpio.go
- pkg/find/find.go
- pkg/find/find_test.go
currently, users of `pkg/find` have to do the following:
```go
f := find.New(func(f *Finder) error {
f.Root = "/boot"
})
go f.Find()
for name := range f.Names {
```
with this PR, it changes to:
```go
names := find.Find(ctx, find.WithRoot("/boot"))
for name := range names {
```
cc @dpsmith your usage of `pkg/find` inspired me to fix the API...
> pkg/find: nicer user API

- .github/auto-merge.yml
If the 'automerge' label is added to the PR, This tool automatically
merges the PR once it has all the necessary approvals.
This is useful for trivial PRs such as
https://github.com/u-root/u-root/pull/1443 which are in an endless cycle
of bringing the branch up to date.
> Add config for automerge tool

- pkg/smbios/struct_parser.go
It inhibits dead code elimination
> dmidecode: Do not use reflect.Value.MethodByName

- cmds/boot/boot/boot.go
- pkg/boot/linux.go
This relates to:
https://github.com/u-root/u-root/issues/751
https://github.com/u-root/u-root/issues/1054
https://github.com/u-root/u-root/pull/1283
https://github.com/u-root/u-root/pull/1241
I'm currently starting from the boot/boot command as it uses less packages so almost everything is in the same file.
> refactor boot commands to use pkg/boot and avoid unnecessary file copy

- Gopkg.lock
- cmds/boot/fbnetboot/main.go
- pkg/checker/interfaces.go
- vendor/github.com/insomniacslk/dhcp/dhcpv6/client6/client.go
- vendor/github.com/insomniacslk/dhcp/dhcpv6/option_bootfileparam.go
- vendor/github.com/insomniacslk/dhcp/dhcpv6/options.go
- vendor/github.com/insomniacslk/dhcp/netboot/netboot.go
Added support of DHCP option 60 on IPv6 to define arguments (cmdline) to the loading kernel.
Task: https://github.com/u-root/u-root/issues/1384
~~Depends on: https://github.com/insomniacslk/dhcp/pull/340~~
~~Update: The build is failed because of the dependency above.~~
> cmds/boot/fbnetboot: use bootfile params if provided

- cmds/core/elvish/edit/api.go
- cmds/core/elvish/edit/completion/completion_mode.go
- cmds/core/elvish/edit/eddefs/binding_map.go
- cmds/core/elvish/eval/builtin_fn.go
- cmds/core/elvish/eval/builtin_fn_test.go
- cmds/core/elvish/eval/ns.go
Use of `reflect.Value.Call` disables unused public method elimination at build time,
which leaves unused code in the resulting binary,
see https://github.com/u-root/u-root/issues/1477.
Elvish uses `reflect.Value.Call` to invoke builtin functions.
Replace its use with a static set of possible function signatures:
these cover all existing use cases and can be extended if needed.
Saves approx. 3.2M on amd64 (go 1.13.5 + text/template patch):
```
[rojer9@rojer9-t470 ~/go/src/github.com/u-root/u-root/bb master]$ GOROOT=$HOME/go_210284 go build && ls -l bb
-rwxrwxr-x. 1 rojer9 rojer9 20645771 Dec 16 16:40 bb
[rojer9@rojer9-t470 ~/go/src/github.com/u-root/u-root/bb master]$ gc elvish_noreflect
Switched to branch 'elvish_noreflect'
[rojer9@rojer9-t470 ~/go/src/github.com/u-root/u-root/bb …
```
> elvish: Do not use reflect.Call

- pkg/rand/random_unix.go
- pkg/rand/random_urandom.go
This package is sometimes used by other projects, at least
"github.com/insomniacslk/dhcp/dhcpv4".
Therefore, it must be ported even if the whole u-root project isn't
available on AIX.
> pkg/rand: add AIX support

- pkg/pty/pty_linux.go
- tools/testramfs/testramfs.go
testramfs was broken by a series of changes culminating in 8483665f289e261c7e6ada8bd24803c473ae5950
I can't get the noninteractive test working again, but this does fix interactive usage.
I'll try to figure out what broke noninteractive later this week.
A further question: why did our CI no catch this? No idea.
Signed-off-by: Ronald Minnich <rminnich@gmail.com>
> fix testramfs

- cmds/exp/ipmidump/ipmidump.go
- pkg/ipmi/ipmi.go
Print chassis power status and SEL information in u-root shell 
via IPMI "get chassis status" and "get SEL info".
> cmds/ipmidump: Add ipmidump command to dump IPMI chassis and SEL info

- cmds/core/init/init_linux.go
- pkg/cmdline/cmdline.go
- pkg/cmdline/cmdline_test.go
Update init_linux.go to load modules from /lib/modules before exec-ing into userland
Signed-off-by: Jake Saferstein <jsaf@google.com>
> Load modules in Init before userland

- pkg/boot/stboot/bootball.go
> STBoot: Fix getSignatures Filewalk generating extensive arrays

- pkg/golang/build.go
- pkg/vmtest/gotest.go
It appears function inlining was enabled and it was taking a lot of space. So flag `-gcflags=all=-l` was added to reduce the size of the initrd image.  The size of the image was reduced on 15% in the compressed state.
Before:
$ stat -c %s /tmp/initramfs.linux_amd64.cpio.inline
16399044
$ stat -c %s initramfs.linux_amd64.cpio.inline.xz
4613328
$ stat -c %s stat /tmp/extracted/inline/bbin/bb
16384000
$ go tool objdump bb | awk '{print $1}' | sort | uniq -c | sort -rn | head -10
102193 <autogenerated>:1
15791 TEXT
15790
13388 nl_linux.go:271
11954 nl_linux.go:290
8860 nl_linux.go:376
6805 errors.go:59
5571 data.go:12
4949 builder.go:298
3413 buffer.go:92
After:
$ stat -c %s /tmp/initramfs.linux_amd64.cpio.noinline
14887620
$ stat -c %s /tmp/initramfs.linux_amd64.cpio.noinline.xz
3933256
$ …
> Disable function inlining

- cmds/core/kexec/kexec_linux.go
- pkg/boot/esxi/esxi.go
- pkg/boot/esxi/esxi_test.go
- pkg/boot/kexec/memory_linux.go
- pkg/boot/multiboot.go
- pkg/boot/multiboot/description.go
- pkg/boot/multiboot/module.go
- pkg/boot/multiboot/multiboot.go
- pkg/boot/multiboot/reader.go
- pkg/bootconfig/bootconfig.go
The goal is to unify the interface with LinuxImage and hopefully allow to PXE boot multiboot kernel
> Rework MultibootImage to use ReaderAt instead of filename

- README.md
The default for pkg.go.dev is to show documentation for the last u-root
release, which happened last August. I'd rather we get our documentation
at HEAD.
This reverts commit ad45df693f3715dbc8f0a6a40586a43c2e7987e4.
> Revert "Update godoc link to pkg.go.dev"

- u-root.go
When we started u-root in 2011, on Go 1.2, the toolchain was
based on Ken's Plan 9 C compiler toolchain (in fact, the amd64
toolchain was derived from the DOE-funded C toolchain created
by Vita Nuova for DOE Fast-OS).
That compiler was so fast that I ran, by mistake, with commands always
being compiled and it was months before I noticed it.
Time flies. Go is not as fast as it was. Commands take many seconds to compile.
It's not really viable to have a Go compiler in FLASH at this point.
Even little disks are very big, so the space argument no longer holds for root
file systems. Almost no one (and maybe no one) uses source mode any more.
Make the default be bb, which everyone uses.
> u-root: default to build=bb

- pkg/boot/netboot/netboot.go
The hack is what to do if DefaultEntry is not set: use "LinuxImage"
as the name.
The good fix is to correctly detect nothing was found, and return
an error, instead of returning nil, nil, which was causing pxeboot
to explode.
> pkg/boot/netboot: Check for error in looking up the name instead of returning a nil pointer that will cause callers to panic

- pkg/ldd/ldd_test.go
- pkg/ldd/ldd_unix.go
go get github.com/u-root/u-root on darwin fails with
```
u-root/u-root/pkg/ldd/ldd_unix.go:156:18: undefined: LdSo
```
Fix this by adding build constraints for freebsd and linux which are
currently the only supported platforms for pkg/ldd
> pkg/ldd: add build constraints

- cmds/core/fusermount/fusermount_linux.go
`Setfsuid`/`Setfsgid` from `x/sys/unix` don't return the previous filesystem
uid/gid, so `restorePrivs` will be a no-op as it is just setting previous
`fileSystemUID` and `fileSystemGID` again.
golang/sys@e047566fdf introduced the `SetfsuidRetUid`/`SetfsgidRetGid`
wrappers for the `setfsuid`/`setfsgid` syscalls returning the previous
fileystem uid/gid. Use these and store the previous values, so they can
be used in `restorePrivs`.
> cmds/core/fusermount: restore privs correctly

- cmds/exp/pox/pox.go
- pkg/ldd/ldd_unix.go
This patch series consists of a bunch of changes to pox that helped me run it on non-standard Linux machines.  Highlights include:
- Splits pox's creation (-c) from running (-r).  You can now do only one at a time.
- Allow passing arguments to your binary, with '--'
- Option to use zip (-z) instead of squashfs, for kernels without CONFIG_SQUASHFS built in
With these changes, I am able to pox-run a relatively complicated program (https://github.com/pmem/ndctl) that requires several shared libraries, including its own .sos, and runtime access to /proc and /sys.
> Pox improvements

- cmds/core/kexec/kexec_linux.go
- pkg/boot/esxi/esxi.go
- pkg/boot/esxi/esxi_test.go
- pkg/boot/multiboot.go
- pkg/boot/multiboot/description.go
- pkg/boot/multiboot/module.go
- pkg/boot/multiboot/multiboot.go
- pkg/boot/multiboot/reader.go
- pkg/bootconfig/bootconfig.go
This has broken multiboot for ESXi kernels. I need to temporarily revert this for time constraints, I will fix forward later. cc @JulienVdG 
you can use the instructions at https://github.com/u-root/u-root/tree/master/cmds/exp/esxiboot to reproduce the failure. I'll be bisecting to test this.
> Multiboot ReaderAt revert

- cmds/exp/page/main.go
The u-root less program has a lot of issues that make it
'less' useful, especially in firmware environments:
1) can't read from a pipe
2) can't read from any file that can't be mmap'ed
3) can't be in a pipeline
4) needs builtin terminfo support and environment variables
5) at least for me, has a weird error that won't let it read commands at all,
so I'm always stuck seeing just one page of text
page is a dead simple pager modeled on the one from Plan 9.
It's already more useful to me than our less program.
And it's got far less footprint: 2.22M vs. 3.38M
> add a simple pager

- cmds/core/chmod/chmod.go
- cmds/core/chmod/chmod_test.go
Fixes #1366
Signed-off-by: Ward Vandewege <ward@jhvc.com>
> chmod: support (u|g|o|a)(+|-|=)(r|w|x) syntax

- cmds/exp/ash/ash.go
- pkg/complete/file.go
- pkg/complete/line_test.go
- pkg/complete/newline.go
If you run
INTERACTIVE=1 go test -run TestSh
you can try what I think may be a good enough completer.
The first arg on the line will be determined from $PATH;
then we switch to a file completer.
ash is also modified to work with this. It seems to work
fine SAVE there is not  prompt yet; WIP.
Try this if you can and see if it is close.
If it works,  we have an advantage:
- much smaller code and binary: 2.7M vs. 5.1M for elvish
- code is easier (for me) to understand
- completer package is useful in other programs
> Get completion rules right 

- cmds/core/kexec/kexec_linux.go
If you run kexec this way:
kexec -l /bzImage
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x953946]
goroutine 1 [running]:
google3/third_party/golang/uroot/pkg/uio/uio.(*LazyOpenerAt).ReadAt(0x0, 0xc000220000, 0x8000, 0x8000, 0x0, 0xcf51c0, 0xc000036d01, 0xc000220000)
third_party/golang/uroot/pkg/uio/lazy.go:89 +0x26
io.(*SectionReader).Read(0xc0001c8840, 0xc000220000, 0x8000, 0x8000, 0x0, 0x0, 0xe8c93c)
third_party/go/gc/src/io/io.go:478 +0x7c
io.copyBuffer(0x1073e20, 0xc00000e488, 0x1073860, 0xc0001c8840, 0xc000220000, 0x8000, 0x8000, 0x2f7d40, 0x0, 0x0)
third_party/go/gc/src/io/io.go:405 +0x122
io.Copy(...)
third_party/go/gc/src/io/io.go:364 …
> kexec: fix segv when no initramfs is specified

- pkg/complete/newline.go
- pkg/complete/prefix.go
- pkg/complete/prefix_test.go
there may not be an exact match but there may be enough to fill out the completion more
This gives us nicer behavior:
% ls /etc/ho
[/etc/host.conf /etc/hostname /etc/hosts /etc/hosts.allow /etc/hosts.deny]
% ls /etc/host
[/etc/host.conf /etc/hostname /etc/hosts /etc/hosts.allow /etc/hosts.deny]
note that I hit /etc/ho<tab><tab> and it filled it out to the
longest common prefix.
> add a prefix function

- cmds/core/msr/doc.go
- cmds/core/msr/msr.go
This is for convenience:
msr lock <glob> <msr-#> <value>
Will OR value into all the <msr>s on cores <glob>.
The MSRs must be readable.
> msr: add a lock command

- cmds/exp/madeye/doc.go
- cmds/exp/madeye/madeye.go
This is an original goal of u-root: that we could build a root file system
and use it on different architectures.
This is called MADI: Multi Architecture Disk Image. It has binaries for several
architectures, rooted at, e.g., /amd64, /arm, and so on; with binaries in, e.g.,
/amd64/bbin, and init in /amd64/init.
To boot on, e.g., x86_64, you set init=/amd64/init
It's spelled madeye so people know how to say and, because, some might think it mad.
This idea is not original with u-root; it's how Plan 9 works. It was the reason for the
"source mode" in original u-root: four binaries only, the rest source. Busybox mode
did not come until 2015 or so, and it turns out it lets us do the same thing with
one binary or five; we can have both busybox and source mode MADIs.
Source mode and busybox mode …
> madeye: create Multi Architecture Disk Images

- cmds/exp/pox/pox.go
ldd.Ldd returns ALL the names, including the names of
the input files. We appended the ldd.Ldd results
to the file names, resulting in us adding the binary
names twice.
This has not been a problem in several years, until we hit
a weird case today where adding a file twice failed.
Just use the ldd.Ldd() list.
> pox: just use the list of names retured by ldd.Ldd()

- docs/index.md
v1.11 > v1.12 as per README.md
> docs/index.md: Use same go version as in README.md

- .circleci/images/test-image-amd64/Dockerfile
Fixes #1298
As comparison: test-image-arm runs QEMU v3.1.0 from 2018.
v4.2.0 builds well locally on amd64, I hope this doesn't break
any integration. If all works well I will also update the arm image if wanted.
> test-image-amd64/Dockerfile: Bump QEMU to version v4.2.0

- cmds/exp/pox/pox.go
It has proven handy to allow users to add more mappings.
For instance, we might want to share a /tmp with the outside
world. The -e[xtra] switch lets you do this:
pox -c -e /tmp /bin/ls # creates the extra directories you will need
pox -r -e /someplace:/tmp ls -l /tmp
As an extra convenience you can now build and run in one step:
pox -c -r /bin/bash
will build the pox and run /bin/bash, or:
rminnich@xcpu:~/gopath/src/github.com/u-root/u-root/cmds/exp/pox$ sudo ./pox -r -c /bin/ls
pox  pox.go  pox.test  pox_test.go
rminnich@xcpu:~/gopath/src/github.com/u-root/u-root/cmds/exp/pox$ sudo ./pox -r -c /bin/date
Tue Mar 10 00:38:57 UTC 2020
pox is actually becoming useful in ways we did not imagine. It's great
for creating text infra and running things in it that have dependencies
on weird …
> Allow users to add more pox mappings

- .circleci/config.yml
Bump dep v0.5.0 (Jul 2018) -> latest v0.5.4 (Jul 2019) in circleci/config.yml
> .circleci/config.yml: Bump dep to v0.5.4

- .circleci/config.yml
This PR will bump the UROOT_QEMU_TIMEOUT_X value to 3 for QEMU VM tests
in .circleci/config.yml.
Local `circleci build --job test` builds consistently failed for me before increasing 
the timeout value.
> circleci/config.yml: Increase UROOT_QEMU_TIMEOUT_X fixes build failures

- cmds/core/lockmsrs/lockmsrs.go
- cmds/core/msr/msr.go
- pkg/msr/msr_linux.go
These are all MSRs in the Intel SDM, Lock them as part of Linuxboot.
> Lock documented MSRs.

- pkg/forth/forth.go
- pkg/forth/forth_test.go
The forth eval loop as broken for 8 years and nobody noticed -- and, weirdly, this
code was used.
If two Eval's were nested, the inner one would catch panics and the outer one would return
no error. This hid a broken forth test (for 8 years) and broke the msr command.
This now works right:
rminnich@xcpu:~/gopath/src/github.com/u-root/u-root/cmds/core/msr$ ./msr  READ_IA32_FEATURE_CONTROL
2020/03/14 06:26:40 [open /dev/cpu/0/msr: permission denied open /dev/cpu/1/msr: permission denied open /dev/cpu/2/msr: permission denied open /dev/cpu/3/msr: permission denied]
and
rminnich@xcpu:~/gopath/src/github.com/u-root/u-root/cmds/core/msr$ sudo ./msr  READ_IA32_FEATURE_CONTROL
[5 5 5 5]
> Fix some forth eval fun

- cmds/core/pci/pci.go
- pkg/pci/pci_linux.go
- pkg/pci/pci_linux_test.go
Also allow the pci command to take , separate globs, viz:
rminnich@xcpu:~/gopath/src/github.com/u-root/u-root/cmds/core/pci$ ./pci -s *1[78]*
0000:00:17.0: VMware PCI Express Root Port
0000:00:17.1: VMware PCI Express Root Port
0000:00:17.2: VMware PCI Express Root Port
0000:00:17.3: VMware PCI Express Root Port
0000:00:17.4: VMware PCI Express Root Port
0000:00:17.5: VMware PCI Express Root Port
0000:00:17.6: VMware PCI Express Root Port
0000:00:17.7: VMware PCI Express Root Port
0000:00:18.0: VMware PCI Express Root Port
0000:00:18.1: VMware PCI Express Root Port
0000:00:18.2: VMware PCI Express Root Port
0000:00:18.3: VMware PCI Express Root Port
0000:00:18.4: VMware PCI Express Root Port
0000:00:18.5: VMware PCI Express Root Port
0000:00:18.6: VMware PCI Express Root Port …
> pci: alloc NewBusReader to take a []string

- pkg/boot/acpi/rsdp.go
This allows you to select which method to use for finding the RSDP.
> Make GetRSDPEFI and GetRSDPMem function public

- .circleci/config.yml
This PR updates .circleci/config.yml to use
uroottest/test-image-amd64:latest which uses QEMU v4.2.0
> .circleci/config.yml: use uroottest/test-image-amd64:latest

- cmds/core/lockmsrs/lockmsrs.go
- pkg/msr/msr_linux.go
This helps when we happen to be trying to lock MSRs
that are already locked. This avoids the resulting io error. If we
really want to rewrite the same value you can do so using read followed
by write.
> Rename MaskBits to TestAndSet and write only if changed

- cmds/core/lockmsrs/lockmsrs.go
- pkg/msr/intel.go
- pkg/msr/msr.go
- pkg/msr/msr_linux.go
- pkg/msr/msr_linux_test.go
There were constants defined in lockmsr that are
useful to have in the msr package; move them. Place the
Intel-specific MSR settings in an array.
Add a Test function to verify settings.
Add test code, now that constants and a Test function
are available.
Add -verify option to lockmsr.
> msr: move definitions to package, add Test function, add -verify to lockmsr

- pkg/bb/bbmain/cmd/main.go
- pkg/bb/bbmain/register.go
The bb command exits silently when invoked directly, e.g.
/bbin/bb
just exits.
Sometimes due to build system problems an initramfs is built
either with missing symlinks or missing compiled-in commands.
These problems are difficult to diagnose.
With this change, bb invoked directly will create a listing
of the command, formed from either the basename of the /bbin/
symlink or the list of compiled-in commands; the symlink;
and the compiled-in command name.
If the symlink is missing or there is a symlink with no compiled-in
command, a diagnostic is shown, e.g. if we have an image with a bogus
symlink, in this ccat; or a missing symlink, in this case cat, we
would see (among a listing of all correct commands)
cat:	NO SYMLINK	cat
ccat:	"/bbin/ccat"	NO COMMAND
N.B. this command does not sort …
> bb: if bb is invoked directly, list commands and symlinks

- cmds/core/ts/ts.go
- pkg/ts/ts.go
- pkg/ts/ts_test.go
This prepends a timestamp in front of each line of stdin. Useful for
measuring performance from logs.
> Add ts command

- cmds/core/ts/ts.go
- pkg/ts/ts.go
When the -f argument is set, the first line printed will always be
prefixed with "[0.0000s]" all other lines are relative to this.
> ts: Add option for times relative to first line

- cmds/boot/systemboot/main.go
CMOS clear and fbnetboot are OEM defined SEL.
Signed-off-by: Johnny Lin <johnny_lin@wiwynn.com>
> systemboot: Add OEM CMOS clear SEL and update fbnetboot SEL

- templates.go
In current master uinit is deprecated. The systemboot template
is referencing it still and breaking the build consequently.
Therefore systemboot is discarded in favor of the all-template
Signed-off-by: Patrik Tesarik <mail@patrik-tesarik.de>
For more background information check the u-root slack channel [here](https://u-root.slack.com/archives/CAJUM8MF1/p1586425897025100) and following.
> Change: templates.go

- cmds/core/strace/strace.go
- uroot_test.go
386 had stopped building and nobody noticed.
strace will need to be fixed but for now -- just exclude it.
Add a test case to make sure it does not break again.
> Get 386 to build again; add a test to make sure.

- cmds/core/strace/strace.go
- pkg/cpio/sysinfo_linux.go
- pkg/mount/switch_root_linux.go
This is to tackle #1652, though I cannot yet confirm that it really works.
For testing, I am using https://people.debian.org/~aurel32/qemu/mipsel/
QEMU command:
```sh
#!/bin/sh
export RAM_SIZE=32M
export KERNEL=vmlinux-3.2.0-4-4kc-malta
export INITRD=initramfs.linux_mipsle_mini.cpio
qemu-system-mipsel \
-M malta \
-m $RAM_SIZE \
-kernel $KERNEL \
-initrd $INITRD \
-append "console=ttyS0" \
-nographic
```
With the initramfs, the output is stuck early:
```
[    0.000000] Initializing cgroup subsys cpuset
[    0.000000] Initializing cgroup subsys cpu
[    0.000000] Linux version 3.2.0-4-4kc-malta (debian-kernel@lists.debian.org) (gcc version 4.6.3 (Debian 4.6.3-14) ) #1 Debian 3.2.51-1
[    0.000000] bootconsole [early0] enabled
[    0.000000] CPU revision is: 00019300 (MIPS 24Kc)
[ …
```
> Fix mipsle

- README.md
- cmds/boot/boot/boot.go
- pkg/boot/grub/echo_test.go
- pkg/boot/grub/grub.go
- pkg/boot/grub/grub_test.go
- pkg/boot/grub/testdata/bash_wrapper.sh
- pkg/boot/grub/testdata/example_grub_script_test.in
- pkg/boot/grub/testdata/example_grub_script_test.out
- pkg/boot/grub/testdata/grub_cmd_echo.in
- pkg/boot/grub/testdata/grub_cmd_echo.out
- pkg/boot/grub/testdata/grub_script_comments.in
- pkg/boot/grub/testdata/grub_script_comments.out
- pkg/boot/grub/testdata/grub_script_echo_keywords.in
- pkg/boot/grub/testdata/grub_script_echo_keywords.out
- pkg/boot/grub/testdata/import_grub_tests.sh
- pkg/boot/grub/testdata/test_bash_wrapper.sh
- pkg/boot/syslinux/syslinux.go
This is a work in progress parsers replacement.
I started in boot as it doesn't use packages. Basically the functions added at the end of boot.go should go to a new "diskboot" or "localboot" or whatever package.
Opening the PR now to show the work.
> Boot parsers

- pkg/boot/ibft/ibft.go
You can't make this shit up -- the spec is at ftp://ftp.software.ibm.com/systems/support/bladecenter/iscsi_boot_firmware_table_v1.03.pdf. Origin is undocumented, other than to link to http://msdn.microsoft.com/library/default.asp?url=/library/en-us/iphlp/iphlp/ip_prefix_origin.asp, which doesn't exist anymore.
> ibft: demystify Origin field

- .cirrus.yml
If somebody wants to fix cirrus that's fine, but picking up after it
dumps a load is getting old fast.
> neuter cirrus

- cmds/exp/acpicat/main.go
- cmds/exp/acpigrep/main.go
- pkg/acpi/acpi.go
- pkg/acpi/acpi_test.go
- pkg/acpi/linux_test.go
- pkg/acpi/raw.go
- pkg/acpi/rsdp.go
- pkg/acpi/rsdp_linux.go
- pkg/acpi/rsdp_linux_test.go
- pkg/acpi/rsdp_unix.go
- pkg/acpi/tables.go
- pkg/acpi/tables_linux.go
- pkg/acpi/tables_linux_test.go
This simple package supports reading the RSDP, reading, and writing tables.
Programs can read in tables, pick which ones to write, and write them out.
This package is useful for generating tables for cbfs.
Two programs are included:
acpicat, for cat'ing all acpitables from a named source type -- e.g files in /sys
acpigrep, a filter for keeping (discarding) tables whose signature matches (does not match) an RE.
> ACPI functions

- cmds/exp/console/console.go
console is invaluable for debugging serial console issues.
It was originally designed to run as init, but we can much
more easily run as uinit, and avoid setup issues.
To build:
u-root -o /tmp/console.cpio -uinitcmd=/bbin/console all github.com/u-root/u-root/cmds/exp/console
to use:
/usr/bin/qemu-system-x86_64 -kernel somekernel -initrd /tmp/console.cpio -append console=ttyS0 -serial stdio -monitor /dev/null -m 8192
kernel will need to have
CONFIG_DEVPORT=y
CONFIG_UNIX98_PTY=y
> Fix up console so it correctly runs as uinit

- cmds/exp/esxiboot/esxiboot.go
- integration/generic-tests/esxi_boot_test.go
- pkg/boot/multiboot/header.go
- pkg/boot/multiboot/info.go
- pkg/boot/multiboot/internal/trampoline/trampoline.go
- pkg/boot/multiboot/internal/trampoline/trampoline_linux_amd64.go
- pkg/boot/multiboot/internal/trampoline/trampoline_linux_amd64.s
- pkg/boot/multiboot/module.go
- pkg/boot/multiboot/multiboot.go
- pkg/boot/multiboot/multiboot_test.go
- pkg/boot/multiboot/mutiboot_info.go
- pkg/boot/multiboot/mutiboot_info_test.go
- pkg/boot/multiboot/mutiheader.go
- pkg/qemu/devices.go
- pkg/qemu/qemu.go
- pkg/vmtest/integration.go
mutiboot is VMware ESXi's homegrown multiboot mutation to support EFI and arm64. Post-7.0 GA kernels will not support multiboot anymore.
mutiboot is their interface between the bootloader (http://github.com/vmware/esx-boot) and kernel (well, first-stage kernel, b.b00). Despite being relatively stable, they don't consider it stable, and neither should we. Implementing mutiboot is a temporary measure.
Long-term, we need to pick up Ofir's work and bring it to productionization, and boot ESXi by booting the EFI bootloader.
It's a rough first draft, it needs cleanup and nicer commits. And b.b00 is still crashing somewhere shortly after looping through the mutiboot elements, but I think I've almost got that one.
cc @oweisse @n-canter @TimothyPMann (in case you were curious :))
> VMware mutiboot support

- pkg/uroot/initramfs/cpio.go
The archive doesn't need the execute bit: 0755 -> 0644.
> uroot/initramfs/cpio: Fixup OpenFile filemodes.

- cmds/exp/acpicat/main.go
- pkg/acpi/acpi.go
- pkg/acpi/acpi_test.go
- pkg/acpi/bios.go
- pkg/acpi/raw.go
- pkg/acpi/rsdp.go
- pkg/acpi/rsdp_linux.go
- pkg/acpi/rsdp_unix.go
- pkg/acpi/sdt.go
- pkg/acpi/tables_linux.go
What is in FLASH (top 128K) and what kernels show you is not
always the same. Here is an example, the first coming from ebda, the
second from linux files in /sys:
```
rminnich@xcpu:~/gopath/src/github.com/u-root/u-root/cmds/exp/acpicat$ sudo ./acpicat  -s ebda | ../acpigrep/acpigrep -d . >/dev/null
2020/05/11 21:57:51 Keeping RSDT@0x0 64 1 0x5b "INTEL " "440BX   " 0x06040000 0x50544c20 0x00000000
2020/05/11 21:57:51 Keeping FACP@0x0 116 1 0xf7 "INTEL " "440BX   " 0x06040000 0x204c5450 0x000f4240
2020/05/11 21:57:51 Keeping DSDT@0x0 138866 1 0xaa "PTLTD " "Custom  " 0x06040000 0x5446534d 0x03000001
2020/05/11 21:57:51 Keeping BOOT@0x0 40 1 0xa5 "PTLTD " "$SBFTBL$" 0x06040000 0x50544c20 0x00000001
2020/05/11 21:57:51 Keeping APIC@0x0 1858 1 0x8f "PTLTD " "\t APIC  " 0x06040000 0x50544c20 …
```
> ACPI: Add functions to read *SDT and tables from memory

- pkg/boot/esxi/esxi.go
- pkg/boot/esxi/esxi_test.go
- pkg/boot/esxi/testdata/kernelopt_first.cfg
The kernel cmdline is expected to have a filename as arg[0], and I doubt /tmp/sda5-blablabla/b.b00 is a useful arg[0] for any of the ESXi cmdlines.
before:
```bash
[root@localhost:~] vsish -e get /system/bootCmdLine
vmkernel bootloader command line {
command line:no-auto-partition logPort=com1 gdbPort=none tty2Port=none bootUUID=7a2bbd9707adf29999b9eabd783cde33 vmkBootVerbose=TRUE vmbLog=TRUE debugLogToSerial=1
}
```
after:
```bash
[root@localhost:~] vsish -e get /system/bootCmdLine
vmkernel bootloader command line {
command line:b.b00 no-auto-partition logPort=com1 gdbPort=none tty2Port=none bootUUID=7a2bbd9707adf29999b9eabd783cde33 vmkBootVerbose=TRUE vmbLog=TRUE debugLogToSerial=1
}
```
> ESXi: tweak cmdline handling

- pkg/boot/syslinux/syslinux.go
- pkg/boot/syslinux/syslinux_test.go
Simple NERF chainloader support (NERFDEFAULT)
change the pxeboot.cfg/default configuration:
==== old ====
DEFAULT foo
LABEL foo
KERNEL /bzImage
INITRD /initrd.cpio.gz
APPEND root=/dev/ram0 ramdisk=8192 console=ttyS0,115200n8
LABEL bar
KERNEL /bar-bzImage
INITRD /bar-initrd.cpio.gz
APPEND root=/dev/ram0 ramdisk=8192 console=ttyS0,115200n8
==== new ====
DEFAULT foo
NERFDEFAULT bar
LABEL foo
KERNEL /bzImage
INITRD /initrd.cpio.gz
APPEND root=/dev/ram0 ramdisk=8192 console=ttyS0,115200n8
LABEL bar
KERNEL /bar-bzImage
INITRD /bar-initrd.cpio.gz
APPEND root=/dev/ram0 ramdisk=8192 console=ttyS0,115200n8
When BIOS is loading, it does not know anything about 'NERFDEFAULT' and will
simply load the foo kernel and initrd. When NERF is loading, it will parse the
same configuration file again and will …
>  Simple NERF chainloader support (NERFDEFAULT)

- pkg/boot/gboot/entry/entry.go
- pkg/boot/gboot/entry/entry_test.go
An entry file is a GRUB environment file consisting of key-value pairs
akin to the GRUB commands load_env and save_env.
> Add grub entry file parser

- pkg/cmos/cmos.go
- pkg/cmos/docs.go
cmds/core/io/cmos.go is only built into the io package if it's amd64 or
386. In the Go build system, that means pkg/cmos is never even compiled.
However, in blaze/bazel, all dependencies are always built, used or not,
since it doesn't know any better. That means pkg/cmos has to be
buildable on other architectures than amd64 or 386.
If you just add the build tags "+build amd64 386", pkg/cmos won't be
compilable by blaze/bazel because it's empty.
Hence, we need a neutral file in there that always builds.
> cmos: add non-constrained docs file

- pkg/mount/fs_linux.go
- pkg/mount/fs_linux_test.go
circleci has cut pack /proc/filesystems output, and the test is failing
at HEAD right now.
> pkg/mount: system-independent FindFileSystem test

- pkg/vmtest/internal/json2test/testcollector.go
otherwise, our VM tests print non-sense like this:
gotest.go:126: Test github.com/u-root/u-root/pkg/menu.TestChoose/hit_3 left in state 3:
after this commit, it'll be:
gotest.go:126: Test github.com/u-root/u-root/pkg/menu.TestChoose/hit_3 left in state paused:
As seen in #1684.
> teststate: give human-readable test results

- cmds/boot/boot/boot.go
- cmds/boot/pxeboot/pxeboot.go
- cmds/core/wget/wget.go
- pkg/boot/grub/echo_test.go
- pkg/boot/grub/grub.go
- pkg/boot/netboot/ipxe/ipxe.go
- pkg/boot/netboot/ipxe/ipxe_test.go
- pkg/boot/netboot/netboot.go
- pkg/boot/netboot/pxe/pxe.go
- pkg/boot/syslinux/syslinux.go
- pkg/boot/syslinux/syslinux_test.go
- pkg/curl/mock_schemes.go
- pkg/curl/schemes.go
- pkg/curl/schemes_test.go
Internally, we use SchemeWithRetries to retry our PXE/iPXE downloads due to spurious network config or network errors. The result is something that can spiral out of control sometimes:
```
[bmboot] 2020/05/07 00:57:32 Error: HTTP client: Get "http://10.244.211.18/ipxe.script": dial tcp 10.244.211.18:80: connect: connection refused                                                                                                                
[bmboot] 2020/05/07 00:57:48 Error: HTTP client: Get "http://10.244.211.18/ipxe.script": dial tcp 10.244.211.18:80: connect: connection refused                                                                                                                
[bmboot] 2020/05/07 00:57:48 Error: Too many retries to download http://10.244.211.18/ipxe.script …
```
> Ability to cancel boot downloads with context

- cmds/boot/boot/boot.go
- cmds/boot/pxeboot/pxeboot.go
- integration/generic-tests/pxeboot_test.go
- integration/generic-tests/testdata/pxe/pxelinux.cfg/default
- pkg/boot/menu/menu.go
- pkg/boot/netboot/netboot.go
- pkg/boot/netboot/pxe/pxe.go
- pkg/boot/syslinux/syslinux.go
- pkg/boot/syslinux/syslinux_test.go
from:
```go
type Config struct {
// Entries is a map of label name -> label configuration.	
Entries map[string]*boot.LinuxImage	
// DefaultEntry is the default label key to use.
//			
// If DefaultEntry is non-empty, the label is guaranteed to exist in
// `Entries`.
DefaultEntry string
}
func ParseConfigFile(ctx context.Context, s curl.Schemes, url string, wd *url.URL) (*Config, error)
```
to:
```go
func ParseConfigFile(ctx context.Context, s curl.Schemes, url string, wd *url.URL)
([]boot.OSImage, error)
```
- pxeboot now displays a menu with that ordered list, and if no option is chosen within 10 seconds, tries to boot them in the order that they're in the menu
> pxeboot gets a terminal boot menu

- cmds/boot/boot/boot.go
- pkg/boot/netboot/pxe/pxe.go
- pkg/boot/syslinux/syslinux.go
- pkg/boot/syslinux/syslinux_test.go
- multiboot is required for qubes
- 'menu default' and 'menu label' are used by debian installers and fedora installers
- debian installer also uses absolute paths, relative to the disk partition of course
> syslinux: multiboot support, support 'menu default' and 'menu label' directives

- .circleci/config.yml
- pkg/pty/pty_test.go
I don't have the energy to fix this at the moment, and the failing tests
have been bugging us for weeks now.
- pty test: disable under race
- integration tests: increase timeout
> deflake tests

- cmds/exp/smn/main.go
This tool allows probing of the System Management Network.
It allows reading many words at a time, but only setting one
word at a time on a northbridge. However the northbridges are specified
with a glob, as in the pci command, so one can dump all values of a given
range of SMN for several northbridges, e.g. one has a system accessible
via the cpu command, we can see parts of SMN as so:
cpu 10.0.1.18 ./smn -s 0000:*:00.0 13b102f0
If we want to further restrict it, and add more SMN addresses:
cpu 10.0.1.18 ./smn  -s 0000:[02468]0:00.0 13{b,c,d,e}102f0
> AMD System Management Network dumper

- cmds/boot/boot/boot.go
- cmds/boot/pxeboot/pxeboot.go
- integration/generic-tests/pxeboot_test.go
- pkg/boot/menu/menu.go
- pkg/boot/menu/menu_test.go
This PR adds a terminal UI boot menu to cmds/boot/boot to allow the user to choose which image to boot.
In order to do this cleanly, we should have the ability to unmount all file systems before actually execing the new OS.
Previously, `pkg/boot/menu` took care of both the kexec_load and exec steps. However, having both of those happen in `pkg/boot/menu` doesn't give the caller the ability to clean up the OS (like unmount file systems) before transferring execution to the new OS (or rebooting, or execing a shell).
So, before:
```go
type Entry interface {
Do() error
}
func (img boot.OSImage) Do() error {
img.Load()
boot.Execute()
}
func main() {
menu.ShowMenuAndBoot(os.Stdin, entries...)
panic("ShowMenuAndBoot should have kexec'd")
}
```
after:
```go
type Entry interface {
Load() error …
```
> Add boot menu to cmds/boot

- pkg/curl/mock_schemes.go
- pkg/curl/schemes.go
- pkg/curl/schemes_test.go
Internally, we use SchemesWithRetries on a bunch of netboot operations, but admittedly, it is not working very well.
Even with recent changes such as https://github.com/u-root/u-root/commit/18b0531231224d08946575b21a69824a5b0377d1 there are some cases where buggy HTTP servers will mess with us:
```
[netboot] 2020/06/19 00:18:31 Skipping configuring eth0 with lease IPv4 DHCP Lease IP 10.177.153.193/26
2020/06/19 00:18:31 Boot URI: http://.../ipxe.script/01-94-eb-2c-1a-2c-46
2020/06/19 00:18:32 Got ipxe config file http://.../ipxe.script/01-94-eb-2c-1a-2c-46:
#!ipxe
kernel http://../94-eb-2c-1a-2c-46.vmlinuz redacted
initrd http://../94-eb-2c-1a-2c-46.rd.gz
boot
[netboot] 2020/06/19 00:18:32 Error: Getting http://.../01-94-eb-2c-1a-2c-46: HTTP server responded with error code 500, want 200: …
```
> Refactor SchemesWithRetries

- cmds/core/sluinit/uinit.go
- pkg/boot/stboot/bootball.go
- pkg/complete/prefix.go
- pkg/securelaunch/launcher/launcher.go
- pkg/securelaunch/measurement/collectors.go
- pkg/securelaunch/measurement/cpuid.go
- pkg/securelaunch/measurement/dmi.go
- pkg/securelaunch/measurement/files.go
- pkg/securelaunch/measurement/storage.go
- pkg/securelaunch/policy/policy.go
- pkg/securelaunch/tpm/tpm.go
- pkg/tss/constants.go
- pkg/tss/pcr.go
- pkg/tss/tss.go
sluinit will now be using the new in house tss package. In this process, we made tpm a local variable to the sub-package called "tpm" inside securelaunch package. With this change, tpm variable does not need to be passed around in sluinit and other parts of securelaunch package, making all function calls lightweight.
> Use new tss package for securelaunch

- pkg/boot/initrd.go
- pkg/boot/initrd_test.go
This enables passing multiple initrds to the kernel.
> pkg/boot: add PadInitrds helper to align multiple initrds to 512b

- .circleci/config.yml
- cmds/core/dhclient/dhclient.go
- cmds/exp/rush/attr.go
- cmds/exp/rush/attr_linux.go
- cmds/exp/rush/rush.go
- cmds/exp/rush/tty.go
- templates.go
Start to get things to build on plan 9.
Create a plan9 template so nobody has to remember what builds
and what does not. Add a test for building for Plan 9 on amd64.
This should help force us walk the line on OS dependencies.
> Plan 9 support

- cmds/core/mount/mount.go
- pkg/boot/diskboot/device.go
- pkg/mount/block/blockdev.go
- pkg/mount/mount_linux.go
- pkg/mount/mount_linux_test.go
Before this PR, you have to specify `-t ext4` or some file system for mount to work.
After this PR, mount will read file systems from `/proc/filesystems` and automatically try all block file systems if `-t` is not specified.
> cmds/mount: try all block file systems in order if no fstype specified

- pkg/boot/initrd.go
- pkg/boot/initrd_test.go
- pkg/boot/linux.go
- pkg/boot/linux_test.go
- pkg/boot/multiboot.go
I wanted to make sure that when you embed a concatenated Initrd into a LinuxImage, it'd show the right name if you call the Stringer or the Label() function.
> boot: some improvements to CatInitrds

- cmds/core/elvish/edit/e2e_test.go
- cmds/core/elvish/edit/ui/render_test.go
- cmds/core/scp/scp_test.go
- cmds/exp/hdparm/hdparm.go
- cmds/exp/pflask/pflask.go
- pkg/boot/menu/menu_test.go
- pkg/boot/stboot/signature.go
- pkg/boot/systembooter/bootentry_test.go
- pkg/boot/systembooter/booter.go
- pkg/lockfile/lockfile_test.go
- pkg/mount/mount_linux.go
- pkg/mount/mtd/dat.go
- pkg/mount/scuzz/control.go
- pkg/mount/scuzz/sg_linux.go
- pkg/tarutil/tar.go
Quoting https://go-review.googlesource.com/c/go/+/236857:
"There's been plenty of discussion on the usage of these terms in tech.
I'm not trying to have yet another debate. It's clear that there are
people who are hurt by them and who are made to feel unwelcome by their
use due not to technical reasons but to their historical and social
context. That's simply enough reason to replace them."
Omitted a few places where we're trying to maintain 1:1 command-line API
compatibility (hdparm, ip). Also did not change PCI product names. Also
did not change a few places yet where I didn't understand the usage or
the code.
Also did not change vendored files.
I followed this guide: https://twitter.com/TwitterEng/status/1278733305190342656/photo/1
> Move to more inclusive language.

- cmds/boot/boot/boot.go
- cmds/exp/esxiboot/esxiboot.go
- pkg/boot/esxi/esxi.go
- pkg/boot/esxi/esxi_test.go
- pkg/boot/localboot/localboot.go
Adds detecting an ESXi install (or installer CD) to boot and its boot menu. Should deprecate `cmds/exp/esxiboot` eventually, I guess.
> boot: add ESXi booting to boot cmd

- cmds/boot/pxeboot/pxeboot.go
- cmds/boot/stboot/network.go
- cmds/core/dhclient/dhclient.go
- pkg/dhclient/dhclient.go
We used to wait on FlagUp, which actually gets set the moment you call
LinkSetUp, and has no bearing on whether the link is actually
operational. Sometimes the nic is still waiting for carrier and we
incorrectly proceed while the nic is still down.
> dhclient: wait on iface OperUp instead of FlagUp

- pkg/dhclient/dhcp6.go
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=684009
"Note that the dhcpv6 protocol doesn't have an option for a netmask. So
it is always /128 and routing is left to icmpv6 router advertisements."
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=684009
RFC5942, p.7 under "Host Rules":
```
The assignment of an IPv6 address -- whether through IPv6
stateless address autoconfiguration [RFC4862], DHCPv6 [RFC3315],
or manual configuration -- MUST NOT implicitly cause a prefix
derived from that address to be treated as on-link and added to
the Prefix List.  ...
```
and on p.8 under the heading "Observed Incorrect Implementation Behavior":
```
...  An address
could be acquired through the DHCPv6 identity association for non-
temporary addresses (IA_NA) option from [RFC3315] (which does not …
```
> dhcpv6: add IPv6 addresses as /128

- pkg/pci/pci.go
- pkg/pci/pci_linux.go
- pkg/pci/pci_linux_test.go
- pkg/pci/types.go
Sometimes we wish to block, match, reject devices based on some
criteria.
If this meets approval I'll add a few examples as tests. We could for example filter
on vendor id as string, name as string, type, etc.
> pci: allow bus Read() to take a ...Filter

- pkg/uroot/uroot.go
Formerly, directories like /sys and /proc were created at runtime. This
is problematic if the root filesystem is read-only.
> uroot: Create system directories at build time

- pkg/uroot/uroot.go
- pkg/vmtest/integration.go
- tools/mkinitramfs/main.go
- u-root.go
Not everything is Unix; make the DefaultRamfs a function
that returns a *cpio.Archive that is more kernel-specific.
> Make the DefaultRamfs kernel-specific

- u-root.go
Not all kernels run elvish, or any u-root shell, yet.
Make init() check the target OS and set the default
shell accordingly.
> u-root: make default shell kernel-specific

- cmds/boot/systemboot/main.go
- pkg/ipmi/ocp/ocp.go
This PR adds OEM ipmi POST end command in u-root. OpenBMC can receive
POST end after systemboot.
Signed-off-by: Tim Chu <Tim.Chu@quantatw.com>
> pkg/ipmi: Add OEM IPMI command for POST end

- CONTRIBUTING.md
- README.md
- docs/index.html
- docs/index.md
We moved to https://osfw.slack.com 🚚.
> Update references to Slack team

- pkg/boot/multiboot/internal/trampoline/trampoline_linux_amd64.go
- pkg/boot/multiboot/internal/trampoline/trampoline_linux_amd64.s
The crux of the problem is that we're trying to find these symbols'
location in order to insert some bytes at each. Until now, we've done
this by putting some strings before the symbol, and finding the string
in the trampoline, and then replacing the bytes in the function _after_
assuming a Go compiler's alignment of 16 bytes.
Go 1.15's https://github.com/golang/go/commit/30f8074e3510da8c39f879cfdbde600eb876a79e changes the default alignment of functions from 16 to 32 bytes.
We could decide to use 16 bytes for <= Go 1.14 and 32 bytes for >= Go
1.15. Instead, each symbol is treated like a function so we can use funcPC
to find their location. This fix works in Go 1.13, 1.14, as well as 1.15
without keying off an internal Go compiler alignment value.
Fixes #1803
Signed-off-by: Chris Koch …
> trampoline: find info,entry,magic location using funcPC

- README.md
- pkg/bb/bb.go
- pkg/bb/bb_test.go
- pkg/golang/build.go
- pkg/uroot/builder/bb.go
- pkg/uroot/builder/binary.go
- pkg/uroot/builder/builder.go
- pkg/uroot/test/bar/bar.go
- pkg/uroot/test/foo/foo.go
- pkg/uroot/uroot.go
- pkg/uroot/uroot_test.go
- tools/makebb/makebb.go
- u-root.go
- uroot_test.go
This required two user-visible changes:
* Added `-no-strip` to `makebb`
* Added ability to exclude certain commands from image build.
This is necessary to exclude commands known to offend against DCE
policy (but that will be fixed by Go 1.15 adoption).
Fixes https://github.com/u-root/u-root/issues/1808
Signed-off-by: Deomid "rojer" Ryabkov <rojer9@fb.com>
> Add a test that makes sure dead code elimination works

- pkg/boot/netboot/ipxe/ipxe.go
- pkg/boot/netboot/ipxe/ipxe_test.go
Enable to concat initrd files natively, similar to what was done earlier
in syslinux.go.
Signed-off-by: Robi Buranyi <rburanyi@google.com>
> boot: support CatInitrds in ipxe

- cmds/core/kexec/kexec_linux.go
Sometimes kernels are gzip'ed, and the naming does not always make sense.
Try to gunzip the kernel; if that succeeds, use that as for the multiboot
path. If not, proceed as before.
> kexec_linux: enable reading gzip'ed kernels

- .circleci/config.yml
- pkg/uroot/initramfs/archive.go
- pkg/uroot/initramfs/cpio.go
- pkg/uroot/initramfs/dir.go
- pkg/vmtest/integration.go
- templates.go
- tools/mkinitramfs/main.go
- u-root.go
- uroot_test.go
This is the first step to https://github.com/u-root/u-root/issues/1809
We collect size and build time stats, store as JSON file and expose them as a build artifact.
Signed-off-by: Deomid "rojer" Ryabkov <rojer9@fb.com>
> Collect build stats during CircleCI run

- pkg/boot/linux.go
- pkg/boot/multiboot/multiboot.go
- pkg/boot/util/reader.go
ARM64 kexec_file_load only processes ELF files.
But on many ARM64 Linux distros, the ELF file is
gzip'ed, with names like vmlinuz-x.y.z-whatever.
Move the tryGzipFilter code to boot/util, and
make it exported as TryGzipFilter, so that it
can be used in kexec as well as multiboot.
Not tested on ARM64. Will need to write a test if
this approach is acceptable.
> kexec: support gzip-ELF files so ARM64 works

- cmds/core/ping/ping.go
- cmds/core/ping/ping_linux.go
- cmds/core/ping/ping_other.go
Fixes #1009
Tested with:
```
$ go build && sudo ./ping -c 3 8.8.8.8
2020/09/15 22:51:10 84 bytes from 8.8.8.8: icmp_seq=1, time=32.758334ms
2020/09/15 22:51:11 84 bytes from 8.8.8.8: icmp_seq=2, time=33.057741ms
2020/09/15 22:51:12 84 bytes from 8.8.8.8: icmp_seq=3, time=32.89407ms
```
```
$ go build && sudo ./ping -6 -c 3 2001:4860:4860::8888
2020/09/15 22:50:52 64 bytes from 2001:4860:4860::8888: icmp_seq=1, time=34.242377ms
2020/09/15 22:50:53 64 bytes from 2001:4860:4860::8888: icmp_seq=2, time=33.450789ms
2020/09/15 22:50:54 64 bytes from 2001:4860:4860::8888: icmp_seq=3, time=37.98115ms
```
Signed-off-by: Andrea Barberio <insomniac@slackware.it>
> [cmds/core/ping] Implement ping6

- cmds/boot/pxeboot/pxeboot.go
This matches the options for dhclient.
> pxeboot: Add options to disable ipv4/ipv6 pxeboot

- pkg/boot/boot.go
- pkg/boot/linux.go
- pkg/boot/menu/menu.go
- pkg/boot/menu/menu_test.go
- pkg/boot/multiboot.go
Example usage from booting OpenSUSE with boot command:
Welcome to NERF's Boot Menu
Enter a number to boot a kernel:
01. Installation
02. Upgrade
03. Rescue System
04. Boot Linux System
05. Check Installation Media
06. Reboot
07. Enter a LinuxBoot shell
Enter an option ('01' is the default, 'e' to edit kernel cmdline):
> e
Select a boot option to edit:
> 1
The current quoted cmdline for option 1 is:
> "splash=silent console=ttyS0,115200,8n1"
* Note the cmdline is c-style quoted. Ex: \n => newline, \\ => \
Enter an option:
* (a)ppend, (o)verwrite, (r)eturn to main menu
> a
Enter unquoted cmdline to append:
> text
The new quoted cmdline for option 1 is:
> "splash=silent console=ttyS0,115200,8n1 text"
Returning to main menu...
Enter an option ('01' is the default, 'e' to edit kernel cmdline): …
> boot/menu: Add menu to edit kernel command line

- pkg/bb/bb.go
- uroot_test.go
u-root busybox builds are currently broken when using the u-root command outside of the u-root repo directory.
The `go.mod` change (https://github.com/u-root/u-root/pull/1821) failed to account for this possibility.
As a result, people saw stuff like this:
```console
chrisko@foo:~$ u-root core
2020/09/18 17:02:13 Disabling CGO for u-root...
2020/09/18 17:02:13 Build environment: GOARCH=amd64 GOOS=linux GOROOT=/usr/local/google/home/chrisko/sdk/go1.13 GOPATH=/usr/local/google/home/chrisko/go CGO_ENABLED=0 GO111MODULE=off
2020/09/18 17:02:13 Skipping package "/usr/local/google/home/chrisko/go/src/github.com/u-root/u-root/cmds/core/bind": no buildable Go source files in /usr/local/google/home/chrisko/go/src/github.com/u-root/u-root/cmds/core/bind
2020/09/18 17:02:31 error building: type …
```
> Fix u-root command outside of $GOPATH

- pkg/boot/menu/menu.go
`term` is in raw mode. Write \r\n whenever you would write a \n. When
testing in qemu, it might look fine because there might be another tty
cooking the newlines. In for example minicom, the behavior is different.
And you would see something like:
Select a boot option to edit:
>
Instead of:
Select a boot option to edit:
>
> menu: Put \r\n back into menu prints

- pkg/bb/bbmain/cmd/main.go
See the main.go for a long discussion.
Short form: we need a way to run on file systems without
symbolic links.
This change lets bb run as the interpreter in a #! file.
Due to differences in kernels, we mark the argument with a #!.
So, e.g., /bbin/ls on Plan 9 or a VFAT file system becomes:
Tested on Linux and Plan 9 via the following script:
192.168.0.7# cat /tmp/ls
192.168.0.7# /tmp/ls
acme.dump
bbin
...
The next change will be to have u-root optionally generate
these files instead of symlinks. Note that it will be required for
Plan 9 but will work on any Unix system as well.
> Modify the bb main so bb can be a #! interpreter

- pkg/mount/block/blockdev.go
- pkg/mount/mount_linux_test.go
localboot -guid cannot boot because the device name in the partition
map key doesn't have 'p' before the partition number, so it cannot find
the block device from the map. For instance, nvme0n12 should be nvme0n1p2.
Signed-off-by: Johnny Lin <johnny_lin@wiwynn.com>
> block: Add 'p' before the partition number when the last character of the device name is a digit

- pkg/boot/multiboot/module.go
- pkg/boot/multiboot/multiboot.go
- pkg/boot/multiboot/mutiboot_info.go
- pkg/boot/multiboot/mutiboot_info_test.go
- pkg/boot/multiboot/mutiheader.go
Renamed as of https://github.com/vmware/esx-boot/commit/868a4f89de7eb8f627ca42a5f3fcec35a6545d04
The name "Mutiboot" was originally a joke, meaning "VMware's mutated
boot". The name has proven to be too confusing, as it looks too much
like a typo for Multiboot.
> mb: rename mutiboot into ESXBootInfo

- cmds/boot/boot/boot.go
- pkg/boot/bootcmd/bootcmd.go
- pkg/boot/localboot/localboot.go
- pkg/mount/block/blockdev.go
- pkg/mount/loop/loop_linux.go
- pkg/mount/mount_linux.go
- pkg/mount/mount_linux_test.go
The Pool will allow the grub interpreter to keep track of mount points,
inform the caller of new mounts so it can unmount everything, prevent
re-mounting a partition unnecessarily and makes it easy to fake out
mounts points for testing.
> mount: Add pool for managing a list of MountPoints

- cmds/core/io/asmports.go
- pkg/memio/io_test.go
- pkg/memio/ioport_linux_386.s
- pkg/memio/ioport_linux_amd64.s
- pkg/memio/ports_linux.go
- pkg/memio/ports_test.go
Sometimes going via /dev/port is too slow.
Add support for x86 raw assembly IO. Add an init function that
does an iopl(3). This function need not succeed; it sets an
error value so that if an attempt is made to use those instructions,
and the iopl failed, the iopl error will be returned.
> pkg/iomem,cmds/core/io: Add support for x86 CPU IO instructions

- pkg/boot/boottest/json.go
- pkg/boot/grub/config_test.go
- pkg/boot/grub/grub.go
- pkg/boot/grub/testdata_new/debian_10_4_installed.json
- pkg/boot/grub/testdata_new/debian_9_install.json
- pkg/boot/grub/testdata_new/fedora_27_install.json
- pkg/boot/grub/testdata_new/qubes_3_2_boot.json
- pkg/boot/grub/testdata_new/rhel_7_8_another.json
- pkg/boot/grub/testdata_new/rhel_7_8_installed.json
- pkg/boot/grub/testdata_new/ubuntu_16_04_boot.json
Wikipedia says it best: "while "file:///foo.txt" is valid,
"file://foo.txt" is not, although some interpreters manage to handle the
latter".
File schemes must be absolute and expressed with three slashes '/'. It
seems url.Parse() and url.String() make this assumption at times, which
makes it difficult to modify the grub parser to continue emitting
incorrect URLs with two slashes.
This change permits the grub interpreter to emit file schemes with
absolute paths. The boottest package takes these paths and strips out
the non-hermetic portion in before comparing against the value in the
json.
> boottest: Correctly use file:/// schemes

- cmds/boot/pxeboot/pxeboot.go
- pkg/dhclient/iface.go
> Allow pxeboot to skip nics that may have already been bonded.

- integration/generic-tests/esxi_boot_test.go
- pkg/boot/esxi/esxi.go
- pkg/boot/esxi/esxi_test.go
- pkg/qemu/devices.go
Fixes booting ESXi from NVMe drives.
manual test:
```
integration.go:133: 2020/11/09 12:06:18 serial: ~2020-11-09T20:06:17.846Z cpu1:135638)Boot Successful
integration.go:133: 2020/11/09 12:06:18 serial: ~
integration.go:191: QEMU command line to reproduce TestESXiNVMe:
qemu-system-x86_64 -enable-kvm -nographic -kernel /tmp/uroot-integration301512720/kernel -append ' console=ttyS0 earlyprintk=ttyS0 uroot.vmtest UROOT_USE_9P=1' -initrd /tmp/uroot-integration301512720/initramfs.cpio -device nvme,drive=NVME1,serial=nvme-1 -drive file=/usr/local/google/home/chrisko/disk.raw,if=none,id=NVME1 -smp 2 -enable-kvm -cpu IvyBridge -m 8192 -device virtio-rng-pci -fsdev local,id=tmpdir,path=/tmp/uroot-integration301512720,security_model=mapped-file -device virtio-9p-pci,fsdev=tmpdir,mount_tag=tmpdir …
```
> esxi: use correct partition naming for NVMe

- pkg/dt/fdt.go
- pkg/dt/fdt_test.go
- pkg/dt/print.go
- pkg/dt/walk.go
One can now get the value of the named property on a node as a
[]byte, string, and uint64.
These conversion operations are needed to support FIT booting.
The printing changes have proven invaluable for debugging.
> fdt: add Bytes, AsString, AsU64 Node funcs, extend printing

- pkg/mount/switch_root_linux.go
The way `resursiveDelete` is written in `switch_root_linux.go`, there are many conditions under which the function will fail.  This results in two unexpected things:
1. The process of recursiveDelete is terminated at the first failure, potentially leaving much of the old root un-deleted;
2. The function returns an error, which gets passed to calling functions.  The `switch_root` command, in turn, will fail and never execute the specified `init`, meaning total boot failure.
It is actually common for some files/directories in old root to not be deleted.  For instance, they may reference underlying mount points, and sometimes this is intentional.  An example of this is the upper/lower mounts involved in switch_rooting into an overlayfs mount point (the specific case that lead me to this PR). …
> switch_root fails on recursiveDelete when it shouldn't

- pkg/boot/grub/grub.go
This gracefully skips unsupported constructions of the `search` command
such as:
search.fs_uuid be271b43-e570-4af7-9c9a-f9315636679d root hd0,gpt2
As seen on Ubuntu 20.04.
> grub: Add missing continues on parser errors

- cmds/boot/fbnetboot/main.go
Just noticed the two params are swapped.
Signed-off-by: Tobias Fleig <tfleig@fb.com>
> cmd/boot/fbnetboot: Fix https client setup debug output

- tools/testramfs/testramfs.go
This one-liner fixes an issue where `testramfs` wouldn't actually create a mount namespace because the wrong flags got passed to `SysProcAttr.Unshareflags`.
Signed-off-by: J. Lowell Wofford <lowell@lanl.gov>
> Fix issue where testramfs failed to create mount namespace

- cmds/core/cpio/cpio.go
- cmds/core/cpio/cpio_test.go
- pkg/cpio/fs_plan9.go
- pkg/cpio/fs_unix.go
For reproducible builds, the u-root command produces cpio entries
with inumber of 0. This has worked fine for years, until recently
an archive was created with an empty, zero-length directory, when it
failed on Harvey.
Zero-length entities in cpio archives indicate a zero length file, OR, a second
hard link to an already-written file, OR a directory.
Commit 301d69f0ab67540205bed49b191433a4c8456fe8 tried to handle
zero-length entries but only got 2 of the 3 cases right. A recent commit,
676b9e5fb2fc934d01384ea58187cf0575baf8a8 fixed directories,
but still had a few issues with Inums of 0, seen on Harvey.
The problem boils down to handling entries with an inumber of 0.
That is an illegal value for real file systems, but not illegal
per se. The code now uses it as a sentinal
to gate other …
> pkg/cpio,cmds/core/cpio: handle Inum 0 better, start numbering at 2

- pkg/uroot/builder/bb.go
- u-root.go
Not all kernels support symlinks, and not all file systems
on all kernels do. Symlinks are not as portable as we want.
For example, a simple u-root on a VFAT file system can not
be created.
It turns out there is a way to use shellbang files that is as
efficient as symlinks and much more portable.
Add an option to the busybox builder to generate shellbang files,
not symlinks.
TODO: update the tests. But this change is known to work on Plan 9.
Question: should we just move to shellbang files
only, given their more universal nature, or keep it as an option?
> provide an option to use shellbang, not symlinks, for busybox

- cmds/core/msr/msr.go
I forgot my own forth.
msr r glob register
works now
Note that if you want to use *, because * means times to forth, you MUST
quote with a '
msr r \'\* 0x202
reads all cpus,
you can also
msr r '[01]' 0x202
to read cores 0 and 1, and so on.
> Fix dumb MSR bug

- cmds/exp/disk_unlock/disk_unlock.go
- pkg/mount/scuzz/ata.go
- pkg/mount/scuzz/control.go
This PR adds a few changes:
* Try unique HSS values to avoid consuming password retry attempts.
* Have the option to have multiple retries for an HSS in case
there's failure for any reason other than an incorrect password.
* Check disk state more extensively before trying to unlock.
* Rescan SCSI host after unlock.
> Updates to disk_unlock command

- docs/index.html
- tricksandtips.md
Today during a discussion I realized people did not know you
could do this:
u-root -o /dev/stdout | cpio -ivt
to see what went into an image.
This led to the idea of a tricks and tips page where we can
accumulate these techniques.
> Add a 'tricks and tips' section

- cmds/core/cpio/cpio_plan9_test.go
- cmds/core/cpio/cpio_posix_test.go
- cmds/core/cpio/cpio_test.go
- pkg/cpio/fs_plan9.go
- pkg/cpio/sysinfo_plan9.go
- pkg/testutil/testutil.go
- pkg/testutil/testutil_plan9.go
- pkg/testutil/testutil_posix.go
Plan 9 uses different file type bits compared to unix. It uses
0x80000000 for directories and 0 for regular files. Adjust the mode so
that file modes are correct in the resulting archive.
Also get all cpio tests passing on Plan 9.
Signed-off-by: Fazlul Shahriar <fshahriar@gmail.com>
> cpio: fix file modes in archives created on Plan 9

- pkg/rand/random.go
- pkg/rand/random_std.go
- pkg/rand/random_unix.go
- pkg/rand/random_urandom.go
Plan 9 doesn't have /dev/urandom. The crypto/rand package in the
standard library implements its own pseudorandom generator seeded by
/dev/random on Plan 9. We just wrap the crypto/rand implementation,
adding a context.
Signed-off-by: Fazlul Shahriar <fshahriar@gmail.com>
> pkg/rand: add implementation for Plan 9

- pkg/uroot/uroot.go
Users frequently wish to include whole directories of executables.
Further, messages about ldd parsing are confusing when the
LDD on a non-regular-file fails.
Change the enumeration of the single file to a filepath.Walk.
Only try to enumerate ldd on files that are ELF files.
This change makes the use of -files a much better experience,
as well as allowing users to include whole directories
containing executables.
> uroot: recurse ldd directories and stop trying to ldd non-ELF

- cmds/core/mount/mount.go
- cmds/core/mount/mount_plan9.go
- pkg/namespace/parser.go
In the early days of u-root we had hoped to cleave to a more
plan 9-like model, in which the operations of mounting were
two separate commands. But the habit of typing mount by itself
to see mounts is not going to go away.
When mount is invoked with no args, it will try to read the mtab
from a number of standard places (Linux, Unix, OSX) or from
/proc/os.Getpid()/ns (Plan 9).
As an experiment, to try to keep the number of system calls down,
handle the "no args" case in init. We still end up with 300, which
is largish.
> mount: with no args, show mounts

- tools/testramfs/testramfs.go
As of ubuntu 20, on exit, the terminal was left
in raw mode, no echo, etc. etc.
This fixes, we hope, for the last time.
> testramfs: fix it so ttys work again

- pkg/memio/ports_linux.go
/dev/port on linux only does an outb/inb.
see drivers/char/mem.c::write_port and read_port.
This can cause real trouble for hardware. For example,
on an AMD Rome system, writing to 0xcf8 with a write
system call to /dev/ports hangs the system in a way the
BMC can not recover from. This is because the 4-byte write
is realized as four outb instructions, not one outl.
Hence, on Linux, the memio package should return an error
if anything other than a uint8 is written to /dev/port.
Note that this restriction does not apply to Plan 9,
which has a better design for port IO than Linux.
> pkg/io/ports_linux: only allow outb and inb

- cmds/core/cp/cp_test.go
- pkg/cp/cp.go
currently, given:
a/b/c
and
d/b/
cp -R a/ d/ will error when doing a recursive copy since d/b exists
use os.MkdirAll, not os.Mkdir
Fixes #1923
> cp: don't error if a destination directory exists

- cmds/core/cpio/cpio.go
- pkg/cpio/cpio.go
- pkg/cpio/newc.go
- pkg/cpio/newc_test.go
Currently, the cpio package can not read from pipes. This violates
a fundamental property of both cpio and Unix in general.
The fix might seem to be allowing creation of Readers from an os.File.
We could then see if the File in question implements Reader or
ReaderAt: if ok, rat := f.(ReaderAt) ...
and handle each case, transparent to the caller.
The problem is that some Go os.File types, such as Pipes,
advertise themselves as implementing ReaderAt but in fact do not
do so.
e.g.
r, _, _ := os.Pipe()
var b [2]byte
var _ io.ReaderAt = r
_, err := r.ReadAt(b[:], 0)
fmt.Printf("%v", err)
will fail, since whatever Go may think, Linux pipes do not allow a
seek, even when the offset is not changing. So the test
above will not work.
The Go runtime needs to be fixed, so that it does not claim
pipes …
> pkg/cpio, cmds/core/cpio: Allow reading from pipes

- cmds/core/tar/tar.go
- pkg/tarutil/tar.go
- pkg/tarutil/tar_test.go
For example, this includes most of the files in /proc and /sys under
Linux. The size cannot be found with a stat. No, you have to read the
whole file first to determine size. Since we cannot seek in a pipe (such
as when piping tar into gzip), this reads the file into a memory buffer.
This commit also adds the --no-recurison option at the same time. The
new unit test needs it to avoid taring all of /proc.
> tar: Support non-empty files with 0 size

- cmds/core/ls/ls.go
- cmds/core/ls/ls_test.go
If ls is given a directory as an argument, it always puts the directory name in quotes.  It should instead respect the Q flag.
Signed-off-by: Graham MacDonald <grahamamacdonald@gmail.com>
> ls: when provided with directory names, respect quote flag

- cmds/boot/systemboot/main.go
Continuing https://github.com/u-root/u-root/pull/1869 here.
Accepting coreboot loglevels now, (but still mapping them internally to quiet/verbose as that is all we have for now)
Testing done, I built a new image, set `systemboot_log_level=crit` and flashed it to a real devices.
Log lines from systemboot before: 219
Log lines from systemboot now: 117
DHCP debug dumps are quiet now, but it is still visible what is going one. There is still too much output from the disk mounting, but way less than before.
> systemboot: control debug level via VPD variable

- pkg/pci/pci_linux_test.go
The test is flaky because it assumed the machine you ran it on had no
two pcie devices which matching vendor and device id.
> pci: Fix flaky test

- cmds/core/cpio/testdata/dir-hard-link.go
We want to make sure the command still builds in the CI.
> Remove "+build ignore" from test command

- pkg/ls/fileinfo_plan9.go
We actually can get the username of the file owner, so do that instead of
just saying "bootes" for everything.
> Fix username reported by ls on Plan 9

- cmds/core/ls/ls_plan9.go
The lc script expects a -p flag on ls. We don't actually have to do anything
with it, since the default behavior of u-root ls is appropriate for lc.
> Implement -p flag for Plan 9 ls

- README.md
As title, the data on codecov is ready for showing a badge.
> docs: Add codecov badge in README.md

- pkg/mount/magic.go
- pkg/mount/mount_linux.go
The method of trying each file system type in turn to mount is
causing lots of confusion.
This change makes the code smarter. It opens the device,
ensures we can read the superblock, ensures the magic is known
(the magic numbers were pulled out of the kernel), ensures the
file system exists, and then tries to mount.
Gone is the "keep trying until it fails" model.
Some file systems can never be mounted writeable, and the code
further provides flags to be added to the mount flags so an error
message can be avoided.
> mount: use magic numbers for mounting

- cmds/exp/bzimage/bzimage.go
- cmds/exp/bzimage/bzimage_test.go
- cmds/exp/kconf/kconf.go
- pkg/boot/bzimage/bzimage.go
- pkg/boot/bzimage/header.go
- pkg/boot/bzimage/kver.go
- pkg/boot/bzimage/kver_test.go
* `kconf`: Reads kernel config from /proc/config.gz or a bzimage, optionally filtering
* `bzimage cfg`: Dumps embedded config in a bzimage to stdout
* `bzimage ver`: Dumps version info to stdout, similar to `file <bzimage>`
I tried to improve `bzimage`'s help output for other commands; someone with more knowledge, please verify that I got them correct.
In addition to the commands above, I added  supporting functionality in `pkg/boot/bzimage`.
> Add standalone kconf cmd, add ver and cfg subcommands to bzimage

- README.md
As reported in
https://github.com/u-root/u-root/issues/1954#issuecomment-790491114,
using 1.13 isn't required, but anything >= 1.13 should do.
> README: Go >= 1.13 is supported

- cmds/exp/pox/pox.go
- pkg/boot/stboot/bootball.go
- pkg/uzip/uzip.go
- pkg/uzip/uzip_test.go
The generated archive can now execute itself:
$ pox -cvsf date /bin/date
Creates a self-executing pox called "date".
$ ./date --utc
The archive is simultaneously an elf file and zip file:
$ file date
date: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked
$ unzip -z date
Archive:  date
/bin/date
Length      Date    Time    Name
---------  ---------- -----   ----
0  2021-03-02 08:07   /bin/
113864  2021-03-02 08:07   /bin/date
0  2021-03-02 08:07   /dev/
0  2021-03-02 08:07   /lib/
... elided ...
---------                     -------
4149104                     12 files
The trick is zip files place their header at the end of the file, while
elf files place theirs at the beginning. The zip file has a special
piece of metadata called the "comment" we use to store the …
> pox: Add self-executing pox archive

- pkg/crypto/ed25519_test.go
Use ioutil.TempDir to create a temporary folder, that's cleaned up after
the test.
Remove `{private,public}KeyPEMFile2` variables, as these were only used
to prevent conflicts with the existing files, and would also require to
create a `test` subfolder in the tempdir.
Given this folder is fresh for every test, we can just call them
`{private,public}_key.pem`.
Reported-In: https://github.com/u-root/u-root/issues/1955
> pkg/crypto/ed25519_test.go: don't create test artifacts in worktree

- pkg/boot/kexec/kexec_load_linux.go
- pkg/boot/kexec/memory_linux.go
- pkg/boot/kexec/memory_linux_test.go
Previously, it was assumed that all adjacent segments would have directly adjoining buffers in the virtual space.
Merging only worked on segments that were directly physically adjoining but not aligned to page size:
```
userspace: [0xff1000, 0xff1234] phys: [0x1000, 0x1234]
userspace: [0xff1234, 0xff2000] phys: [0x1234, 0x2000]
or
userspace: [0xff1000, 0xff1234] phys: [0x1000, 0x1234]
userspace: [0xff2000, 0xff2dcc] phys: [0x1234, 0x2000]
```
However, non-aligned addresses with holes and non-linear continuation are also valid, e.g. in the case where an image wants to  avoid padding with zeros:
```
userspace: [0xff1000, 0xff1234] phys: [0x1000, 0x1234]
userspace: [0xff1234, 0xff2234] phys: [0x2000, 0x2234]
```
Also, holes in the image that are not linear with the physical address space are …
> kexec: accurate merging of segments

- tools/checklicenses/checklicenses.go
Currently if more than one accept/reject pattern is specified,
checklicense will just ignore the check. This patch addresses the issue,
and also enforces that rejection rules have priority over acceptance
rules, in case there are colliding accept/reject matches.
Signed-off-by: Andrea Barberio <insomniac@slackware.it>
> [tools/checklicenses] Fix multi-pattern rules

- cmds/boot/fitboot/main.go
- pkg/boot/fit/fit.go
- pkg/boot/fit/fit_test.go
- pkg/dt/walk.go
bz config options are no longer prioritized by default but instead can be specified using the -config option.
Print list of configs on miss.
> Changes to fitboot to allow overriding the default FIT config.

- pkg/curl/schemes.go
Some tftpd clients fails when he windowsize is greater than 64. For
example tftp-hpa:
https://github.com/ClausKlein/tftp-hpa/blob/develop/tftpd/tftpd.c#L84
Also, according to rfc7440 (https://tools.ietf.org/html/rfc7440), the
performance levels out around 64.
> Change tftp window size to 64

- cmds/core/elvish/eval/exception.go
- cmds/core/uptime/uptime.go
- cmds/core/uptime/uptime_test.go
- pkg/tss/capabilities.go
This fixes the following errors:
pkg/tss/capabilities.go:48:17: conversion from uint32 to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
pkg/tss/capabilities.go:48:51: conversion from uint32 to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
pkg/tss/capabilities.go:48:83: conversion from uint32 to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
pkg/tss/capabilities.go:48:113: conversion from uint32 to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
cmds/core/elvish/eval/exception.go:196:10: Sprintf format %v with arg f causes recursive Error method call
--- FAIL: TestUptime/badDataInput (0.00s)
uptime_test.go:34: Mismatched …
> Make tests compatible with go1.15

- cmds/exp/netbootxyz/netbootxyz.go
- cmds/exp/netbootxyz/network.go
- pkg/boot/menu/menu.go
Working so far:
- Ubuntu 20.xx
- Debian
- Mint (based on Ubuntu 20.xx)
- Fedora
- Pop!_OS (based on Ubuntu 20.xx)
Ubuntu 18.xx and older use a different cmdline and are not yet handled
> Clean up some code and enable more distributions in netboot

- cmds/core/pci/pci.go
- pkg/pci/bits.go
- pkg/pci/bits_test.go
- pkg/pci/devices.go
- pkg/pci/pci.go
- pkg/pci/pci_linux_test.go
The original pci command was modeled after the Plan 9 version.
Hence the original u-root pci command was very simple. On Plan 9,
extra capabilities are added by extra commands. Kind of like Unix.
Simple is not the habit on Linux; the style of "one command that does everything
possible" is more the mode.
And it turns out users like that; they want more printing like lspci.
This is the first of series of changes to give users what they want.
For now, the command will show Control and Status registers for selected
devices when -v=1. The information presented is basically the same as lspci.
Note that for Status, INTx is presented in bit numbered order on pci, and lspci
for some reason puts it last. Your guess is as good as mine.
There is also, now, the ability to dump to JSON
for forensics …
> pkg/pci, cmds/core/pci: add more printing per requests from engineers

- pkg/ldd/ldd_darwin.go
- pkg/ldd/ldd_darwin_test.go
Making u-root on OSX requires making ldd a no op. The ldd
package on OSX will now continue to bring in symbolic links
but will not try to figure out libraries. OSX does not have
a stable kernel interface guarantee, unlike Linux, so the
ldd step has little value anyway.
With this change, these two commands work:
For OSX:
./u-root -defaultsh="" -initcmd="" github.com/u-root/u-root/cmds/core/date
For Linux
GOOS=linux ./u-root  -defaultsh=rush  github.com/u-root/u-root/cmds/core/init github.com/u-root/u-root/cmds/exp/rush
> OSX support

- cmds/exp/cbmem/cbmem_linux_test.go
- cmds/exp/cbmem/io.go
- cmds/exp/cbmem/main_linux.go
- cmds/exp/cbmem/types.go
The cbmem console can wrap and start writing new console
logs at the start. Correctly handle this case.
Add a test for a bogus cursor.
Add checks for bad cbmem pointers and handle them if they
occur.
fixes #1988
> cmds/exp/cbmem: add test and correctly handle wrapping

- pkg/termios/sgtty.go
- pkg/termios/termios_test.go
The printing will now be speed, rows, cols, integer-valued options,
boolean options which are true, boolean options which are false.
The integer-valued, true, and false options are sorted.
We're finding this makes it easy to quickly find variables.
> pkg/termios:Change String() for TTY struct

- cmds/core/find/find.go
- cmds/core/mkdir/mkdir.go
- pkg/golang/build.go
- uroot_test.go
For now, these simple hacks at least get us building.
The problems with "os" becoming "io/fs" are not simple.
Signed-off-by: Ronald Minnich <rminnich@gmail.com>
> Fix u-root build for go1.16

- pkg/boot/grub/grub.go
- pkg/mount/block/blockdev.go
- pkg/mount/block/blockdev_test.go
- pkg/ulog/klog_linux.go
Complement the "Filter...()" set of methods with `func (b BlockDevices) FilterPartLabel(label string) BlockDevices` using information from a `gpt.Table` according to the other methods instead of reading udev's `/dev/disk/by-partlabel/` list. The latter is usually not available in u-root.
> adapt FilterPartLabel

- pkg/rand/random_std.go
I am working on an userland network stack based on gvisor (https://github.com/containers/gvisor-tap-vsock). 
In order to add a DHCP to the virtual network, I use https://github.com/insomniacslk/dhcp.
It is using the rand pkg as a dependency. It is the only package which doesn't compile on Windows.
This change uses the default Golang implementation.
> Use Go crypto/rand as rand implementation for Windows

- cmds/core/ip/ip.go
This slipped in because in the earlier version there was no
one() function, and I did not want to type address all the time.
> cmds/core/ip: addr -> address

- pkg/mount/magic.go
With this patch it's possible to mount the VFAT filesystem that QEMU
uses to present a local directory as a filesystem with the parameter
-drive file=fat:rw:your_directory,format=raw,media=disk
Fixes #2025
> mount: Add magic number for QEMU virtual VFAT

- pkg/pci/lookup.go
- pkg/pci/pci.go
- pkg/pci/pci_linux.go
- pkg/pci/types.go
The recent bug fixes created other bugs. The testing is hard as we don't
yet have standard qemu tests for /sys/ and such.
> pkg/pci: fix bug in printing out vendor, dev, class

- README.md
- cmds/core/init/init_linux.go
- pkg/libinit/root_linux.go
Commit b6836a4 introduced a call to the `cmdline` package trying to open `proc/cmdline` before `libinit.CreateRootfs()` which result in an error and an empty `procCmdLine` inside the `cmdline` package. Since this variable is initialized only once, any further calls to the `cmdline` package will have no effect (operate on an empty `procCmdLine`).
The new part of commit b6836a4
```
// Backwards compatibility for the transition from uroot.nohwrng to
// UROOT_NOHWRNG=1 on kernel commandline.
if cmdline.ContainsFlag("uroot.nohwrng") {
os.Setenv("UROOT_NOHWRNG", "1")
log.Printf("Deprecation warning: use UROOT_NOHWRNG=1 on kernel cmdline instead of uroot.nohwrng")
}
```
just needs to go anywhere after the rootfs was created. This approach here is just a proposal, feel free to suggest …
> Fix cmdline

- cmds/exp/rush/info.go
- cmds/exp/rush/parse.go
- cmds/exp/rush/rush.go
- cmds/exp/rush/time.go
Add builtin info command so we can better see what it thinks is going on
use \r to break lines too
rename runtime function to runtimecmd, since runtime is a package :-)
It is a builtin because in bare metal environments like tamago debugging
is very hard otherwise.
> cmds/exp/rush: add changes for tamago

- cmds/boot/pxeboot/pxeboot.go
This can be useful when something goes wrong. The information will be printed in console for later debugging.
> Print information when netboot failed

- pkg/boot/esxi/esxi.go
Use partNo to get the correct name.
Signed-off-by: Terry Tang <terrytang@google.com>
> Fix wrong device name of esxi image.

- cmds/core/time/time.go
- cmds/core/time/time_test.go
This command was originally part of rush, as a builtin.
It seems we need it standalone.
> cmd/time: add a time command

- pkg/watchdogd/watchdogd.go
> Do not print every ping of the watchdog

- .circleci/config.yml
The default is for each test to analyze only the package being tested.
This should increase test coverage.
> Cover all packages, not just package under test

- pkg/golang/build.go
The old format was deprecated see "go help build".
> Separate tags by commas

- cmds/exp/netbootxyz/netbootxyz.go
- pkg/boot/bootcmd/bootcmd.go
- pkg/boot/menu/menu.go
- pkg/boot/menu/menu_term.go
- pkg/boot/menu/menu_test.go
Add option to disable bootmenu edits and updated menu logic
Removed the spawned function in ShowMenuAndLoad in favor of
file.SetDeadline(). Switched from Stdin to TTY to support this.
Previous tests for menu.Choose spawned a xterm shell and had to use manual sleeps prevent races.
The menu class used methods and member variables of xterm so a wrapper interface/class were made to support mocking+injection
This shaved ~20s off the test time
> Add option to disable bootmenu edits

- pkg/boot/bootcmd/bootcmd.go
- pkg/mount/mount_linux.go
Error messages during boot
```
Enter an option ('01' is the default, 'e' to edit kernel cmdline):
>
[diskboot] 2021/07/30 16:20:32 Failed to unmount: directory not empty
[diskboot] 2021/07/30 16:20:32 Nothing to boot.
```
The root cause was the wrong path of rmdir in (p *Pool) Mount().
Verified that this was caused by rmdir() with new error message format
```
2021/08/06 10:21:05 Failed in UnmountAll: (Rmdir) directory not empty
2021/08/06 10:21:05 executing command "/bin/defaultsh" with args []
u-root-mounts716997181
~/# ls /tmp/u-root-mounts716997181
sda
sdb1
sdb2
```
> Fix failed to unmount error message

- pkg/vpd/vpd.go
- pkg/vpd/vpd_test.go
- tools/vpdbootmanager/add.go
- tools/vpdbootmanager/add_test.go
- tools/vpdbootmanager/get.go
- tools/vpdbootmanager/get_test.go
- tools/vpdbootmanager/main.go
- tools/vpdbootmanager/main_test.go
The `get` command in vpdbootmanager allows to read VPD variables.
Example:
```
~/# vpdbootmanager get firmware_version
firmware_version(RO) => 0.0.0
```
If no arguments are passed to `get`, all the variables are read:
```
~/# vpdbootmanager get
firmware_version(RO) => 0.0.0
internal_versions(RO) => {
"build_id": "6bc0645",
...
}
}
}
~/#
```
Signed-off-by: Andrea Barberio <insomniac@slackware.it>
> [tools/vpdbootmanager] Added command `get`

- cmds/core/backoff/main.go
- cmds/core/backoff/main_test.go
backoff will run a command, repeatedly, with exponential
backoff, until it succeeds or a timeout is passed.
The default timeout is zero, meaning "run until success".
The timeout is specified as a standard string duration,
e.g. 30s, 10m, and so on.
> cmds/core/backoff: simple backoff command

- cmds/core/wget/wget_test.go
Our internal infra runs the subcommand under the wrong working
directory.
> Use absolute path in wget tests

- pkg/golang/build.go
Go's caching is mature and can be trusted to detect changes.
> [pkg/golang] Do not force rebuild of all packages

- cmds/boot/fbnetboot/main.go
- cmds/core/ntpdate/ntpdate.go
- go.mod
- go.sum
- pkg/ntpdate/ntpdate.go
- vendor/github.com/insomniacslk/dhcp/dhcpv4/server4/conn_unix.go
- vendor/github.com/insomniacslk/dhcp/dhcpv4/server4/conn_windows.go
- vendor/github.com/insomniacslk/dhcp/dhcpv6/dhcpv6message.go
- vendor/github.com/insomniacslk/dhcp/dhcpv6/option_ntp_server.go
- vendor/github.com/insomniacslk/dhcp/dhcpv6/options.go
- vendor/github.com/insomniacslk/dhcp/dhcpv6/server6/conn_unix.go
- vendor/github.com/insomniacslk/dhcp/dhcpv6/server6/conn_windows.go
- vendor/github.com/insomniacslk/dhcp/interfaces/bindtodevice_darwin.go
- vendor/github.com/insomniacslk/dhcp/interfaces/bindtodevice_windows.go
- vendor/github.com/insomniacslk/dhcp/netboot/netconf.go
- vendor/modules.txt
Having valid time is important for HTTPS boot to work, as it prevents
certificate validation failures due to invalid system time.
This PR adds NTP support, enabled by default, to query NTP servers
hard-coded in the image or returned by DHCPv4/v6.
Failure to set time is not fatal and boot proceeds regardless.
With no additional configuration and assumiong no NTP servers
returned by the DHCP server, it's a no-op.
Example of successful execution: https://gist.github.com/rojer9-fb/893ac04361eb3da414d73e5b9befd7e5
Signed-off-by: Deomid "rojer" Ryabkov <rojer9@fb.com>
> [fbnetboot] Add NTP support

- pkg/mount/block/blockdev.go
- pkg/mount/mount_linux_test.go
This allows filtering for block devices that have a partitions 1,2,4
> Add Block device filter checking for required partitions 

- tools/makebb/makebb.go
In scripts, as used in, e.g., Harvey, it is important to
know what commands are built into a bb.
The glob passed to makebb will not always be the same
as the actual commands that get built (there might be a
match for a command that does not get built due to build
constraints).
The -c switch to bb will now list the commands that get built in.
> tools/makebb: add -c switch so it lists commands

- .cirrus.yml
"""
.cirrus.yml#L8
you've probably meant template_task
"""
> cirrus ci: fix results parsing warning.

- cmds/boot/systemboot/main.go
Signed-off-by: Tim Chu <Tim.Chu@quantatw.com>
> systemboot: add Quanta S9S to supported OEM product list

- pkg/spi/spidev_linux_test.go
This corrects the following:
* The original code's cast from a3 to `*reflect.SliceHeader` does not
make sense. Doubly so since the `Data` field also gets set to a3.
* Added a `KeepAlive` for `a3` since it is cast to a uintptr and has
nothing to keep it alive. It looks like this was the original intent,
but the line was commented out for some reason.
> spi: Improve GC safety in spidev test

- integration/generic-tests/uefiboot_test.go
Temporary increase QEMU memory to 4GB to unblock the flaky integration
test. This is because payload assume some memory mapping after APIC and
it may not be accessible in QEMU6. We will need to root cause this.
> Increase uefiboot's memory to 4096

- .circleci/config.yml
- pkg/boot/linux.go
- pkg/boot/linux_test.go
- pkg/mount/magic.go
- pkg/mount/mount_linux_test.go
...and under tmpfs.
One caveat discussed is original file may be opened
for writting, which kexec file load does not like.
This change does not proactively prevent that from
happening within linux.go, but now allow it to fail
in that case.
One thing I can do is write, in golang, lsof, and matching
/proc/\*/fd/\* sym linked file against original file name
and see if there is any currently opening it, and throw
an error to kexec load caller, but that is not giving
any advantage over let kexec file load propogating up
the error. One benefit being we can do sth custom when
that happens, say proactively purging / closing them.
That just lead us into another hole of mess. So I prefer
to "Leap Before You Look" here for simplicity.
> linux kexec: skip kernel / initrd copying when source is a regular file. 

- cmds/boot/pxeboot/pxeboot.go
This PR fixes the missing routing information in debug message.
> Print IPv6 routing table in the debug message

- cmds/core/elvish/getopt/getopt.go
- cmds/core/ps/ps_test.go
- cmds/core/readlink/readlink_test.go
- cmds/core/scp/scp_test.go
- cmds/exp/ash/parse.go
- cmds/exp/rush/parse.go
- cmds/exp/validate/validate.go
- pkg/mount/scuzz/control.go
- pkg/txtlog/txtlog.go
Housecleaning of string handling:
- removing unneeded function calls
- replace for loop with automatic appending
- replace `strings.Index(X, Y) == -1 {` constructs with `strings.Contain(X,Y)`
> improve string handling

- integration/gotests/gotest_test.go
One of the mount test alone need to claim large memory, e.g.
pkg/mount/gpt/gpt_test.go:
disk = make([]byte, 0x100000000)
This would cause a OOM in test.
Example:
```
fatal error: runtime: out of memory~
~
runtime stack:~
runtime.throw(0x172f2a, 0x16)~
/usr/local/go/src/runtime/panic.go:1116 +0x54~
runtime.sysMap(0x4004000000, 0x100000000, 0x27cc58)~
/usr/local/go/src/runtime/mem_linux.go:169 +0xbc~
runtime.(*mheap).sysAlloc(0x261240, 0x100000000, 0x4100400000, 0xffffffffffff)~
/usr/local/go/src/runtime/malloc.go:727 +0x42c~
runtime.(*mheap).grow(0x261240, 0x80000, 0x0)~
/usr/local/go/src/runtime/mheap.go:1344 +0x98~
runtime.(*mheap).allocSpan(0x261240, 0x80000, 0x7fc5220100, 0x27cc68, 0x7fc5229978)~
/usr/local/go/src/runtime/mheap.go:1160 +0x5f8~
runtime.(*mheap).alloc.func1()~ …
```
> integrations: bump mem to 5G for gotests

- .github/workflows/go.yml
- go.mod
- go.sum
- vendor/github.com/pierrec/lz4/v4/internal/lz4block/blocks.go
- vendor/modules.txt
In our defense, this was done before go modules existed.
Had to change the workflow too.
> retract versions v1.0.0-v7.0.0

- pkg/dhclient/dhcp6.go
- pkg/uio/archivereader_test.go
...so don't blindly reference further.
Internally, we ran into a case where DHCPv6 REPLY
came back, but with no `IANAOption` with a IP address
that triggered the code path, where `Packet6.Lease()` is
nil, and caller is printing out the `Packet6.String()`
I can add a test later if preferred. but I have to go now, so
just fix the issue.
also reduce the duration needed for archivereader_test, which
otherwise would flakily timeout in Circle CI.
> dhclient: Packet6.Lease() can be nil

- pkg/uroot/uroot.go
- pkg/uroot/uroot_test.go
It's important to have an init. The suggested fix, when there is no init,
will lead people down the primrose path, onto the on ramp of the
Information Highway To Hell: they might build an image with no init,
when what really happened is they misconfigured something.
This has happened.
Add a bit more info to this error, in the hopes of making people take
a second look.
It's a lot more wordy now but maybe that is worth it?
% ./u-root github.com/u-root/u-root/cmds/core/date
.
.
.
2021/03/17 16:15:12 could not create symlink from "init" to "init": command \
or path "init" not included in u-root build: specify -initcmd="" to \
ignore this error and build without an init (or, did you specify a list, \
and are you missing github.com/u-root/u-root/cmds/core/init?)
Signed-off-by: Ronald G. Minnich …
> Add more info when init is missing

- cmds/core/cat/cat.go
- cmds/core/cat/cat_test.go
Restructure main
Add test for empty arguments
Add test for file not exist
Add test for io copy fail
> cover/cmds/core/cat 

- cmds/core/chmod/chmod_test.go
Ending up with the entire tree as 555 causes, sometimes:
testing.go:967: TempDir RemoveAll cleanup: unlinkat /tmp/TestChmodRecursive2303678599/001/L1_A/L2_A: permission denied
> Delete one part of recursive test that flakes testing package

- u-root.go
The build process now defaults to the new gobusybox UNLESS
GO111MODULE is set to off.
> u-root: default to building with gobusybox if GO111MODULE!="off"

- pkg/uroot/builder/gbb.go
- pkg/uroot/builder/gbb_test.go
- u-root.go
Previously, we added the gobusybox builder as a test.
Add it the way it should be added:
- make a new builder, gbb, and type GBBBBuilder that implements builder.Builder
This new type uses the u-root/gobusybox package
- extend the string handling for the build option to include gbb
- add a test for the gbb builder
Remaining is the question of whether to pull gobusybox into u-root.
Is this separation the right thing in the long term? gobusybox and
u-root are very tightly connected.
> u-root: add the new go builder the right way

- pkg/spidev/spidev_linux_test.go
This is an error caught by go vet 1.17. Fixed by using a safe way
of pointing data.
For more information:
https://dev.to/jlauinger/sliceheader-literals-in-go-create-a-gc-race-and-flawed-escape-analysis-exploitation-with-unsafe-pointer-on-real-world-code-4mh7
> pkg/spidev/spidev_linux_test.go: fix invalid usage of reflect.SliceHeader

- go.mod
This versions were done before migrating to modules. **This
commit must be taged with ~~v7.0.1~~ v1.0.1**and retracts versions
v{1,2,3,4,5,6,7}.0.0 and ~~v7.0.1~~ v1.0.1 too.
Comments at the retract statements will show up when using
go get, go list, etc.
Publishing v1, v2, ... will be possible as v1.0.1, v2.0.1, ...
> retract versions v1.0.0-v7.0.0 2nd try

- pkg/strace/syscall_linux.go
Use the syscall method instead of repeating the type conversions for
the syscall.Stat_t Atim/Ctim/Mtim members.
> strace: use syscall.Timespec.Unix

- .circleci/config.yml
- .circleci/images/test-image-amd64/config_linux5.10_x86_64.txt
Add ipmi capabilities to amd64 kernel
Add bmc emulation and ipmi support to qemu for test-image-amd64
> CI/Integrate IPMI capabilities to kernel and qemu for integration tests

- cmds/core/mknod/mknod_linux_test.go
We have some issues with coverage report, Maybe this fixes it.
> cmds/core/mknod: Remove SkipIfNotRoot

- pkg/bb/bb_test.go
There's no reason to disable this test. It does not interfere with
gobusybox or modules.
> Re-enable pkg/bb test.

- cmds/core/cat/cat_test.go
- cmds/core/hexdump/hexdump_test.go
- cmds/core/ls/ls_linux_test.go
- cmds/core/ls/ls_test.go
- cmds/core/mkdir/mkdir_test.go
- cmds/core/mknod/mknod_linux_test.go
- cmds/core/mv/mv_test.go
- cmds/core/sync/sync_test.go
- pkg/cp/cp_test.go
- pkg/memio/ports_linux_test.go
- tools/vpdbootmanager/add_test.go
- tools/vpdbootmanager/main_test.go
A small testing enhancement.
Use `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
Reference: https://pkg.go.dev/testing#T.TempDir
> testing: use `T.TempDir` to create temporary test directory

- cmds/core/ls/ls.go
- cmds/core/ls/ls_linux_test.go
- cmds/core/ls/ls_test.go
Test was flaky due to how test output was written out and how it is parsed.
cmds/core/ls: collect output via io.Writer so test infra can parse test output correctly
Otherwise, the output of the command interferes with our test infra's
parsing of test state:
```
integration.go:145: 2022/02/21 00:22:24 serial: === RUN   TestListName/ls_classify_=_true~
integration.go:145: 2022/02/21 00:22:24 serial:     --- PASS: TestListName/ls_classify_=_true (0.00s)~
integration.go:145: 2022/02/21 00:22:24 serial: -rw-r--r--{"Time":"2022-02-21T00:22:22.771036451Z","Action":"pass","Package":"github.com/u-root/u-root/cmds/core/ls","Test":"TestListName/ls_directory_=_true","Elapsed":0}~
integration.go:145: 2022/02/21 00:22:24 serial:  circleci {"Time":"2022-02-21T00:22:22.774185019Z","Action":"pass","Package …
```
> Fix flaky ls test

- pkg/termios/termios_darwin.go
- pkg/termios/termios_linux.go
- pkg/termios/termios_test.go
- pkg/termios/var_unix.go
The Termios type is intended to be a value, not a reference,
so that it can be modified or saved and reused. Dereferencing
a *Termios should yield a value that, when changed, does not
affect the original.
For example, the Raw() function returns a Termios intended
to be used later to reset the terminal state, and modifies
a copy.
As part of bc40a4c6c, "make termios less linux/unix-specific.",
a Termios struct was created containing the *unix.Termios that
had been passed around directly.
This broke semantics of functions like Raw and MakeRaw,
which depend on being able to return an unmodified struct value
while modifying a copy of the one passed in. Since the passed-in
*Termios contained a *unix.Termios, copying just mean we had two
Termios using the same *unix.Termios.
This change fixes a …
> termios: make struct Termios contain unix.Termios, not *unix.Termios

- cmds/core/date/date.go
- cmds/core/date/date_test.go
- cmds/core/date/date_unix.go
cmds/core/date:
* Adatp TestGetTime to not be flaky.
> Fix flaky tests of cmds/core/date

- cmds/core/truncate/truncate.go
Only call flag.Usage in main(), not the truncate function.
The error messages from the test are very confusing otherwise.
> Fix truncate to not drop garbage in integration tests

- cmds/core/comm/comm.go
- cmds/core/comm/comm_test.go
The comm command was dumping lots of noise into the integration
tests, since the comm() function calls flag.Usage, which exits, loudly.
Further, the tests were wrong. comm requires two arguments.
> cmds/core/comm: fix it to handle error

- cmds/exp/ssh/destination_test.go
- cmds/exp/ssh/main.go
- cmds/exp/ssh/utils_linux.go
- cmds/exp/ssh/utils_plan9.go
- go.mod
- go.sum
- vendor/github.com/kevinburke/ssh_config/.gitattributes
- vendor/github.com/kevinburke/ssh_config/.mailmap
- vendor/github.com/kevinburke/ssh_config/AUTHORS.txt
- vendor/github.com/kevinburke/ssh_config/LICENSE
- vendor/github.com/kevinburke/ssh_config/Makefile
- vendor/github.com/kevinburke/ssh_config/README.md
- vendor/github.com/kevinburke/ssh_config/config.go
- vendor/github.com/kevinburke/ssh_config/lexer.go
- vendor/github.com/kevinburke/ssh_config/parser.go
- vendor/github.com/kevinburke/ssh_config/position.go
- vendor/github.com/kevinburke/ssh_config/token.go
- vendor/github.com/kevinburke/ssh_config/validators.go
- vendor/modules.txt
This client works on Plan 9 and Linux. It takes a normal user@host
destination spec. Note that it currently only supports password
authentication.
> Add a rudimentary ssh client.

- cmds/core/init/fns_other.go
- cmds/core/init/fns_unix.go
But it got introduced in https://go.googlesource.com/go/+/c3fcd01 and
that broke some things.
u-root is supposed to work on Go 1.17.
> unix build tag does not exist

- pkg/dt/node.go
the Walk(), Find(), FindAll(), LookProperty() functions all returned a
copy of the node/property instead of a reference to the value itself. By
changing it to reference, the very same library is now capable of both
traversing and also manipulating the data.
Signed-off-by: Robi Buranyi <rburanyi@google.com>
> change the lookup functions to return references

- cmds/exp/gosh/gosh.go
I started gosh for the first time and was greeted with
"This will only work with a working framebuffer for now"
and I wasn't sure if it meant that the shell altogether would only work
with a framebuffer.
> gosh: fix ambiguous info message

- cmds/exp/smbios_transfer/smbios_transfer.go
The main user of smbios - openbmc/smbios-mdr has made some changes where they require `smbios_entry_point` (https://github.com/openbmc/smbios-mdr/commit/0435a483afb10a5eabe7ae93f07fbb2d2265e53f) to be appended to the end of the DMI as found while working on https://gerrit.openbmc-project.xyz/c/openbmc/smbios-mdr/+/51500.
> Append the smbios_entry_point to the end of DMI

- cmds/core/poweroff/poweroff_linux.go
There are just enough uses for a command with no options,
and no arguments, to make this useful.
> Add a power off command

- pkg/boot/syslinux/syslinux.go
Search for `extlinux.conf` following the order from https://wiki.syslinux.org/wiki/index.php?title=Config
> Add extlinux support to syslinux pkg

- cmds/core/shutdown/shutdown_linux.go
- cmds/core/shutdown/shutdown_linux_test.go
when the tests were added for shutdown, they broke the command.
Even the most basic usage:
shutdown
would fail. Further, there were a few mistakes left over from the conversion.
Finally, there were magic numbers in the test that did not need to be magic.
So:
move shutdown_test.go to shutdown_linux_test.go, since it is linux specific.
remove magic numbers in the test -- use constants from unix
clean up function, remove support for things we don't need.
> shutdown: fix it, it was broken by test creation

- pkg/boot/kexec/kexec_linux_implemented.go
`sys_kexec` does not distinguish if it made a file
load call or classic kexec call.
We now have code path for classic kexec call, we
need lore accurately.
We were pondering why console log saying the classic
sys call function not implemented, even after we
enabled it during build (CONFIG_KEXEC). But it
turns out that was a file load call, and our test
kernel did not have it enabled (CONFIG_KEXEC_FILE).
> boot/kexec: log accurate syscall for file load.

- pkg/cpio/fs_unix.go
If a same file is specified as source for multiple extra files,
e.g. -files 'README.md:a.txt' -files 'README.md:b.txt', the
contents of the second and subsequent files, e.g. b.txt, are empty.
This is because `ReaderAt` is not initialized after the second time
if the inode of source is duplicated.
```bash
$ go run . -files 'README.md:a.txt' -files 'README.md:b.txt' cmds/core/{init,elvish}
$ lsinitramfs -l /tmp/initramfs.linux_amd64.cpio
-rw-rw-r--   0 root     root        16228 Jan  1  1970 a.txt # file is written successfully.
-rw-rw-r--   0 root     root            0 Jan  1  1970 b.txt # file is empty.
```
> cpio: fix to allow a same file as source for multiple extra files

- integration/testcmd/common/common.go
- pkg/mount/mount_linux.go
- pkg/mount/mount_linux_test.go
Remove the code that always does a MkdirAll in mount.Mount.
Making the mountpoint by default is nonstandard behavior.
It was introduced in 74c94c.
It must have been useful, I assume, else we would not have done it?
This code can have all kinds of confusing consequences, e.g.
imagine a script that does this:
mount /dev/sda1 /mnnt
ls -l /dev/mnt
/mnnt will be created, but it's not what the caller intended by
any means!
Further, mount.Mount does not allow callers to set the mode to other than
666.
At the same time, the behavior can be useful, so change
mount.Mount as follows:
func Mount(dev, path, fsType, data string, flags uintptr, opts ...func() error)
Then, callers wishing to do a few things ahead of time can do so:
mount.Mount("none", dst, fstype, "", 0, os.Mount(dst, 0o644))
Note that …
> pkg/mount: do not MkdirAll the mountpoint by default

- integration/.gitignore
- integration/RUNLOCAL
RUNLOCAL stopped working some time ago, and never quite worked like the
CI did.
This change fixes RUNLOCAL to do what the CI does, with the same kernel and
qemu the CI uses.
Tested and working for amd64 and arm64 on an amd64 host.
> Fix RUNLOCAL to work

- pkg/libinit/proc_linux.go
- pkg/libinit/root_linux.go
syscall has been deprecated in Go 1.4. See https://pkg.go.dev/syscall
> pkg/libinit: migrate from syscall to golang.org/x/sys

- .circleci/config.yml
- pkg/uroot/builder/builder.go
- pkg/uroot/uroot.go
This is an attempt to trace down a CI issue probably occuring because of memory pressure or locking.
EDIT: As the go.mod file gets locked by the go toolchain, it was necessary to run highly parallel tests with GOMAXPROCS=1 which is the major change of this PR.
> Change default Busybox backend to GBB

- cmds/exp/syscallfilter/main_linux.go
- integration/gotests/gotest_test.go
- pkg/syscallfilter/doc.go
- pkg/syscallfilter/syscallfilter_linux.go
- pkg/syscallfilter/syscallfilter_linux_test.go
system call filter
This commit includes the systemcallfilter package and a command which uses it.
The package defines a type, Cmd, which embeds an exec.Cmd and a set of event filters.
> System call filter package and sample command

- cmds/core/grep/grep.go
- cmds/core/grep/grep_linux.go
- cmds/core/grep/grep_plan9.go
- cmds/core/grep/grep_test.go
With pflag, you can now say `grep -rn`. The long names match GNU.
Also adds `-e`, `-h`, and `-n` flags. This brings us close to parity with
Plan 9 grep, although we're still missing `-L`, `-f`, and `-b`.
Also fixes a bug in the -l flag, where it wasn't outputting newlines between file names.
> Convert grep to use pflag package, and add some functionality.

- u-root.go
As 2256 got merged, this adjusts the print of the previous "version" accordingly.
> Change print to commit directly before the merge of #2256

- .circleci/config.yml
a few runs from recent PRs showes they were
flapping between succeeded and failed due to
timeout. Bumping up the max time in hopes they
will be more reliable.
> Bump up integration tests timeout.

- pkg/acpi/rsdp_linux.go
fixrsdp wants to get rsdp from EBDA or low memory region. 
The searching priority of EFI system table should be the lowest.
> Update rsdpgetter order

- u-root.go
The current value of -uroot-source is now "."
For almost all users, this will be the right value. This is
preferable to the previous value, "", which was wrong for
ALL users, and, when not set, resulted in a confusing
error message.
Further, perform a simple test to see if the directory
cmds/core exists at -uroot-source, and print a hopefully
helpful error message if it does not.
This will lessen another surprise that came with modules support.
> u-root.go: set a reasonable and checked default for -uroot-source

- cmds/exp/rush/attr.go
- cmds/exp/rush/attr_linux.go
- cmds/exp/rush/attr_linux_test.go
- cmds/exp/rush/cd.go
- cmds/exp/rush/cmd_test.go
- cmds/exp/rush/info.go
- cmds/exp/rush/parse.go
- cmds/exp/rush/parse_test.go
- cmds/exp/rush/rush.go
- cmds/exp/rush/rush_test.go
- cmds/exp/rush/tty.go
- cmds/exp/rush/tty_linux.go
- cmds/exp/rush/tty_test.go
While elvish is the standard shell, and gosh is the shell we want
to have, rush still has its uses: it's simple, and uses the
most basic tty line discipline, resulting in minimal stress
on potentially flaky hardware.
We are seeing strange lockups on the serial console on some risc-v
boards, and it would be useful to have a simple shell, running
with no overly fancy usage of the serial console, because the
plethora of escape sequences elvish and similar shells send has
been shown to occasionally lockup the FIFOs on the hardware.
In at least one case, the lockup comes and goes depending on Go
version, which is also concerning. We need a fallback, dead simple
shell, to see if the problem is related to one of the tty packages
or some other IO problem on serial lines..
Finally, when using …
> Revert 83ffd49111fcae42d80f8d9e21a282fa5b99cd8c: restore cmds/exp/rush

- go.mod
- go.sum
- pkg/logutil/logutil.go
- pkg/logutil/logutil_test.go
- vendor/github.com/nanmu42/limitio/.gitignore
- vendor/github.com/nanmu42/limitio/LICENSE
- vendor/github.com/nanmu42/limitio/README.md
- vendor/github.com/nanmu42/limitio/limitio.go
- vendor/modules.txt
The logutil package will contain a writer wrapper implementation that
creates a file for logging purposes. It will use a limited writer to
ensure that the log doesn't grow unboundedly.
Signed-off-by: Andrew <andrewsun@google.com>
> Add logutil package with log writer wrapper

- README.md
Explain how to build without network access, using the dependencies in the vendor folder.
Signed-off-by: Ricardo Ribalda <ribalda@chromium.org>
> README.md: Add network-less instructions

- pkg/boot/bzimage/bzimage_test.go
The testdata/bzImage test file cannot be added to TestAddInitRAMFS because it will fail with:
`bzimage_test.go:141: new initramfs is 1536 bytes, won't fit in 480 byte old one`.
> (test cleanup) Add subtest to bzimage_test.go

- cmds/exp/bzimage/bzimage.go
…p using it
in u-root, we set flag.Usage to be called when a usage is wrong.
spf13/flag will exit in at least one place without calling flag.Usage,
which means our usage message will not be printed.
Our use of spf13/flag in this command is not sophisticated
enough to require it, so stop using it.
This way, we get real usage error message.
> cmds/exp/bzimage: change to use standard Go flag package

- pkg/boot/bzimage/bzimage.go
- pkg/boot/bzimage/bzimage_test.go
The existing code already uses payload_size to read the compressed
kernel, but ignores payload_offset and instead uses magic numbers to try
and find the beginning of the compressed kernel code.
This change uses payload_offset to find the exact start of the
compressed code and modifies `findDecompressor` to check that the
compressed payload begins with a known magic number.
payload_size and payload_offset were added in protocol version 2.08
(https://www.kernel.org/doc/html/latest/x86/boot.html) so an explicit
version check has been added. This version requirement is not new,
because the existing code already relies on payload_size, it is just now
explicit.
All tests continue to pass, unmodified.
> bzimage: Use payload_offset to find compressed kernel.

- pkg/boot/bzimage/bzimage.go
- pkg/boot/bzimage/bzimage_test.go
- pkg/boot/bzimage/header.go
Each bzImage file contains a CRC32 checksum appended to the end of the
file. This change adds checking of the CRC32 and updating the CRC32 when
marshaling the image to binary.
Tests are added to ensure that this works as intended. Existing code
which modified the versions needed to be updated to
unmarshal -> marshal to ensure that the new CRC32 is written.
> bzImage: Add CRC32 checking and setting.

- pkg/mount/gpt/gpt.go
- pkg/mount/gpt/gpt_test.go
The current code reads/writes GPT headers in 92-byte `HeaderSize`
increments. Changing the code to read/write GPT headers in sector
increments is a tradeoff with the following pros/cons:
Reading the whole sector:
* Pro: Removes a use of hard coded 0x5c value of `HeaderSize`.
Makes it simpler to support different header sizes in the future.
* Con: Requires reading an additional 820 bytes (420 for primary, 420
for secondary).
Writing the whole sector:
* Pro: Enforces the expectation/requirement that the unused 420 reserved
bytes are zeroed out.
* Con: May overwrite any data that is sneakily being stored in the
reserved bytes for some other (non-compliant) use case.
Also:
* Add test code that succeeds with this change but fails with the
existing code.
* Change iodisk to a struct which logs …
> GPT: Read/Write GPT header in whole-sector increment.

- cmds/core/chmod/chmod.go
- cmds/core/echo/echo.go
- cmds/core/md5sum/md5sum.go
- cmds/core/mkdir/mkdir.go
- cmds/core/mv/mv.go
- cmds/core/netcat/netcat.go
- cmds/core/ping/ping.go
- cmds/core/rm/rm.go
- cmds/core/sync/sync.go
- cmds/core/truncate/truncate.go
- cmds/exp/bzimage/bzimage.go
- cmds/exp/ed/ed.go
- cmds/exp/syscallfilter/main_linux.go
- pkg/uroot/util/pkg_test.go
- pkg/uroot/util/usage.go
Usage used to import "flag", and modify flag.Usage. This failed badly
if the caller was using a different flag package, e.g. spf13/pflag.
Users of Usage must now explicitly provide whatever Usage func
they are using, and must set the Usage function, e.g.:
flag.Usage = util.Usage(flag.Usage, "usage message")
> pkg/uroot/util: change usage to return func() wrapping a func()

- pkg/boot/bzimage/bzimage.go
- pkg/boot/bzimage/bzimage_decompress.go
- pkg/boot/bzimage/bzimage_test.go
* Pull #2480 added a Go zstd package. Let's use that instead of forking out to a comand to decompress these payloads.
* Add a CRC32 hash check to all test cases to ensure that the decompressed payload doesn't change if we swap out decompressors in the future.
> Change zstd decompressor to use Go package instead of forking a command.

- pkg/efivarfs/varfs.go
- pkg/efivarfs/varfs_test.go
- pkg/efivarfs/vars.go
- pkg/efivarfs/vars_test.go
GUIDs are only 16 bytes, pointers are 8 bytes. There is code that blindly
references through the pointer and that is asking for trouble.
The space saving is minimal and the risk is greatly reduced.
> VariableDescriptor: change *GUID to GUID

- cmds/core/timeout/main.go
- cmds/core/timeout/main_test.go
usage:
timeout [-t duration] command [args...]
Runs a command and, if it takes too long, kills it.
> cmds/core/timeout: add a timeout command

- pkg/ldd/ldd_unix.go
- pkg/ldd/ldd_unix_test.go
Usually virtual libraries like `vdso` is printed on the same line,
howeve this doesn't seem to always be the case.
Implement a check to see if the symlink is pointing at the same file and
ignore the entry if it does.
We also return an error instead of failing with a printed message.
Signed-off-by: Morten Linderud <morten.linderud@mullvad.net>
> ldd: Ignore symlinks that lead to the same file

- cmds/core/timeout/main.go
This error was used in previous iterations of the code but was not used in the final iteration. My "thorough review" did not catch this unused variable :)
> Remove unused error.

- cmds/boot/boot/boot.go
- pkg/cmdline/cmdline.go
- pkg/cmdline/cmdline_linux.go
- pkg/cmdline/cmdline_other.go
- pkg/cmdline/cmdline_test.go
- pkg/cmdline/filters.go
- pkg/cmdline/filters_test.go
Remove log.Prints from the package.
Change NewCmdLine to return a *CmdLine.
Split out the cmdline reader into an os-dependent part.
Other kernels have linux-like command lines.
Remove use of once.Do, it is a pointless saving that impedes
tests.
Define operators on the CmdLine struct.
Call those operators from the package functions, e.g.
cmdline.Flag will call getCmdLine().Flag().
Require that filters take a *CmdLine parameter, rather than
using a package variable.
This change makes writing tests for other packages much easier, and
much less dependent on running tests on Linux.
> pkg/cmdline: make it more idiomatic and testable

- cmds/exp/fixrsdp/fixrsdp.go
Verify writes to /dev/mem. Depending on kernel settings like CONFIG_STRICT_DEVMEM, writes to /dev/mem can silently fail.
Signed-off-by: Rob Vandermeulen <rob.vdm.82@gmail.com>
> fixrsdp: add write verification.

- pkg/pci/devices.go
- pkg/pci/devices_test.go
- pkg/pci/pci.go
It is far easier to make use of the int in code.
> pci: Replace bus string with uint8

- cmds/core/wget/wget.go
Before this change, as io.Copy reads from source
and write to destination, it caches a copy.
wget simply need to dump contents, caching a copy
while reading is unnecessary, and can cause OOM in systems with limited ram.
> wget: no cache is needed.

- cmds/core/init/init_linux.go
- pkg/libinit/root_linux.go
- pkg/libinit/root_linux_test.go
This path implements two new ways of loading kernel modules early. Sometimes building monolithic kernels are not really feasible and people use their kernel and kernel modules included int he initrd image. This brings problems like how to supply the desired driver into `/lib/modules/*.ko` as you would need to have an explicit `-file` parameter for each module.
This introduces two new ways to get around this:
* Through configuration files in `/etc/modules-load.d`
* Through `modules_load` kernel parameter
These options are popularized through the systemd project and documented here;
https://www.freedesktop.org/software/systemd/man/kernel-command-line.html#modules_load=
https://www.freedesktop.org/software/systemd/man/modules-load.d.html
I'm also wondering if we'd be interested in supporting …
> Support more ways to load kernel modules early

- cmds/core/kill/kill_test.go
The kill test might fail because PID 9999 exists. This commit create a PID that will be unused temporarily for testing purpose.
Signed-off-by: Medicine Yeh <medicinehy@gmail.com>
> cmds/core/kill: Create an unused port for testing kill

- pkg/efivarfs/fs_test.go
...as cleanup temporary folder can require root
after we temper with file I node flags.
e.g.
```
--- FAIL: TestFSGoodFile (0.00s)
testing.go:967: TempDir RemoveAll cleanup: unlinkat /tmp/TestFSGoodFile214938004/001/x: operation not permitted
FAIL
```
Temporary folder is created from testing pkg.
If test fail to cleanup the temporary folder, it
will [fail the test](https://source.corp.google.com/piper///depot/google3/third_party/go/gc/src/testing/testing.go;l=1125;bpv=0;rcl=478263875)
> fs_test: skip TestFSGoodFile is not run as root.

- pkg/efivarfs/fs_test.go
d6bd58d6a4e8c1f00b1fa996b8d2876acfaf9c0f added a skipifnotroot to avoid a tmpdir removal problem.
This was not the correct fix. The problem was that a file, once make immutable, has to be made mutable, or it can not be removed.
In the test, restore a file to mutability before ending the test.
The test can now be run as any user.
> pkg/efivarfs: correctly fix tmpdir removal

- cmds/core/ls/ls.go
- cmds/core/ls/ls_plan9.go
- cmds/core/ls/ls_test.go
- cmds/core/ls/ls_unix.go
- pkg/cmdline/cmdline_test.go
ls had accumulated a lot of problems around permissions and non-existing files.
```
rminnich@a300:~/go/src/github.com/u-root/u-root/cmds/core/ls$ ./ls /tmp/b rminnich@a300:~/go/src/github.com/u-root/u-root/cmds/core/ls$ rminnich@a300:~/go/src/github.com/u-root/u-root/cmds/core/ls$ ls /tmp/b ls: cannot access '/tmp/b': No such file or directory rminnich@a300:~/go/src/github.com/u-root/u-root/cmds/core/ls$
rminnich@a300:~/go/src/github.com/u-root/u-root/cmds/core/ls$ mkdir /tmp/t/{a,b,c} rminnich@a300:~/go/src/github.com/u-root/u-root/cmds/core/ls$ chmod 0 /tmp/t/b rminnich@a300:~/go/src/github.com/u-root/u-root/cmds/core/ls$ ./ls /tmp/t a
rminnich@a300:~/go/src/github.com/u-root/u-root/cmds/core/ls$ ls /tmp/t{a,b,c}
rminnich@a300:~/go/src/github.com/u-root/u-root/cmds/core/ls$
```
It also …
> cmds/core/ls: fix multiple problems around permissions

- pkg/syscallfilter/syscallfilter_linux_test.go
The test for a double wait is no longer needed
as of the fix called
os/exec: refactor goroutine communication in Wait
4e79f06
With go 1.19 and later, it just hangs. So remove it.
> pkg/syscallfilter: remove test obsoleted by go 1.19

- cmds/boot/fbnetboot/main.go
When booting with a manually-specified image (e.g. via `netboot-url`) it is often useful to be able to apply custom kernel command line arguments.  This adds a `-cmdline` argument in the same style as the `netboot-url` argument, to override the default (typically empty) value.
> Add `-cmdline` to `fbnetboot` to override kernel cmdline args

- pkg/cpio/utils.go
- pkg/cpio/utils_test.go
The need for this function is explained in detail in the code. Short form: it is easy to programatically
create cpio files that the Linux kernel does not
parse correctly.
If a file has a/b/c/d, but not Directory records
for a/b/c, the Linux kernel cpio parser will silently discard the record for a/b/c/d. This is not the same behavior as cpio programs.
> pkg/cpio: add utility function WriteRecordsAndDirs

- cmds/core/ip/ip_linux.go
In `ip route add`, the component after `via` should be an IP address instead of of a CIDR. 
Actually in the current implementation of `nexthop()`, only `nhval.IPNet.IP` (which is a `net.IP`) is used in `routeadddefault()`.
> cmds/core/ip: parse gateway IP instead of CIDR

- pkg/pty/pty_test.go
Similar to TestRunRestoreTTYMode() below, TestNew() should skip the case when there is no /dev/tty in the system.
Signed-off-by: Changyuan Lyu <changyuanl@google.com>
> pkg/pty/pty_test:Skip test if /dev/tty does not exist

- cmds/core/cat/cat.go
currenlty cat -u file.txt will try to open file -u
Signed-off-by: Siarhiej Siemianczuk <pdp.eleven11@gmail.com>
> cmds/core/cat: don't pass cmdline args as a [FILE]

- cmds/boot/fbnetboot/main.go
`dhcp4` and `dhcp6` each iterate through the result of `netboot.RequestNetbootv{4,6}` before checking the error returned by the call. This may lead to situations where the code invoces the `Summary()` method on a nil pointer.
The called function, `ReqestNetbootv4`, has a code path where it may return err==nil along with invalid data.  That is being fixed separately in https://github.com/insomniacslk/dhcp/pull/483.
I stumbled across this while checking on https://github.com/u-root/u-root/issues/2517
Signed-off-by: Avi <avibrender@gmail.com>
> Fix error checking fbnetboot/main.go

- cmds/boot/localboot/grub_test.go
- pkg/boot/grub/config_test.go
- pkg/boot/syslinux/syslinux_test.go
- pkg/cpio/newc_test.go
- pkg/cpio/testdata/fuzz/fuzz_read_write_newc.options
These changes are intended as fixes to the fuzzing tests when running in the oss-fuzz environment.
1. Reduce input size of one test so libfuzzer does not run out of memory 
2. Use a temporary directory per fuzzing input run so no execution is influenced by previous runs
Signed-off-by: Fabian Wienand <fabian.wienand@9elements.com>
> [oss-fuzz integration]: misc fixes in fuzzing tests

- cmds/boot/localboot/grub_test.go
- cmds/exp/gosh/gosh_test.go
- pkg/boot/grub/config_test.go
- pkg/boot/syslinux/syslinux_test.go
Need to roll back some fuzzing tests from calling f.TempDir() to t.TempDir(), as this is currently not supported by OSS-Fuzz. 
As each run in oss-fuzz is sandboxed anyway, this is only relevant when fuzzing locally. 
Signed-off-by: Fabian Wienand <fabian.wienand@9elements.com>
> oss-fuzz: replace t.TempDir()

- cmds/exp/disk_unlock/disk_unlock.go
- cmds/exp/nvme_unlock/nvme_unlock.go
- pkg/hsskey/hsskey.go
- pkg/hsskey/hsskey_test.go
Add a new nvme_unlock command to unlock NVMe drives secured according to the TCG Opal specification, using the kernel's sed-opal driver.  This uses the same key generation algorithm as the disk_unlock command, so that functionality is refactored into a separate package hsskey.
Signed-off-by: Albert Morgese <amorgese@google.com>
> Add tool for unlocking TCG Opal-secured NVMe drives

- cmds/core/date/date_test.go
There is some error text printed by date tests, and it makes looking at CI errors very difficult. Direct it into a bytes.Buffer instead.
> cmds/core/date: set test error output to bytes.Buffer

- pkg/mount/block/blockdev_linux.go
- pkg/mount/block/blockdev_test.go
This is a useful utility function for assembling block device paths, and it already has unit test coverage, so make it public.
Signed-off-by: Albert Morgese <amorgese@google.com>
> /pkg/mount/block: Expose ComposePartName function

- cmds/core/uname/uname.go
- pkg/kmodule/kmodule_linux.go
Use `ByteSliceToString` defined in the `golang.org/x/sys/unix` package to convert `Utsname` `[]byte` fields to strings.
> Use unix.ByteSliceToString to convert Utsname fields

- integration/testcmd/gotest/uinit/gotest.go
- pkg/fdsrv/fdsrv.go
- pkg/fdsrv/fdsrv_test.go
By default, running a test binary only runs tests, not benchmarks or fuzz tests. this left VM tests out of that ability. Adding just benchmark tests here, because fuzz tests need some more flags that I didn't want to figure out.
Also fixing some test that started failing in the VM presumably because the VM is slower and the test is flaky.
> gotest: run benchmarks in VMs

- .circleci/config.yml
- .circleci/images/test-image-amd64/Dockerfile
- .circleci/images/test-image-amd64/config_linux.txt
- .circleci/images/test-image-arm64/Dockerfile
- .circleci/images/test-image-arm64/config_linux.txt
- cmds/exp/pox/pox_vm_test.go
- integration/GET_KERNEL_QEMU
- integration/gotests/gotest_test.go
- pkg/acpi/rsdp_linux_test.go
- pkg/efivarfs/fs.go
- pkg/efivarfs/varfs_test.go
- pkg/ipmi/ipmi_vm_test.go
- pkg/mount/block/vm_test.go
- pkg/smbios/vm_test.go
- pkg/vmtest/gotest.go
This initially worked, but almost all VM Go unit testing broken when Gobusybox was made the default by @MDr164 in May 2022, as [this comment indicates](https://github.com/u-root/u-root/pull/2404#issuecomment-1136008712). All arm64 tests and and most if not all x86 VM-based Go tests (like pkg/ipmi, pkg/mount, pkg/smbios) haven't been running.
Also, we don't seem to notice that the tests aren't running in the first place, but I'm dealing with that later.
End result of this PR:
* CircleCI presubmit now runs in ~15 minutes instead of 30 minutes
* Go unit VM tests work again (amd64 & arm64)
* 1.37% coverage increase
* [this list](https://github.com/u-root/u-root/pull/2589#issuecomment-1367591342) of broken tests fixed
* Couple of tests disabled, but not really relevant.
Before:
... …
> Actually compile Go VM tests; halve CircleCI test time

- pkg/termios/sgtty_openbsd.go
- pkg/termios/termios_bsd.go
- pkg/termios/var_openbsd.go
I verified that this permits Tailscale SSH (Tailscale's SSH server) to run on OpenBSD.
> pkg/termios: add openbsd support

- pkg/termios/termios_bsd.go
- pkg/termios/termios_test.go
- pkg/termios/var_darwin.go
- pkg/termios/var_freebsd.go
- pkg/termios/var_openbsd.go
I broke darwin support in the just-merged #2593.
To atone for my sins, this PR adds some more test coverage (in addition to fixing darwin).
> pkg/termios: fix darwin regression from previous commit, add tests

- .github/workflows/cifuzz.yml
- cmds/core/gosh/testdata/fuzz/fuzz_gosh_run.options
Added the `report-unreproducible-crashes` flag to the cifuzz config (just a verbose change, this is false per default anyway).
Limited the input byte size for the gosh fuzzing to avoid any timeouts due to it.
> cifuzz: do not report non-reproducible crashes

- cmds/core/ip/ip_linux.go
`os.Args[1:]` may include "-6", which should be excluded.
Fixes: c2762deff650 ("cmds/core/ip: remove cmd logic from main")
Signed-off-by: Changyuan Lyu <changyuanl@google.com>
> cmds/core/ip: fix arg parsing

- RELEASES
The major driver for this was that v0.10.0 broke tamago armoryboot.
But it makes sense to do it anyway, with all the bug fixes and cleanups that happened recently.
> bump to v-1.11.0

- cmds/core/time/time.go
- cmds/core/time/time_all.go
- cmds/core/time/time_test.go
- cmds/core/time/time_tinygo.go
time now uses the errors package, simplifying tests.
It now builds with tinygo
> cmds/core/time: make it build with tinygo, tidy up

- pkg/strace/epsocket.go
- pkg/strace/epsocket_test.go
- pkg/strace/socket.go
I am not sure why the original code does this but
it returns a binary string in FullAddress:Addr.
Change the code so that Addr is net.IP().String().
Add tests.
Fixes:#2609
> pkg/strace/epsocket: fix handling of IP4/IP6

- cmds/exp/rush/attr_tinygo.go
- cmds/exp/rush/cd.go
- cmds/exp/rush/info.go
- cmds/exp/rush/rush.go
- cmds/exp/rush/tty_linux.go
- cmds/exp/rush/tty_tinygo.go
It does not work, yet: there are missing functions in the tinygo environment. But, once they are there, we have a (crude) shell.
> cmds/exp/rush: make it build with tinygo

- cmds/boot/fitboot/main.go
- cmds/core/kexec/kexec_linux.go
- pkg/boot/boot.go
- pkg/boot/menu/menu.go
verbose and dryRun will for the most part be set through boolean flags, so a boolean WithVerbose(bool) and WithDryRun(bool) should be available for easy use.
> boot: improved Load API

- pkg/ipmi/blobs/blob_transfer.go
- pkg/ipmi/ipmi_linux.go
- pkg/ipmi/ipmi_vm_test.go
This change makes two minor feature updates to the ipmi and blobs packages:
1. Introduces OpenPath to open the ipmi device by full path instead of just device number.
2. Makes BlobStats's members public, so that BlobStat and BlobSessionStat can be used.
In testing this change, I noticed that BlobStat/BlobSessionStat had a bug. Fixed that as well. (You can't pass a struct with a slice member to binary.Read.)
> Introduce ipmi.OpenPath and make blobs.BlobStats public.

- cmds/core/kexec/kexec_linux.go
- integration/generic-tests/kexec_test.go
- pkg/boot/boot.go
- pkg/boot/linux.go
- pkg/boot/linux/opts.go
This is only triggered when we specify to not load image. Downloaded image info, together with other
configs like cmdline will be saved to a file under tmpfs, which can be reloaded via kexec cmd
> boot: serialize downloaded image info for reload

- cmds/exp/smbios_transfer/smbios_transfer.go
In https://github.com/u-root/u-root/issues/2622, the u-root IPMI blob library was fixed to stop requiring blob IDs to contain trailing NUL characters in them (which is unidiomatic). As a backwards-compatibility step, the library still accepts blob IDs with the trailing NUL, but the library did stop providing blob ID strings (in BlobEnumerate) with these trailing NULs.
The smbios transfer utility had a hard dependency on this trailing NUL (in the equality check). This change fixes that in a way that still supports old versions of u-root if needed, by using strings.TrimSuffix.
> Remove the dependency on un-idiomatic Go strings for IPMI blobs.

- cmds/exp/smbios_transfer/smbios_transfer.go
This change removes the usage of strings.Trim to compare the smbios blob ID. Because this package is in the same repository as u-root/pkg/ipmi/blobs, there is no actual need for backwards-compatibility with an earlier version of the subpackage.
This change also cleans up smbios_transfer by fixing a few instances of the typo "tranfer."
> Simplify smbios_transfer and fix typos

- cmds/core/dd/dd.go
- cmds/core/dd/dd_test.go
- pkg/progress/progress.go
- pkg/progress/progress_test.go
dd fixes for tinygo. These are pretty minimal to get it to go at all, but they have the nice side effect of removing testutil and allowing concurrency in tests. 
The unit package adds a good 11K to the binary when built with tinygo. It's not entirely clear that we need what it does, but for now, it remains. 
Due to some odd limitations in tinygo, the final test memory footprint had to be reduce from 1G to 1/4 G, but I doubt this changes the validity of the test.
This change will also allow dd to be built into the 'forkless' environment.
> Dd for tinygo

- cmds/core/hexdump/hexdump.go
- cmds/core/hexdump/hexdump_test.go
The code was writing the file but not closing it, which could be trouble on some systems.
The string of all letters was used more than once; make it a const.
go test and tinygo test now both work, once #3646 WIP: fix else/defer bug goes in to tinygo.
> cmds/core/hexdump: use constants and os.WriteFile

- cmds/core/time/time.go
in general time output is not specified by POSIX, but with -p flag it does, u-root time command already output in POSIX format, so -p flag does nothing, but time -p will not fail
> cmds/core/time: add -p flag to time command

- cmds/core/grep/grep.go
- cmds/core/grep/grep_test.go
From POSIX: Precede each output line by its relative line number in the file, each file starting at line 1.
> cmds/core/grep: fix line number (-n)

- pkg/cpio/fs_unix.go
- pkg/uio/lazy.go
- pkg/uio/lazy_test.go
There exists a race condition when attempting to add records to the cpio and when the underlying file is being written to at the same time. Introducing a limit writer in case more data gets written to the file.
> Add file limit to cpio file creation

- cmds/core/gosh/gosh.go
- cmds/core/gosh/gosh_test.go
- uroot_test.go
new environment variable controls tab completion.
It could be added to any new shell if we change again
// If UROOT_SHELL_TABCOMPLETE
//   is not set, completion is enabled.
//   is set, and it has value 1, completion is enabled.
//   is set, and it has value !=1, completion is DISABLED.
I also took the opportunity to tidy things up a bit, using variadics where it made sense, and removing the use of nargs arguments: this is Go.
> cmds/core/gosh: make autocomplete disable-able

- cmds/core/grep/grep.go
- cmds/core/grep/grep_test.go
initilise c.expr with args[0] if c.expr is empty
> cmds/core/grep: fix empty fixed-string

- cmds/core/gosh/gosh.go
- cmds/core/gosh/gosh_test.go
gosh is a very active shell. On each command, it spews all kinds of ANSI control sequences and so on.
This noise comes from bubbline, which seems to have no way to easily minimize all the activity. The noise causes trouble for test environments.
Add a switch, -interactive, default true, which if set false makes gosh act like a simple, noninteractive, line-at-a-time shell.
> gosh: add a -interactive switch to disable terminal noise

- cmds/exp/disk_unlock/disk_unlock.go
- cmds/exp/nvme_unlock/nvme_unlock.go
- pkg/hsskey/filereader.go
- pkg/hsskey/filereader_test.go
- pkg/hsskey/hsskey.go
This change adds an option for nvme_unlock to read HSS keys from EEPROM. We assume the EEPROMs will be enumerated in sysfs and can be accessed like a regular file.
> HSS: Support reading HSS from EEPROM

- uroot_test.go
> Remove unused DCE test

- pkg/boot/menu/menu.go
- pkg/libinit/proc.go
Allow users to specify stdin, stdout, and stderr options when running the shell.
> Add stdin, stdout, stderr options to StartShell struct

- pkg/dt/node.go
- pkg/dt/node_test.go
A few minor extensions to the existing pkg/dt API to look-up direct children and prune sub-trees,
It is sometimes useful to look up a specific direct child of a given node, instead of recursively looking up _a_ child at any depth in the tree. A 2nd patch adds the ability to edit the FDT to remove a node and its subtree.
> pkg/dt: look-up direct children and prune sub-trees

- cmds/core/ls/ls.go
- pkg/ls/fileinfo_linux_test.go
- pkg/ls/fileinfo_unix.go
FromOSFileInfo had a blind cast of a FileInfo.Sys() to *syscall.Stat_t.
This could fail with a badly behaving file system, e.g. a 9p server that would fail a Stat in ways that the go runtime was not prepared for.  Ask me how I know :-) The fact that we have not seen this in 11 years of use testifies to its rarity, but ... it can happen.
In FromOSFileInfo, pick default values for UID, GID, and rdev
Check if fi.Sys() is a *syscall.Stat_t and, if so, use Uid, Gid, and Rdev from it.
Add a type to the linux test that implements os.FileInfo (yes, fs.FileInfo now ...) that can return a Sys() of the wrong type. I verified that this test
catches the failing case.
A bit of cleanup:
Rename the test file ls_linux_test.go to fileinfo_linux_test.go, to match everything else in this directory.
Remove a …
> pkg/ls:FromOSFileInfo: fix a panic if fi.Sys() returns the wrong type

- cmds/core/shasum/shasum.go
> Fix argument name for shasum command

- cmds/core/cmp/cmp.go
- cmds/core/cmp/cmp_test.go
fix staticcheck issue with fmt.Fprintf and no args.
> cmds/core/cmp: remove global flags

- cmds/core/pwd/pwd.go
- cmds/core/pwd/pwd_test.go
removed usage because there are no way to run it as ./pwd -LP and flag package will print help when flags are incorrect.
> cmds/core/pwd: add test for follow links

- pkg/mount/magic.go
BTRFS partitions can now be mounted
source: https://btrfs.readthedocs.io/en/latest/dev/On-disk-format.html#superblock
> pkg/mount/magic.go: Add BTRFS magic value

- pkg/libinit/root_linux.go
With this PR, `CreateRootfs()` in `root_linux.go` uses the `NoFollowSymlinks` option to correctly handle broken symlinks found in `/etc` when setting up the filesystems.\n
> Fix /etc/ lossage in CreateRootfs

- pkg/boot/jsonboot/bootconfig.go
- pkg/boot/linux.go
- pkg/boot/linux_test.go
It is possible/likely that the kernel is compressed. In order for kexec to actually find the magic value for aarch64 Linux kernels it needs to be decompressed before refering it to the kexec syscall.
Test: aarch64 Fedora 36 Server image can now be started via localboot.
> pkg/boot/linux.go: Decompress kernel before doing kexec

- pkg/hsskey/hsskey.go
Refactor getHssFromIpmi to use an ordered list of HSS string prefixes, allowing the use of "backup" HSS keys (which will only be used after all "regular" HSS keys have been tried).
> /pkg/hsskey: Include backup HSS

- cmds/core/xargs/xargs.go
- cmds/core/xargs/xargs_test.go
Parsing is simplified by strings.Fields, so no quotes support.
> cmds/core/xargs: minimal xargs, just passing args

- .github/workflows/auto-assign.yml
- cmds/core/lddfiles/lddfiles_linux.go
- cmds/exp/pox/pox.go
- cmds/exp/pox/pox_vm_test.go
- pkg/ldd/ldd.go
- pkg/ldd/ldd_darwin.go
- pkg/ldd/ldd_darwin_test.go
- pkg/ldd/ldd_test.go
- pkg/ldd/ldd_unix.go
- pkg/uroot/uroot.go
New:
* ldd.List(paths ..string) -> lists dependency files (interps and dynamic libraries), as named in the given binary.
* ldd.FList(paths ...string) -> like List, but also lists all files pointed to through symlinks in the dependency files.
Neither of them return the original file name in paths anymore.
Removing:
* ldd.List (equivalent is FList, but FList does not list the original file name anymore)
* ldd.Ldd (there is nothing returning FileInfo anymore, because nothing was using it)
> Revamp ldd API

- cmds/core/dmesg/dmesg.go
- cmds/core/dmesg/dmesg_test.go
Container environments are not always truthful about the UID. Sometimes UID 0 in a container can not do root-level operations.
Also, use errors.Is instead of comparing strings;
embed returned errors with %w for testing.
> Fix dmesg test so that testtool works in CI

- cmds/core/fusermount/fusermount.go
- cmds/core/fusermount/fusermount_linux_test.go
don't even try to run the tests if /dev/fuse does not exist.
> if /dev/fuse does not exist, skip fusermount tests 

- cmds/exp/rush/rush_tinygo.go
- tools/tinygobb/main.go
reduce the number of functions tinygobb updates
to just runone.
Add a placeholder cmds/exp/runone_tinygo.go,
so that gobusybox will not get confused.
> tinygobb: update and make it work again

- .stickler.yml
- CONTRIBUTING.md
golint is gone as of 2021.
stickler-ci.com is either dead, or no longer free, or .. it's not clear.
> remove usage of golint and references in README

- cmds/core/touch/touch.go
- cmds/core/touch/touch_test.go
-d datetime use RFC3339 as date format
-m modification time of file
-a access time of file
-c do not create a specified file if it does not exist
> cmds/core/touch: command with RFC3339 datetime

- cmds/exp/readelf/readelf.go
for slices capacity defaults to length
> cmds/exp/readelf: remove redundant argument

- pkg/ls/fileinfo_tamago.go
There is one difference at the moment, but there may be more, between unix and tamago fileinfo.
We may find it possible to merge later, but for new, create a separate fileinfo_tamago.go
> pkg/ls: create fileinfo_tamago

- cmds/core/ls/ls.go
- cmds/core/ls/ls_linux_test.go
- cmds/core/ls/ls_plan9.go
- cmds/core/ls/ls_test.go
- cmds/core/ls/ls_unix.go
This makes it usable in tamago and other bare-metal environments.
> ls: remove all globals

- pkg/dhclient/dhclient.go
This de-flakes some Google-internal netboot testing which uses manually configured unicast IPv6 addresses.
> dhclient: ensure DHCPv6 address is routable if using non-multicast address

- cmds/fwtools/spidev/spidev_linux.go
- pkg/flash/flash_linux.go
- pkg/flash/op/op.go
- pkg/flash/op/op_test.go
- pkg/flash/spimock/spimock_linux.go
I decided not to use a map. 
Using a switch lets the compiler optimize at it sees fit, where a map wires in a decision as to best implementation, a map sitting around we almost never need, and so on. I'm sensitive to this in a world of little devices.
> flash/op: add String() and Bytes() for OpCode

- cmds/fwtools/spidev/spidev_linux.go
- pkg/flash/flash_linux.go
- pkg/flash/flash_linux_test.go
- pkg/flash/spimock/spimock_linux.go
- pkg/spidev/spidev_linux.go
- pkg/spidev/spidev_linux_test.go
Check for the chip ID first, before trying to read the SFDP. If it is found, use those values for density and so on.
In any case, always try to read the sfdp. As time goes by, more and more chips will implement it, and it will go from mostly failing to mostly working.
> pkg/flash: update flash to use chips package

- cmds/fwtools/spidev/spidev_linux.go
- cmds/fwtools/spidev/spidev_linux_test.go
Remove the code in the command, use ID from the package. tested today on rpi4
> fwtools/spidev: use the ID function from pkg spidev

- pkg/boot/linux.go
- pkg/boot/linux_test.go
- pkg/vfile/vfile.go
On low memory systems, vfile contributes one of many copies of an OS to be kexec'd in u-root. To enable only-one-copy kexec, drop TOCTTOU protections.
> vfile: save memory by removing TOCTTOU protections

- cmds/exp/dumpmemmap/main_linux.go
- pkg/boot/kexec/memory_map_linux.go
- pkg/boot/kexec/memory_map_linux_test.go
- pkg/boot/linux/load_linux_amd64.go
- pkg/boot/multiboot/multiboot.go
- pkg/boot/uefi/uefi.go
- pkg/boot/uefi/uefi_test.go
I was wrong. It only exists on x86 systems, and works with e820 and EFI.
> memmap: rename /sys/firmware/memmap parser

- pkg/boot/kexec/kexec_load_linux.go
- pkg/boot/kexec/memory_linux.go
- pkg/boot/kexec/memory_linux_test.go
This makes segment management much easier. It removes the "pool" hack we were using to keep pieces of memory alive. Convert them to kexec format only when actual kexec syscall is called.
> kexec: switch segments to use []byte

- pkg/boot/linux/load_linux_amd64.go
No unit tests here yet. Still covered by the integration test.
> Reduce memory usage of amd64 userspace kexec

- cmds/fwtools/flash/flash_linux.go
- cmds/fwtools/spidev/spidev_linux.go
- pkg/flash/chips/chips.go
- pkg/flash/flash_linux.go
- pkg/flash/op/op.go
- pkg/flash/op/op_test.go
- pkg/flash/spimock/spimock_linux.go
- pkg/spidev/spidev_linux.go
We now have fast SPI writing, using a block size of 256 bytes. 
No erasing yet.
This also fixes a messy bug in WriteAt where odd sized write blocks would cause it to reference past the
end of the slice.
Erasing tested, works fine.
> Sfdp rules

- README.md
Fixing build error:
vendor/github.com/u-root/uio/uio/buffer.go:179:18: undefined: binary.NativeEndian note: module requires Go 1.21
> Update README.md for Go version 1.21

- docs/playbook.md
add a playbook entry for a question that just came up
> Add a playbook entry showing how to set verbose init

- .golangci.yml
- pkg/boot/bls/bls.go
- pkg/dt/fdt_test.go
first invocation of getGrubvalue can return an error, second only empty string
> pkg/dt,pkg/boot/bls: remove unused variables

- pkg/ipmi/constants.go
- pkg/ipmi/dev.go
- pkg/ipmi/structures.go
Currently IPMI command errors manifest as `"invalid response, expected first byte of response to be 0, got: %v"`. This commit changes the error message to depend on the value of the completion code, clarifying the nature of the error to a casual user.
> pkg/ipmi: Interpret IPMI command error codes

- cmds/exp/ed/commands.go
to avoid possible confusion with Go builtins
> cmds/exp/ed: rename append to offset

- cmds/core/ls/ls.go
- cmds/core/ls/ls_plan9.go
- cmds/core/ls/ls_test.go
- pkg/uroot/unixflag/unixflag.go
- pkg/uroot/unixflag/unixflag_test.go
Go flag processing has followed the Plan 9 model from the beginning,
where -name is a switch for name, whereas in Unix, it means
-n -a -m -e.
This is fine for new programs, but a problem for old programs, like ls, where people
expect Unix rules to apply.
Since 2013 or so, u-root dealt with this by importing a variety of flag packages.
They all come with their own problems, including binary size.
We must have a way to optionally use Unix rules where they are expected. This is
essential, due to the large number of scripts in existence.
Add a function to uroot/util, ArgsToGoArgs, which will take a []string, and change:
--arg is translated to -arg
-arg is tranlated to -a -r -g
The first non-dash argument ends processing.
Add a function, OSArgsToGoArgs, which call ArgsToGoArgs with os.Args[1:] …
> uroot/util: add unixflag processing

- cmds/fwtools/spidev/spidev_linux.go
- cmds/fwtools/spidev/spidev_linux_test.go
for the raw command, for each arg, dump arg size bytes to stdout.
Ryan, feel free to tell me this should be done differently/better :-)
I just did not want to lose these changes.
> spidev: process arguments for raw command

- cmds/core/ls/ls.go
Currently the ls command does nothing except printing out the current directory, because it ignores all arguments.
Fix it by supplying the actual arguments.
Fixes #3019
> cmds/core/ls: Fix flag parsing

- cmds/exp/pox/pox.go
At some point the API changed and it broke pox.
There was never a test for this b/c it's just about impossible to write a long-lived test for pox, it is incredibly system-dependent. Oh well.
> exp/pox: add the binary in since ldd.List no longer does

- cmds/exp/pox/pox.go
- cmds/exp/pox/pox_test.go
- cmds/exp/pox/pox_vm_test.go
With the recent changes, pox standalone mode was totally broken.
You can now use it again
pox -cvsf date `which date`
sudo ./date
works fine.
While we are at it, we now print a useful message if you do not run a standalone pox as root. It comes complete with 38% snark.
> pox: get standalone mode working again

- cmds/exp/disk_unlock/disk_unlock.go
- cmds/exp/nvme_unlock/nvme_unlock.go
- pkg/hsskey/hsskey.go
Previous arg accepted comma-deliminated list. This makes argument passing easier for platform abstracted content. Non uniform HSS gathering can be dumped into a standard directory, eg. /hss
The comma list has not been utilized yet, so easy swap.
> Modify hss-file param in hss gathering to accept directory path

- go.mod
- go.sum
- pkg/boot/bzimage/bzimage.go
- pkg/boot/bzimage/bzimage_decompress.go
- vendor/github.com/therootcompany/xz/AUTHORS
- vendor/github.com/therootcompany/xz/LICENSE
- vendor/github.com/therootcompany/xz/README.md
- vendor/github.com/therootcompany/xz/dec_bcj.go
- vendor/github.com/therootcompany/xz/dec_delta.go
- vendor/github.com/therootcompany/xz/dec_lzma2.go
- vendor/github.com/therootcompany/xz/dec_stream.go
- vendor/github.com/therootcompany/xz/dec_util.go
- vendor/github.com/therootcompany/xz/dec_xz.go
- vendor/github.com/therootcompany/xz/doc.go
- vendor/github.com/therootcompany/xz/reader.go
- vendor/modules.txt
Fixes #2750
This is take 2 for #3026 since I had really messed up my commit comments and couldn't find a way to fix that.
At the moment, we shell out for decompressing xz files. This change will change that to using a library instead. We're using github.com/therootcompany/xz instead of github.com/ulikunitz/xz because the latter doesn't implement the BCJ filters. We're also not using https://github.com/xi2/xz because it does not have an explicit license so most companies would not OK with vendoring it.
> pkg/boot: Use a library for xz files

- pkg/boot/boottest/json.go
- pkg/boot/grub/grub.go
- pkg/boot/grub/testdata_new/ubuntu_16_04_boot.json
- pkg/boot/grub/testdata_new/ubuntu_16_04_boot/grub/grub.cfg
I've been using u-root to boot linux on an arm64 chromebook and noticed that the grub "devicetree" command didn't work. This is widely used in Debian/Ubuntu for arm64 in combination with flash-kernel to keep kernel and DTBs in sync.
> pkg/boot/grub: add support for grub devicetree command

- cmds/core/ip/ip_linux.go
- cmds/core/ip/ip_linux_test.go
- cmds/core/ip/neigh_linux.go
- cmds/core/ip/neigh_linux_test.go
- cmds/core/ip/tuntap_linux.go
- cmds/core/ip/tuntap_linux_test.go
The refactoring of flag parsing broke  some of the flags of the IP cmd, this commit fixes the parsing for all flags
> cmds/core/ip: fix flag parsing

- cmds/core/init/fns_unix.go
- pkg/libinit/net_linux.go
- pkg/libinit/net_linux_tinygo.go
Add conditional compilation to exclude any use of network packages for now. Further, `klauspost/zstd` is used, so to build this cmdlet with tinygo requires to set the build tag `noasm` as well. Since this package uses `unix.Sync` the latest `tinygo` release cannot yet be used but instead, a dev build is required.
```
tinygo build -tags noasm .
```
@rminnich
> tinygo: enable cmd/core/init

- pkg/gzip/file.go
- pkg/gzip/gunzip_tinygo.go
- pkg/gzip/gzip.go
- pkg/gzip/gzip_tinygo.go
- pkg/kmodule/compression.go
- pkg/kmodule/compression_tinygo.go
- pkg/kmodule/kmodule_linux.go
- pkg/kmodule/kmodule_linux_test.go
Right now `tinygo` does not support the use of inline assembly files that are frequently used in compression algorithms to yield performance increases.
This PR removes these implementations from the dependencies and replaces them with generic `golang` implementations, so that `tinygo` can handle this.
EDIT: adding the [`noasm`](https://github.com/klauspost/compress/blob/d76f801616d1080ce0f747ded725a839e46d9331/internal/cpuinfo/cpuinfo_amd64.go#L1C1-L1C47) build tag resolved the inline assembly cpuid issues and zst is supported.
Buildable (with caveats):
> tinygo: generic compressions

- pkg/kmodule/compression.go
- pkg/kmodule/compression_tinygo.go
Add missing !tinygo line in pkg/kmodule/compression.go, without it, there are multiple definitions of the function:
> tinygo build -tags tinygo.enable,noasm
../../../pkg/kmodule/compression.go:20:6: 	other declaration of compressionReader
../../../pkg/kmodule/compression_tinygo.go:24:6: compressionReader redeclared in this block
> tinygo: fix pkg/kmodule/compression{,_tinygo}.go build tags

- pkg/tftp/client.go
- pkg/tftp/tftp.go
- pkg/tftp/tftp_test.go
fix executeGet:
Some tftp-servers do not support file size transmission. 
Adapted function for infinite read until EOF, then write file to disc.
> FIX: cmds/exp/tftp: Read file from server until EOF

- pkg/tftp/tftp.go
fix tftp again:
* Buffer size for reading now has 512 bytes as RFC 1350 defines data size for transmission.
* If the read function indicates EOF, write only bytes which are not zero.
* remove debug statement which slipped through review.
> FIX: cmds/exp/tftp: read buffer adaption and last read correction

- pkg/ipmi/ipmi.go
The IPMI specification allows GetChassisStatus to return 3 byte messages, but the current implementation only handles 4 byte messages. In the case where a 3 byte message is returned, parse it into a shortened struct before returning it in the ChassisStatus format.
Signed-off-by: Hunter Herman <611822+hherman1@users.noreply.github.com>
I observed this issue on a machine. I fixed it locally by managing the parsing myself, but I wanted to upstream the change to help others and remove this extra unnecessary code.
> ipmi: Handle short ChassisStatus responses

- cmds/exp/tcpdump/main.go
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x5dcba5]
Goroutine 1 [running]:
main.(*cmd).processPacket(0xc000029e40, {0x6b9d40, 0xc0002a2f20}, 0x4e, {0xc0000b9d38?, 0x1?, 0x0?})
/usr/local/google/home/xuehaohu/go/src/github.com/u-root/u-root/cmds/exp/tcpdump/main.go:331 +0x1005
main.(*cmd).run(0xc000029e40)
/usr/local/google/home/xuehaohu/go/src/github.com/u-root/u-root/cmds/exp/tcpdump/main.go:210 +0x65c
main.main()
/usr/local/google/home/xuehaohu/go/src/github.com/u-root/u-root/cmds/exp/tcpdump/main.go:370 +0x145
```
A segfault occurs if the transport layer is equal to nil and called upon, i.e. the library cannot determine the type.
This can be mitigated by checking if it is nil and handling …
> cmds/exp/tcpdump: add check if transport layer is present

- cmds/core/tar/tar.go
This patch is to fix #3113 
`FlagSet` is used to parse args.
However `flag.Args()` is passed to `command` and I think it should be `FlagSet.Args()`.
I confirmed the issue was fixed.
```
> cd /tmp                                                                      
> echo aaa > aaa                                                               
> tar -cvf a.tar aaa                                                           
aaa
> tar --list -f a.tar                                                          
aaa
> mkdir test                                                                   
> tar -xvf a.tar test                                                          
aaa
> ls test                                                                      
aaa
```
> cmds/core/tar: use FlagSet.Args to pass args

- .gitignore
When debugging binaries with the GNU Debugger (gdb) it creates history files; they should be ignored by git.
> .gitignore: add .gdb_history

- cmds/core/strings/strings.go
This patch is to fix https://github.com/u-root/u-root/issues/3122
`FlagSet` is used to parse args.
However `flag.Args()` is passed to command and I think it should be `FlagSet.Args().`
I confirmed the issue was fixed.
```
> strings /proc/uptime                                                        
13.63 3.74
```
> cmds/core/strings: use FlagSet.Args to pass args

- .github/workflows/golangci-lint.yml
- .github/workflows/tests.yml
- cmds/core/shutdown/shutdown_linux.go
- cmds/exp/fdtdump/fdtdump.go
- cmds/exp/pflask/pflask.go
- go.mod
- go.sum
- pkg/dt/print.go
- pkg/ipmi/ipmi.go
- vendor/github.com/google/go-tpm/legacy/tpm2/tpm2.go
- vendor/github.com/google/go-tpm/tpm2/constants.go
- vendor/github.com/google/go-tpm/tpm2/crypto.go
- vendor/github.com/google/go-tpm/tpm2/reflect.go
- vendor/github.com/google/go-tpm/tpm2/sessions.go
- vendor/github.com/google/go-tpm/tpm2/structures.go
- vendor/github.com/google/go-tpm/tpm2/tpm2.go
- vendor/github.com/google/go-tpm/tpm2/transport/open_other.go
- vendor/github.com/google/go-tpm/tpm2/transport/open_windows.go
- vendor/github.com/google/go-tpm/tpm2/transport/tpm.go
- vendor/modules.txt
To enable the build of more u-root cmdlets @chrisfenner made a patch to fix the build issues. This PR updates the go-tpm module to commit [`d96ccf71568571dba925660724354682fe8e5fa2`](https://github.com/google/go-tpm/tree/d96ccf71568571dba925660724354682fe8e5fa2).
This goes hand in hand with issue [#3105](https://github.com/u-root/u-root/issues/3105) since go-tpm also requires the new go version.
> modules: udpdate go-tpm to incorporate tinygo issue fixes

- pkg/boot/multiboot/internal/trampoline/trampoline_linux_amd64.go
- pkg/boot/multiboot/internal/trampoline/trampoline_linux_amd64.s
- pkg/boot/multiboot/internal/trampoline/trampoline_linux_amd64_tinygo.go
- pkg/boot/multiboot/internal/trampoline/trampoline_tinygo.h
- pkg/boot/multiboot/multiboot.go
translate multiboot go-style assembly trampolines to CGO and C-style inline assembly to build cmdlets {esxiboot,ftbnetboot,localboot}.
```
$ export CGO_ENABLED=1; tinygo build -tags tinygo.enable,netgo,purego,noasm .
```
> tinygo: add cgo implementation for trampoline code

- cmds/core/mount/mount_unix.go
Shows what's mounted if run with no args.
Works as a mount commant:
```
root@freebsd:~/u-root/cmds/core/mount # ./mount
/dev/gpt/rootfs on / (ufs,0x205000)
devfs on /dev (devfs)
root@freebsd:~/u-root/cmds/core/mount # ./mount -t msdosfs /dev/gpt/efiesp /boot/efi
root@freebsd:~/u-root/cmds/core/mount # ./mount
/dev/gpt/rootfs on / (ufs,0x205000)
devfs on /dev (devfs)
/dev/gpt/efiesp on /boot/efi (msdosfs,0x1000)
```
The Go constants are not up to date with freebsd, so it will show
flags it could not interpret in hex.
> add mount_unix.go

- cmds/core/ip/link_linux.go
Add a missing parsing function for the IP link command, as detailed in #3119
> cmds/core/ip: use group parameter in link set command

- cmds/core/kexec/kexec_linux.go
The current documentation implies the extra file needs to be a cpio, which is not true; the file can be anything.
> correct the kexec documentation concerning -x/--extra

- cmds/core/kexec/kexec_linux.go
- cmds/core/kexec/kexec_test.go
The --append switch claimed to append to the cmdline, but in fact
behaved no differently than -c/--cmdline.
Have the --append switch append to existing cmdline.
Also, redo the confusing documentation of the switches,
which imply that -c/--cmdline "append" to the command line,
which they do not.
Tidying up: remove the (shorthand) comment from the flag help.
It does not add anything useful.
> kexec: fix --append switch

- cmds/core/tty/tty.go
On systems where /dev/fd is a symbolic link traverse of a /dev directory will be stopped early.
> cmds/core/tty: fix /dev/fd symbolic link

- .golangci.yml
- cmds/cluster/nodestats/main.go
- cmds/exp/lsfabric/lsfabric.go
- cmds/fwtools/spidev/spidev_linux.go
- pkg/boot/linux/load_linux_amd64.go
- pkg/msr/msr_linux_amd64.go
- tools/vpdbootmanager/get.go
- uroot_test.go
will catch %v -> %w issues and can be extended in future with errros.Is (comparison) and errros.As (asserts).
> add errorlint linter

- cmds/exp/tcpdump/main.go
- cmds/exp/tcpdump/main_test.go
The description of the flag was already present, but only printed on invalid use, not on `-h` flag. 
This PR fixes this and also prints the flag descriptions when calling the command with `-h`
> cmds/exp/tcpdump: add flag description to output of -h flag

- cmds/core/strace/strace_linux.go
This comit modifies the  behavior of the `strace` command. Now if the user specifies an output file with `-o`, that file will only contain the `strace` output and not the program's `stderr` as well.
This allows users to redirect program `stdout` and `stderr` but keep the `strace` output separate.
> cmds/core/strace: Write only strace output to file.

- cmds/core/ip/address_linux.go
- cmds/core/ip/address_linux_test.go
- cmds/core/ip/monitor_linux.go
- cmds/core/ip/tcp_metrics_linux.go
- cmds/core/ip/tcp_metrics_linux_test.go
These commit fixes 3 separate minor parsing problems in the IP command.
1. Commit
Current state: 
```
sudo /usr/local/go/bin/go run . address show dev TestDev
1: lo: <UP,LOOPBACK> mtu 65536 state UNKNOWN group default
link/loopback
inet 127.0.0.1 scope host lo
valid_lft forever preferred_lft forever
inet6 ::1 scope host
valid_lft forever preferred_lft forever
2: enp2s0f0: <UP,BROADCAST,MULTICAST> mtu 1500 state DOWN group default
link/ether 00:2b:67:e1:ac:67
3: enp5s0: <UP,BROADCAST,MULTICAST> mtu 1500 state DOWN group default
link/ether 00:2b:67:e1:ac:66
4: enp7s0f3u1u2c2: <UP,BROADCAST,MULTICAST> mtu 1500 state UP group default
link/ether a0:ce:c8:bc:76:a9
inet 10.93.128.226 brd 10.93.129.255 scope global enp7s0f3u1u2c2
valid_lft 69555sec preferred_lft 69555sec
inet6 …
```
> cmds/core/ip: fix parsing of ip addr show

- cmds/core/ip/ip_linux.go
- cmds/core/ip/link_linux.go
- cmds/core/ip/tunnel_linux.go
- cmds/core/ip/xfrm_linux.go
- cmds/core/ip/xfrm_policy_linux.go
Some of the help-texts of the ip command were not up-to-date with the implementation. I've removed any objects which are currently not supported by the u-root version. This is accordingly to the changes proposed in https://github.com/u-root/u-root/pull/3015.
> cmds/core/ip: update help text for unsupported options

- pkg/brctl/brctl.go
Output of `brctl show` before this change:
```
>sudo ./brctl show
bridge name                   bridge id     STP enabled           interfaces
```
There is no output even though there should be output, because there is a bug in reading the bridge path.
Output after this change
```
>sudo ./brctl show
bridge name          bridge id          STP enabled   interfaces 
docker0             8000.0242abf40566  false       veth63d5e4e 
dummyBridge        1f40.000000000000  false 
virbr0             8000.5254008f5d84  true
```
> Fix brctl/show functionality

- cmds/core/ip/address_linux.go
Under certain conditions, the addresses of a device to be filtered were skipped because the function that checks the filter of the command had erroneous checks. 
Working example with the fix:  
```
❯ ./ip addr show dev Test
144: Test: <BROADCAST> mtu 4000 state DOWN group default
link/ether 56:ef:8e:34:50:04
cmds/core/ip [ main][$!][🐹 v1.23.0][☁️  (eu-central-1)][☁️  fabian.wienand@9elements.com]
➜ sudo ./ip addr add 192.0.0.2/24 dev Test
cmds/core/ip [ main][$!][🐹 v1.23.0][☁️  (eu-central-1)][☁️  fabian.wienand@9elements.com]
➜ ./ip addr show dev Test
144: Test: <BROADCAST> mtu 4000 state DOWN group default
link/ether 56:ef:8e:34:50:04
inet 192.0.0.2 brd 192.0.0.255 scope global Test
valid_lft forever preferred_lft forever
cmds/core/ip [ main][$!][🐹 v1.23.0][☁️  (eu-central-1)][☁️ …
```
> cmds/core/ip: fix parsing of ip addr flush

- cmds/core/ip/tcp_metrics_linux.go
Added a newline to the help text of the tcpdump command:
```
➜ ./ip tcpmetrics help
Usage:  ip tcp_metrics/tcpmetrics { COMMAND | help }
ip tcp_metrics show SELECTOR
SELECTOR := [ [ address ] PREFIX ]
```
resolves #3198
> cmds/core/ip: add newline to end of tcpmetrics subcommand help text

- cmds/core/dd/dd.go
- cmds/core/dd/dd_test.go
With this change, dd runs in a single process, and uses zero copy when possible.
Before this change, it ran at best 1/2 the speed of the GNU dd.
WIth this change, it frequently is much faster.
```
time ./dd if=/dev/zero of=/dev/null ibs=1048576 obs=1048576 status=progress count=65536
68719476736 bytes (68719.477 MB, 65536.000 MiB) copied, 1.987 s, 34589.234 MB/s
GNU dd
time dd if=/dev/zero of=/dev/null ibs=1048576 obs=1048576 status=progress count=65536
55726571520 bytes (56 GB, 52 GiB) copied, 3 s, 18.6 GB/s
65536+0 records in
65536+0 records out
68719476736 bytes (69 GB, 64 GiB) copied, 3.69293 s, 18.6 GB/s
```
the u-root dd is twice as fast for lots of data.
For small data, it is still competitive:
```
time dd if=4m of=/dev/null ibs=1048576 obs=1048576 status=progress count=65536 …
```
> simplify dd and let it use go runtime and kernel intelligence

- cmds/core/ip/neigh_linux.go
- cmds/core/ip/neigh_linux_test.go
NUD_NONE is 0x00 and not "UNKNOWN"
> cmds/core/ip: fix getState returning incorrect state

- cmds/extra/tsort/bench.sh
- cmds/extra/tsort/generate_graph_fixtures.go
- cmds/extra/tsort/graph.go
- cmds/extra/tsort/graph_test.go
- cmds/extra/tsort/set.go
- cmds/extra/tsort/set_test.go
- cmds/extra/tsort/tsort.go
- cmds/extra/tsort/tsort_test.go
This PR improves the performance of `tsort` on acyclic graphs (the usual kind of input) by ~12% and reduces the number of memory allocations by ~94%, at the cost of ~38% extra memory in total.
I'd totally understand if the extra memory cost of this change is seen as too prohibitive to merge in. 😁 
For cyclic graphs, allocations improved by ~7% but other performance/allocation changes seem inconclusive.
Benchmarks were ran with `./bench.sh`. They assume that [uutils](https://github.com/uutils/coreutils), a competing coreutils implementation in Rust, has been installed on the path with their tsort at `uutsort`. I'd be more than happy to remove or change `./bench.sh` or move it somewhere else later.
For context, the benchmarks show that for the optimized u-root tsort vs uutils tsort, uutils …
> Improve `tsort` performance

- pkg/kmodule/compression.go
Issues #3232 #3226 #3225 uncovered the failing build of compression-related commands when using tinygo.
> remove tinygo exclusion build tag from kmoudle compression handler

- pkg/hsskey/filereader.go
- pkg/hsskey/filereader_test.go
- pkg/hsskey/hsskey.go
Add the ability for the caller to specify different sysfs paths to look for an eeprom.
> Seach for the HSS in any sysfs path.

- pkg/memio/arch.go
- pkg/memio/arch_tinygo.go
- pkg/memio/archport_linux.go
- pkg/memio/ioport_linux_tinygo.h
- tools/tinygo-buildstatus/statusquo.go
Add tinygo support for the `memio` package.
When building commands such as `io` the following build error can observed:
```
...
../../../pkg/memio/archport_linux.go:46: linker could not find symbol github.com/u-root/u-root/pkg/memio.archInl
../../../pkg/memio/archport_linux.go:48: linker could not find symbol github.com/u-root/u-root/pkg/memio.archInw
../../../pkg/memio/archport_linux.go:50: linker could not find symbol github.com/u-root/u-root/pkg/memio.archInb
../../../pkg/memio/archport_linux.go:70: linker could not find symbol github.com/u-root/u-root/pkg/memio.archOutl
../../../pkg/memio/archport_linux.go:72: linker could not find symbol github.com/u-root/u-root/pkg/memio.archOutw
../../../pkg/memio/archport_linux.go:74: linker could not find symbol …
```
> tinygo port for pkg/memio

- pkg/boot/universalpayload/handoffblock.go
- pkg/boot/universalpayload/trampoline_amd64.s
- pkg/boot/universalpayload/trampoline_arm64.s
- pkg/boot/universalpayload/utilities.go
commit 1: "pkg/boot/universalpayload: Move Graphic and Serial Port out of PCI RB" is used to align with logic update in EDK2 UPL impementation.
commit 2: "pkg/boot/universalpayload: Refine trampoline code" is used to fix unexpected behavior, we found this unexpected behavior in when using different Golang tool chain version and integrate with many u-root commands.
commit 3: "pkg/boot/universalpayload: Skip reporting PCI Root Bridge resource region" is used to fix ASSERTION when UPL scan PCI bus.
> pkg/boot/universalpayload: Refine FDT node info; refine assembly code and skip reporting PCI ROOT bridge resource region

- .github/workflows/cifuzz.yml
In one week [1] `actions/{download,upload}-artifacts@v3` will be deprecated. The CI in PR #3278 failed due to this issue.
This PR updates the fuzzing workflow to use the new version.
[1]: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> ci: updat cifuzz workflow to use artifact@v4

- cmds/core/netcat/listen_test.go
The test is fragile, as it depends on how ::1 is named in /etc/hosts, but for now, this will at least work in github CI.
Something just broke it in the the last few days.
> Fix netcat test

- pkg/boot/universalpayload/trampoline_tinygo_amd64.h
- pkg/boot/universalpayload/trampoline_tinygo_arm64.h
- pkg/boot/universalpayload/utilities_arch_amd64_tinygo.go
- pkg/boot/universalpayload/utilities_arch_arm64_tinygo.go
Tinygo build utilizes inline assembly code, we can use relative address to fetch all required variables for tramploine. Update trampoline code for both ARM64 and AARCH64 to simplify trampoline boot logic.
> pkg/boot/universalpayload: Update trampoline code for tinygo

- pkg/boot/bzimage/bzimage.go
- pkg/boot/bzimage/bzimage_ramfs.go
This PR allows compilation of u-root bzimage package under [tamago](https://github.com/usbarmory/tamago) enabling us to [boot Linux kernels in bzImage format](https://github.com/usbarmory/armory-boot/blob/master/exec/linux_amd64.go) on bare metal.
This is the first step for us to run this on real hardware and implement a bare metal Go bootloader.
Example [invocation in tamago-example](https://github.com/usbarmory/tamago-example/blob/development/cmd/linux.go):
```
ssh 10.0.0.1
tamago/amd64 (go1.23.6) • 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
...
> 9p
starting 9p remote filesystem server
access with: `mount -t 9p -o trans=tcp,noextend 10.0.0.1 <path>`
mount -t 9p -o trans=tcp,noextend 10.0.0.1 /tmp/tamago
cp bzImage /tmp/tamago
ssh 10.0.0.1
tamago/amd64 (go1.23.6) • 11th Gen Intel(R) …
```
> allow compilation of bzimage pkg under GOOS=tamago

- pkg/boot/universalpayload/handoffblock.go
- pkg/boot/universalpayload/utilities_arch_amd64.go
- pkg/boot/universalpayload/utilities_arch_amd64_tinygo.go
- pkg/boot/universalpayload/utilities_arch_arm64.go
- pkg/boot/universalpayload/utilities_arch_arm64_tinygo.go
- pkg/boot/universalpayload/utilities_unimplemented.go
PL011 device is used as serial port device in universalpayload ARM64 implementation, we need to pass memory region information of PL011 device for universalpayload to create corresponding memory mapping.
> pkg/boot/universalpayload: Append ARM UART memory region info

- pkg/pci/class.go
Add commonly used class codes for storage devices.
Fixes: `pci` shows ClassUnknown for AHCI and NVMe disks.
> pkg/pci: Add missing class codes

- cmds/core/ip/route_linux.go
- cmds/core/ip/route_linux_test.go
This is a fix for calling 'ip route' without further arguments. It now results in 'ip route show' as expected.
Fixes #3201
> Fix ip route

- pkg/boot/universalpayload/utilities_arch_amd64_tinygo.go
- tools/tinygo-buildstatus/statusquo.go
Add `archGetAcpiRsdpData()` to amd64 tinygo utilities for universalpayload. This removes the current `kexec` build error:
```
../../../pkg/boot/universalpayload/universalpayload.go:51:28: undefined: archGetAcpiRsdpData
```
> tinygo: add archGetAcpiRsdpData function for amd64

- .golangci.yml
Release v6.5.0 adds the feature that the JSON schema is automatically verified. Update config to adhere to the scheme. The error was first discovered in the [CI run](https://github.com/u-root/u-root/actions/runs/13355556419/job/37325126174?pr=3295#step:4:34) for PR #3295.
This can be verified locally by
```
$ tinygoci-lint config verify
```
> ci: update golangci-lint config

- tools/tinygo-buildstatus/main.go
- tools/tinygo-buildstatus/statusquo.go
There are cmdlets that can and should be ingored for target oses, such as the bind command. These commands are designed specifically for other OSes and will never be ported. This skipping is reported to the logs of the builder
> ci: add ignore list to not throw error

- .circleci/images/ovmf-amd64/Dockerfile
- .circleci/images/ovmf-arm64/Dockerfile
Add pre-built AMD64 OVMF binary from Ubuntu offical ovmf package, pre-built ARM64 OVMF binary released from Linaro organization.
> ci: Add pre-built OVMF binaries for AMD64 and ARM64

- pkg/boot/universalpayload/utilities.go
Modify offset addresses to create more space for HOBs.
> pkg/boot/universalpayload: Make space for HOB

- cmds/core/netstat/netstat_linux.go
- pkg/netstat/interfaces.go
* Fix crash upon conflicting `netstat_linux` options.
* Fix typo in `--interface` help text.
* Add delay to `--continuous` loop when used with `--interface` or `--interfaces`.
> Netstat tweaks

- pkg/netstat/sockets.go
~~~
Both NetSockets.readData() and UnixSockets.readData() try to parse kernel
space pointers from files under /proc/net. Such kernel pointer values are
obfuscated (hashed) from userspace, in order to thwart attacks from user
space, while preserving the unicity of said pointer values:
https://docs.kernel.org/core-api/printk-formats.html#plain-pointers
If the kernel lacks entropy for said hashing, then it must give up the
unicity of the formatted values, but it still keeps them confidential: it
prints them as "(____ptrval____)", using underscores for padding to the
requested width.
In turn, such strings trip up the fmt.Sscanf("%X") parsing verbs in
NetSockets.readData() and UnixSockets.readData().
The parsed pointer values are not used for anything, so just don't try to
parse them as …
> pkg/netstat: ignore kernel space pointers under /proc/net

- pkg/netcat/config.go
- pkg/netcat/config_test.go
- pkg/netcat/const.go
1. The commands
netcat --listen --unixsock       PATHNAME
netcat --listen --unixsock --udp PATHNAME
uselessly append the default port (":31337") to PATHNAME, leading to unix domain socket names such as PATHNAME:31337 in the filesystem.
Fix the bug, and add the missing unit test cases.
2. Netcat currently requires the user to pass IPv6 addresses on the command line in square bracket notation. This is inconsistent with Nmap's netcat.
Take IPv6 addresses from the user without square brackets, and supply them internally with `net.JoinHostPort()`. This affects multiple IPv6-related code paths (listen mode, connect mode with portscan off, connect mode with portscan on).
> pkg/netcat: fix address formatting for listening unix domain, and all IPv6, sockets

- integration/generic-tests/netstat_test.go
While working on the patch that would become commit e7b6bdb7129c ("integration/generic-tests: add netstat_test", 2025-03-20), I replaced the Kill in the final sequence
if err := vm.Kill(); err != nil {
t.Errorf("Kill: %v", err)
}
_ = vm.Wait()
with Wait, but failed to remove the now-superfluous second Wait. Do that now.
(The Kill is unnecessary because the VM shuts down gracefully anyway, with "TESTS PASSED MARKER".)
> integration/generic-tests/netstat_test: remove leftover line

- .circleci/config.yml
- .github/workflows/tests.yml
- cmds/core/netcat/connect.go
- cmds/core/netcat/connect_test.go
- cmds/core/netcat/listen.go
- cmds/core/netcat/netcat.go
- cmds/core/netcat/netcat_test.go
- cmds/core/netcat/packet.go
- integration/generic-tests/netcat_test.go
The front of the series fixes some further problems in the `netcat` command. The tail of the series adds stream (TCPv4, TCPv6, UNIX) and datagram (UDPv4, UDPv6, UNIX) integration tests, using two VMs.
> Netcat integration test

- cmds/core/kexec/kexec_linux.go
- pkg/boot/universalpayload/universalpayload.go
- pkg/boot/universalpayload/utilities.go
- pkg/boot/universalpayload/utilities_test.go
- pkg/smbios/smbios.go
smbios package provides method to retrieve SMBIOS info, this method tries to get SMBIOS3 info first, and then SMBIOS info. However, we have no way to figure out this is SMBIOS3 or SMBIOS info.
In order to integrate with TianoCore EDk2 UPL implementation, we need to provide SMBIOS3 info in device tree info since SMBIOS3 info is constructed from device tree info and only can be constructed from device tree info. In this case, we need to ensure that the SMBIOS info that is retrieved from smbios package is SMBIOS3 info not a SMBIOS, and provide SMBIOS3 info in device tree.
> Add SMBIOS3 info in device tree node

- cmds/core/ip/neigh_linux.go
- cmds/core/ip/neigh_linux_test.go
- cmds/core/ip/parsing_linux.go
- cmds/core/ip/parsing_linux_test.go
- integration/generic-tests/ip_test.go
Overhauled some parts of the `ip neigh` cmd. 
- `ip neigh add` had a bug, which defaulted the entry to an erroneous state.
- `ip neigh flush` and `ip neigh show` have new filter capabilities. 
- added the `neigh` cmds to the ip integration test.
> ip neigh improvements + integration test

- cmds/exp/traceroute/main.go
- pkg/traceroute/defaults.go
- pkg/traceroute/icmp4.go
- pkg/traceroute/icmp6.go
- pkg/traceroute/tcp4.go
- pkg/traceroute/tcp6.go
- pkg/traceroute/trace.go
- pkg/traceroute/traceroute.go
- pkg/traceroute/udp4.go
- pkg/traceroute/udp6.go
Currently, the CLI offers the option to set a custom destination port for trace probes, which is currently unused. This PR adds functionality to propagate it into the trace.
According to the man page, the `--port` option behaves differently depending on the protocol type:
- UDP: base port for randomization
- ICMP: start of sequence number
- TCP: exact port to probe on
> cmd/exp: propagate -p/-port in traceroute

- go.mod
With recent versions of Go: "Starting in Go 1.21, the Go distribution consists of a go command and a bundled Go toolchain, which is the standard library as well as the compiler, assembler, and other tools."
https://go.dev/doc/toolchain
Sounds like a great idea.
Unfortunately, this breaks badly if go.mod has a version like this: go 1.24
which people have used for several years.
You get the incredibly non-intuitive message:
root@localhost:~/go/src/github.com/u-root/u-root# go version go: downloading go1.24 (linux/amd64)
go: download go1.24 for linux/amd64: toolchain not available
even though go 1.xx has worked for years in go.mod.
Just use the full version in go.mod:
go 1.24.0
and then:
go version
go version go1.24.0 linux/amd64
This has been broken for some time, I just never understood …
> Change the version in go.mod so go download works

- pkg/boot/universalpayload/utilities.go
- pkg/boot/universalpayload/utilities_64bit_test.go
- pkg/boot/universalpayload/utilities_test.go
pkg/boot/universalpayload: Update PCI Root Bridge fetch logic
Previous, PCI Root Bridge info is constructed from all resource files
in /sys/bus/pci/devices folder, it applies to single segment platform.
In order to support multiple segments platform, we need to get PCI
hierarchy from /sys/devices/pci* device nodes. Since PCI device nodes
under this format of path are align with actual PCI hierarchy.
For instance, following is hierarchy snippet from command "lspci -t":
\-[0000:00]-+-00.0
+-1c.0-[01]--+-00.0
\-00.1
+-1c.5-[03-04]----00.0-[04]----00.0
Corresponding device nodes layout in /sys/devices/pci* are as follows:
/sys/devices/pci0000:00/0000:00:1c.0/0000:01:00.0
/sys/devices/pci0000:00/0000:00:1c.5/0000:03:00.0/0000:04:00.0
> Update logic to construct PCI Root Bridge device tree nodes.

- pkg/boot/universalpayload/utilities_arch_arm64.go
This allows users to specify the physical address size of their CPU for cases where the value is not automatically derivable (e.g. ARM).
> Add UROOT_PHYS_ADDR_SIZE option for UPL

- go.mod
- go.sum
- pkg/core/cat/cat.go
- pkg/core/find/find.go
- pkg/core/mkdir/mkdir.go
- pkg/core/rm/rm.go
- pkg/core/touch/touch.go
- pkg/core/xargs/xargs.go
- vendor/github.com/spf13/pflag/.editorconfig
- vendor/github.com/spf13/pflag/.golangci.yaml
- vendor/github.com/spf13/pflag/README.md
- vendor/github.com/spf13/pflag/bool_func.go
- vendor/github.com/spf13/pflag/count.go
- vendor/github.com/spf13/pflag/errors.go
- vendor/github.com/spf13/pflag/flag.go
- vendor/github.com/spf13/pflag/func.go
- vendor/github.com/spf13/pflag/golangflag.go
- vendor/github.com/spf13/pflag/ip.go
- vendor/github.com/spf13/pflag/ipnet_slice.go
- vendor/github.com/spf13/pflag/string_array.go
- vendor/github.com/spf13/pflag/text.go
- vendor/github.com/spf13/pflag/time.go
- vendor/modules.txt
* Joint flags like `rm -rf` wasn't properly working, requiring to type them separately as `-r -f`. Fixed that by using `unixflag.ArgsToGoArgs` on the places where it was missing.
* Fix `find` to allow flags or argument to be given at any position. Moved to `pflag` here because the Go's `flag` required the flags to be given before the arguments. `find` is a special snowflake ❄️ because it have single-dash flags that should not be interpreted as shortant.
I considered moving completely to [`pflag`](https://github.com/spf13/pflag), but there are some minor behavior differences that made it non-trivial. We can still consider in the future, though.
> fix(core-utils): fix use of joint flags, like in `rm -rf` + fix `find`

- .circleci/images/upl-fit-amd64/Dockerfile
- .circleci/images/upl-fit-arm64/Dockerfile
Update code base for UPL Fit code base for both AMD64 and ARM64 on top of tianocore/edk2-stable202508.
edk2-stable202508 is official release from tianocore EDK2 code base, it ensures code base of UPL Fit image easy to trace.
> ci: Update EDK2 UPL Fit code base to tianocore/edk2-stable202508

- .github/workflows/test-images.yml
- tools/tinygo-buildstatus/statusquo.go
OVMF and Universal Payload binaries are required to integrate Universal Payload solution in Github CI.
> CI: Add OVMF and Universal Payload binaries docker push action
